[build-system]
requires = ["setuptools>=68", "wheel", "numpy==2.3.2"]
build-backend = "setuptools.build_meta"

[project]
name = "swrlzkamico-native"
version = "0.1.0"
description = "§wyrlz Vercel server native R39 acceleration package"
requires-python = ">=3.12"
dependencies = [
  "fastapi==0.116.1",
  "numpy==2.3.2",
  "pydantic==2.11.7",
]
