#define PY_SSIZE_T_CLEAN
#include <Python.h>
#include <numpy/arrayobject.h>
#include <stdint.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>

static inline float fp16_to_f32(uint16_t h){uint32_t s=(h>>15)&1u,e=(h>>10)&31u,f=h&1023u,out;if(e==0){if(f==0)out=s<<31;else{int shift=0;while((f&0x400u)==0){f<<=1;shift++;}f&=0x3ffu;out=(s<<31)|((uint32_t)(127-14-shift)<<23)|(f<<13);}}else if(e==31)out=(s<<31)|0x7f800000u|(f<<13);else out=(s<<31)|((e+(127-15))<<23)|(f<<13);float v;memcpy(&v,&out,4);return v;}
static inline float bf16_to_f32(uint16_t b){uint32_t u=((uint32_t)b)<<16;float v;memcpy(&v,&u,4);return v;}
static inline uint16_t rd16(const uint8_t *p){return (uint16_t)p[0]|((uint16_t)p[1]<<8);}
static void q4k_scales(const uint8_t *sc,int scale[8],int minv[8]){for(int j=0;j<4;++j){scale[j]=sc[j]&63;minv[j]=sc[j+4]&63;}for(int j=4;j<8;++j){scale[j]=(sc[j+4]&15)|((sc[j-4]>>6)<<4);minv[j]=(sc[j+4]>>4)|((sc[j]>>6)<<4);}}
static inline void add_scaled(float *y,const float *x,int batch,float w){for(int t=0;t<batch;++t)y[t]+=w*x[t];}
static int row_bytes(const char *kind,int cols){if(strcmp(kind,"f32")==0)return cols*4;if(strcmp(kind,"f16")==0||strcmp(kind,"bf16")==0)return cols*2;if(strcmp(kind,"q4_0")==0&&cols%32==0)return(cols/32)*18;if(strcmp(kind,"q8_0")==0&&cols%32==0)return(cols/32)*34;if(strcmp(kind,"q4_k")==0&&cols%256==0)return(cols/256)*144;if(strcmp(kind,"q6_k")==0&&cols%256==0)return(cols/256)*210;return 0;}
static void row_f32(const uint8_t *row,int cols,const float *x,int batch,float *y){const float *w=(const float*)row;for(int i=0;i<cols;++i)add_scaled(y,x+(size_t)i*batch,batch,w[i]);}
static void row_f16(const uint8_t *row,int cols,const float *x,int batch,float *y){for(int i=0;i<cols;++i)add_scaled(y,x+(size_t)i*batch,batch,fp16_to_f32(rd16(row+2*i)));}
static void row_bf16(const uint8_t *row,int cols,const float *x,int batch,float *y){for(int i=0;i<cols;++i)add_scaled(y,x+(size_t)i*batch,batch,bf16_to_f32(rd16(row+2*i)));}
static void row_q40(const uint8_t *row,int cols,const float *x,int batch,float *y,float *scratch){float *local=scratch;for(int b=0;b<cols/32;++b){memset(local,0,(size_t)batch*sizeof(float));const uint8_t *p=row+b*18,*q=p+2;float d=fp16_to_f32(rd16(p));int base=b*32;for(int i=0;i<16;++i){float w0=(float)((int)(q[i]&15)-8),w1=(float)((int)(q[i]>>4)-8);const float *x0=x+(size_t)(base+i)*batch,*x1=x+(size_t)(base+16+i)*batch;for(int t=0;t<batch;++t)local[t]+=w0*x0[t]+w1*x1[t];}for(int t=0;t<batch;++t)y[t]+=d*local[t];}}
static void row_q80(const uint8_t *row,int cols,const float *x,int batch,float *y,float *scratch){float *local=scratch;for(int b=0;b<cols/32;++b){memset(local,0,(size_t)batch*sizeof(float));const uint8_t *p=row+b*34;float d=fp16_to_f32(rd16(p));const int8_t *q=(const int8_t*)(p+2);int base=b*32;for(int i=0;i<32;++i){const float *xi=x+(size_t)(base+i)*batch;float w=(float)q[i];for(int t=0;t<batch;++t)local[t]+=w*xi[t];}for(int t=0;t<batch;++t)y[t]+=d*local[t];}}
static void row_q4k(const uint8_t *row,int cols,const float *x,int batch,float *y,float *scratch){float *sx0=scratch,*sx1=scratch+batch,*qx0=scratch+2*batch,*qx1=scratch+3*batch;for(int b=0;b<cols/256;++b){const uint8_t *p=row+b*144;float d=fp16_to_f32(rd16(p)),dm=fp16_to_f32(rd16(p+2));const uint8_t *sc=p+4,*qs=p+16;int scale[8],minv[8];q4k_scales(sc,scale,minv);int base=b*256;for(int g=0;g<4;++g){memset(sx0,0,(size_t)batch*sizeof(float));memset(sx1,0,(size_t)batch*sizeof(float));memset(qx0,0,(size_t)batch*sizeof(float));memset(qx1,0,(size_t)batch*sizeof(float));const uint8_t *q=qs+g*32;int o=base+g*64;for(int i=0;i<32;++i){const float *x0=x+(size_t)(o+i)*batch,*x1=x+(size_t)(o+32+i)*batch;float q0=(float)(q[i]&15),q1=(float)(q[i]>>4);for(int t=0;t<batch;++t){float a=x0[t],c=x1[t];sx0[t]+=a;sx1[t]+=c;qx0[t]+=q0*a;qx1[t]+=q1*c;}}for(int t=0;t<batch;++t){y[t]+=d*(float)scale[2*g]*qx0[t]-dm*(float)minv[2*g]*sx0[t];y[t]+=d*(float)scale[2*g+1]*qx1[t]-dm*(float)minv[2*g+1]*sx1[t];}}}}
static void row_q6k(const uint8_t *row,int cols,const float *x,int batch,float *y){for(int b=0;b<cols/256;++b){const uint8_t *p=row+b*210,*ql=p,*qh=p+128;const int8_t *sc=(const int8_t*)(p+192);float d=fp16_to_f32(rd16(p+208));int base=b*256;for(int half=0;half<2;++half){const uint8_t *lo0=ql+half*64,*lo1=ql+half*64+32,*hi=qh+half*32;int s=half*8,o=base+half*128;for(int i=0;i<32;++i){int ix=i/16,q1=(int)((lo0[i]&15)|(((hi[i]>>0)&3)<<4))-32,q2=(int)((lo1[i]&15)|(((hi[i]>>2)&3)<<4))-32,q3=(int)(((lo0[i]>>4)&15)|(((hi[i]>>4)&3)<<4))-32,q4=(int)(((lo1[i]>>4)&15)|(((hi[i]>>6)&3)<<4))-32;const float *x0=x+(size_t)(o+i)*batch,*x1=x+(size_t)(o+32+i)*batch,*x2=x+(size_t)(o+64+i)*batch,*x3=x+(size_t)(o+96+i)*batch;float w1=d*(float)sc[s+ix]*(float)q1,w2=d*(float)sc[s+2+ix]*(float)q2,w3=d*(float)sc[s+4+ix]*(float)q3,w4=d*(float)sc[s+6+ix]*(float)q4;for(int t=0;t<batch;++t)y[t]+=w1*x0[t]+w2*x1[t]+w3*x2[t]+w4*x3[t];}}}}
static PyObject *py_matmat(PyObject *self,PyObject *args){const char *kind=NULL;PyObject *raw_obj=NULL,*x_obj=NULL;int cols=0,rows=0;if(!PyArg_ParseTuple(args,"sOiiO",&kind,&raw_obj,&cols,&rows,&x_obj))return NULL;if(cols<=0||rows<=0){PyErr_SetString(PyExc_ValueError,"cols and rows must be positive");return NULL;}int rb=row_bytes(kind,cols);if(!rb){PyErr_SetString(PyExc_ValueError,"unsupported quantizer or block mismatch");return NULL;}Py_buffer raw;if(PyObject_GetBuffer(raw_obj,&raw,PyBUF_CONTIG_RO)!=0)return NULL;PyArrayObject *x=(PyArrayObject*)PyArray_FROM_OTF(x_obj,NPY_FLOAT32,NPY_ARRAY_IN_ARRAY);if(!x){PyBuffer_Release(&raw);return NULL;}if(PyArray_NDIM(x)!=2||PyArray_DIM(x,0)!=cols){Py_DECREF(x);PyBuffer_Release(&raw);PyErr_SetString(PyExc_ValueError,"x must have shape (cols,batch)");return NULL;}int batch=(int)PyArray_DIM(x,1);if(batch<=0||batch>4096){Py_DECREF(x);PyBuffer_Release(&raw);PyErr_SetString(PyExc_ValueError,"batch must be 1..4096");return NULL;}if(raw.len<(Py_ssize_t)rb*rows){Py_DECREF(x);PyBuffer_Release(&raw);PyErr_SetString(PyExc_ValueError,"raw tensor is shorter than expected");return NULL;}npy_intp dims[2]={rows,batch};PyArrayObject *out=(PyArrayObject*)PyArray_ZEROS(2,dims,NPY_FLOAT32,0);if(!out){Py_DECREF(x);PyBuffer_Release(&raw);return NULL;}const uint8_t *rp=(const uint8_t*)raw.buf;const float *xp=(const float*)PyArray_DATA(x);float *yp=(float*)PyArray_DATA(out);float *scratch=(float*)malloc((size_t)batch*4*sizeof(float));if(!scratch){Py_DECREF(out);Py_DECREF(x);PyBuffer_Release(&raw);return PyErr_NoMemory();}Py_BEGIN_ALLOW_THREADS for(int r=0;r<rows;++r){float *y=yp+(size_t)r*batch;const uint8_t *row=rp+(size_t)r*rb;if(strcmp(kind,"f32")==0)row_f32(row,cols,xp,batch,y);else if(strcmp(kind,"f16")==0)row_f16(row,cols,xp,batch,y);else if(strcmp(kind,"bf16")==0)row_bf16(row,cols,xp,batch,y);else if(strcmp(kind,"q4_0")==0)row_q40(row,cols,xp,batch,y,scratch);else if(strcmp(kind,"q8_0")==0)row_q80(row,cols,xp,batch,y,scratch);else if(strcmp(kind,"q4_k")==0)row_q4k(row,cols,xp,batch,y,scratch);else if(strcmp(kind,"q6_k")==0)row_q6k(row,cols,xp,batch,y);} Py_END_ALLOW_THREADS free(scratch);Py_DECREF(x);PyBuffer_Release(&raw);return(PyObject*)out;}
static PyMethodDef Methods[]={{"matmat",py_matmat,METH_VARARGS,"Direct quantized matrix-matrix multiply for batched prefill."},{NULL,NULL,0,NULL}};static struct PyModuleDef Module={PyModuleDef_HEAD_INIT,"_r39_batch","Native direct-quantized R39 batched prefill kernels",-1,Methods};PyMODINIT_FUNC PyInit__r39_batch(void){import_array();return PyModule_Create(&Module);}
