(()=>{
"use strict";
const STORAGE_KEY="swrlz.vercel.chat.v1";
let status=null,profile=null,menu=null,googleHost=null,googleInitialized=false;
const $=(s,r=document)=>r.querySelector(s);
const api=(path,init={})=>fetch(path,{credentials:"same-origin",cache:"no-store",...init});
function setMode(v){window.SWRLZ_ACCOUNT_MODE=Boolean(v);window.dispatchEvent(new CustomEvent("swrlz:account-change",{detail:{connected:Boolean(v),profile}}));}
function toast(text){const el=$("#toast");if(!el)return;el.textContent=text;el.classList.add("show");clearTimeout(window.__swrlzAccountToast);window.__swrlzAccountToast=setTimeout(()=>el.classList.remove("show"),2800)}
function style(){if($("#swrlz-account-style"))return;const s=document.createElement("style");s.id="swrlz-account-style";s.textContent=`.swrlz-account{margin-top:10px;padding-top:10px;border-top:1px solid var(--line)}.swrlz-account-card{display:flex;align-items:center;gap:10px;width:100%;padding:10px;border:1px solid var(--line);border-radius:14px;background:rgba(255,255,255,.025);color:var(--secondary)}.swrlz-account-avatar{width:32px;height:32px;border-radius:50%;display:grid;place-items:center;flex:0 0 auto;background:linear-gradient(135deg,rgba(56,232,255,.18),rgba(154,85,255,.2));overflow:hidden;font-size:12px;font-weight:800}.swrlz-account-avatar img{width:100%;height:100%;object-fit:cover}.swrlz-account-copy{min-width:0;flex:1}.swrlz-account-copy strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px}.swrlz-account-copy span{display:block;margin-top:3px;color:var(--muted);font-size:10px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.swrlz-account-actions{display:flex;gap:5px;margin-top:7px}.swrlz-account-actions button{flex:1;min-height:32px;padding:0 8px;border:1px solid var(--line);border-radius:9px;cursor:pointer;color:var(--secondary);background:rgba(255,255,255,.035);font-size:10px;font-weight:700}.swrlz-account-actions button:hover{border-color:var(--line-strong);color:var(--text)}.swrlz-google-host{min-height:44px;margin:8px 0 2px;display:flex;justify-content:center}.swrlz-account-note{margin:6px 2px 0;color:var(--muted);font-size:9px;line-height:1.35}.swrlz-importing{opacity:.65;pointer-events:none}`;document.head.append(s)}
function loadGoogle(){if(window.google?.accounts?.id)return Promise.resolve();if(window.__swrlzGoogleLoad)return window.__swrlzGoogleLoad;window.__swrlzGoogleLoad=new Promise((resolve,reject)=>{const existing=document.querySelector('script[src*="accounts.google.com/gsi/client"]');if(existing){existing.addEventListener("load",resolve,{once:true});existing.addEventListener("error",reject,{once:true});return}const s=document.createElement("script");s.src="https://accounts.google.com/gsi/client";s.async=true;s.defer=true;s.onload=resolve;s.onerror=reject;document.head.append(s)});return window.__swrlzGoogleLoad}
function localState(){try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY)||"null");return v&&Array.isArray(v.threads)?v:null}catch(_){return null}}
async function migrateLocal(){const local=localState();if(!local?.threads?.length)return {importedThreads:0,importedMessages:0};const response=await api("/api/account/import-local",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({threads:local.threads})});const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.detail||`History import failed (${response.status})`);return data}
async function hydrateServer(){const response=await api("/api/account/state");const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.detail||`Account state failed (${response.status})`);const threads=Array.isArray(data.threads)?data.threads:[];if(threads.length){const local=localState();const preferred=local?.currentId&&threads.some(t=>t.id===local.currentId)?local.currentId:threads[0].id;localStorage.setItem(STORAGE_KEY,JSON.stringify({version:1,currentId:preferred,threads}));if(typeof window.render==="function")window.render()}profile={...(profile||{}),...(data.profile||{})};return data}
function initials(){const n=profile?.display_name||profile?.displayName||profile?.email||"G";return n.trim().slice(0,2).toUpperCase()}
function renderSignedOut(){if(!menu)return;menu.classList.remove("swrlz-importing");menu.innerHTML="";const card=document.createElement("div");card.className="swrlz-account-card";const av=document.createElement("div");av.className="swrlz-account-avatar";av.textContent="G";const copy=document.createElement("div");copy.className="swrlz-account-copy";const strong=document.createElement("strong");strong.textContent="§wyrlz account";const sub=document.createElement("span");sub.textContent="Not connected · local history stays here";copy.append(strong,sub);card.append(av,copy);menu.append(card);googleHost=document.createElement("div");googleHost.className="swrlz-google-host";menu.append(googleHost);const note=document.createElement("div");note.className="swrlz-account-note";note.textContent="Sign in to save your conversations to the server and carry them between devices.";menu.append(note);renderGoogle();}
function renderSignedIn(){if(!menu)return;menu.classList.remove("swrlz-importing");menu.innerHTML="";googleHost=null;const card=document.createElement("div");card.className="swrlz-account-card";const av=document.createElement("div");av.className="swrlz-account-avatar";if(profile?.picture){const img=document.createElement("img");img.src=profile.picture;img.alt="";av.append(img)}else av.textContent=initials();const copy=document.createElement("div");copy.className="swrlz-account-copy";const strong=document.createElement("strong");strong.textContent=profile?.display_name||profile?.displayName||profile?.email||"Google account";const sub=document.createElement("span");sub.textContent=profile?.email||"Server account connected";copy.append(strong,sub);card.append(av,copy);menu.append(card);const actions=document.createElement("div");actions.className="swrlz-account-actions";const sw=document.createElement("button");sw.type="button";sw.textContent="Switch account";sw.onclick=()=>{if(window.google?.accounts?.id){window.google.accounts.id.disableAutoSelect();renderSignedOut();renderGoogle(true)}else toast("Google sign-in is still loading")};const out=document.createElement("button");out.type="button";out.textContent="Sign out";out.onclick=signOut;actions.append(sw,out);menu.append(actions);const note=document.createElement("div");note.className="swrlz-account-note";note.textContent="Server history is authoritative while signed in.";menu.append(note);}
async function renderGoogle(switching=false){if(!googleHost)return;try{if(!status?.googleClientId){googleHost.textContent="Google sign-in is not configured on this deployment";return}await loadGoogle();if(!googleInitialized){window.google.accounts.id.initialize({client_id:status.googleClientId,callback:handleCredential,auto_select:false,use_fedcm_for_button:true});googleInitialized=true}googleHost.replaceChildren();window.google.accounts.id.renderButton(googleHost,{theme:"outline",size:"large",shape:"rectangular",text:"signin_with",width:240,button_auto_select:false});if(switching)toast("Choose the Google account to use")}catch(e){googleHost.textContent="Google sign-in unavailable";googleHost.title=e.message||"Google Identity Services failed"}}
async function handleCredential(response){try{const r=await api("/api/account/google",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({credential:response.credential})});const data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.detail||`Google sign-in failed (${r.status})`);profile={...(data.profile||{}),...(data.user||{})};setMode(true);menu.classList.add("swrlz-importing");toast("Google account connected — saving your existing chat history…");const imported=await migrateLocal();await hydrateServer();renderSignedIn();menu.classList.remove("swrlz-importing");toast(`Account linked · ${imported.importedMessages||0} prior messages saved`)}catch(e){menu?.classList.remove("swrlz-importing");toast(e.message||"Google sign-in failed")}}
async function signOut(){try{window.google?.accounts?.id?.disableAutoSelect?.();await api("/api/account/logout",{method:"POST"});profile=null;setMode(false);renderSignedOut();toast("Signed out of §wyrlz account")}catch(e){toast(e.message||"Sign out failed")}}
async function boot(){style();status=await api("/api/account/status").then(r=>r.json()).catch(()=>null);const foot=$(".sidebar-foot");if(!foot)return;menu=document.createElement("div");menu.id="swrlzAccountMenu";menu.className="swrlz-account";foot.append(menu);const me=await api("/api/account/me").then(async r=>r.ok?r.json():null).catch(()=>null);if(me?.ok){profile={...(me.profile||{}),...(me.user||{})};setMode(true);try{const imported=await migrateLocal();await hydrateServer();renderSignedIn();if(imported.importedMessages)toast(`Account history synchronized · ${imported.importedMessages} prior messages saved`)}catch(e){renderSignedIn();toast(e.message||"Could not synchronize server history")}}else{setMode(false);renderSignedOut()}}
window.SWRLZ_ACCOUNT_OPEN=()=>menu?.scrollIntoView({behavior:"smooth",block:"nearest"});
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();