(()=>{"use strict";
if(window.__swrlzUserTimeContextInstalled)return;
window.__swrlzUserTimeContextInstalled=true;
const priorFetch=window.fetch.bind(window),PROFILE_KEY='swrlz.user.context.profile.v1',REMIND_WEEK_MS=7*24*60*60*1000,REMIND_MONTH_MS=30*24*60*60*1000,pendingReceipts=new Map();
function streamUrl(input){try{return typeof input==='string'?input:(input?.url||'')}catch(_){return ''}}
function isStream(input,init){const method=String(init?.method||input?.method||'GET').toUpperCase();return method==='POST'&&/(?:[?&]action=stream(?:&|$)|\/stream(?:[?#]|$))/i.test(streamUrl(input))}
function parseBody(init){if(typeof init?.body!=='string')return null;try{const v=JSON.parse(init.body);return v&&typeof v==='object'?v:null}catch(_){return null}}
function currentThreadSafe(){try{return typeof currentThread==='function'?currentThread():null}catch(_){return null}}
function pad(value){return String(value).padStart(2,'0')}
function offsetLabel(date){const mins=-date.getTimezoneOffset(),sign=mins>=0?'+':'-',abs=Math.abs(mins);return `${sign}${pad(Math.floor(abs/60))}:${pad(abs%60)}`}
function zoneName(){try{return Intl.DateTimeFormat().resolvedOptions().timeZone||'local'}catch(_){return 'local'}}
function defaults(){return{schemaVersion:1,temporal:{enabled:false,permission:'unset',source:'none',reminderPreference:'occasional',declineCount:0,lastPromptedAt:0,updatedAt:0,timeZone:''},profileLocation:{city:'',state:'',country:'',useForTemporalResolution:false}}}
function loadProfile(){try{const raw=JSON.parse(localStorage.getItem(PROFILE_KEY)||'null');if(!raw||typeof raw!=='object')return defaults();const base=defaults();return{...base,...raw,temporal:{...base.temporal,...(raw.temporal||{})},profileLocation:{...base.profileLocation,...(raw.profileLocation||{}),useForTemporalResolution:false}}}catch(_){return defaults()}}
function saveProfile(profile){try{localStorage.setItem(PROFILE_KEY,JSON.stringify(profile));return true}catch(_){return false}}
function updateProfile(mutator){const profile=loadProfile();mutator(profile);profile.temporal.updatedAt=Date.now();saveProfile(profile);renderSettings();return profile}
function allowed(profile=loadProfile()){return profile.temporal.enabled===true&&profile.temporal.permission==='granted'}
function approvedTimeContext(){const profile=loadProfile();if(!allowed(profile))return{schemaVersion:3,available:false,timeSpecificClaimsAllowed:false,permission:String(profile.temporal.permission||'unset'),source:'none',localDate:'',localTime:'',timeZone:'',utcOffset:''};const date=new Date(),zone=zoneName();return{schemaVersion:3,available:true,timeSpecificClaimsAllowed:true,permission:'granted',source:'device-timezone',localDate:`${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`,localTime:`${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`,timeZone:zone,utcOffset:offsetLabel(date)}}
function receiptFor(payload,ctx){return{requestId:String(payload?.requestId||''),capturedAt:Date.now(),available:ctx.available===true,timeSpecificClaimsAllowed:ctx.timeSpecificClaimsAllowed===true,permission:String(ctx.permission||'unset'),source:String(ctx.source||'none'),timeZone:ctx.available?String(ctx.timeZone||''):'',localTime:ctx.available?String(ctx.localTime||''):'',localDate:ctx.available?String(ctx.localDate||''):'',utcOffset:ctx.available?String(ctx.utcOffset||''):''}}
function annotate(payload,ctx){try{const rid=String(payload?.requestId||'');if(!rid)return;const receipt=receiptFor(payload,ctx);pendingReceipts.set(rid,receipt);const thread=currentThreadSafe(),message=[...(thread?.messages||[])].reverse().find(m=>m?.role==='assistant'&&String(m?.meta?.requestId||'')===rid);if(message){message.meta=message.meta||{};message.meta.temporalContext=receipt;try{typeof saveState==='function'&&saveState()}catch(_){}}}catch(_){}}
function augment(payload){const next={...payload},ctx=approvedTimeContext();next.swrlzUserTimeContext=ctx;annotate(next,ctx);return next}
function shouldPrompt(profile=loadProfile()){const t=profile.temporal;if(t.permission==='granted'||t.reminderPreference==='never')return false;const last=Number(t.lastPromptedAt||0);if(!last)return true;const cooldown=Number(t.declineCount||0)>=2?REMIND_MONTH_MS:REMIND_WEEK_MS;return Date.now()-last>=cooldown}
function grant(){updateProfile(p=>{p.temporal.enabled=true;p.temporal.permission='granted';p.temporal.source='device-timezone';p.temporal.timeZone=zoneName();p.temporal.reminderPreference='occasional';p.temporal.lastPromptedAt=Date.now()});closeConsent();try{typeof toast==='function'&&toast('Time-aware context enabled')}catch(_){}}
function decline(never=false){updateProfile(p=>{p.temporal.enabled=false;p.temporal.permission='declined';p.temporal.source='none';p.temporal.declineCount=Number(p.temporal.declineCount||0)+1;p.temporal.lastPromptedAt=Date.now();if(never)p.temporal.reminderPreference='never'});closeConsent()}
function disable(){updateProfile(p=>{p.temporal.enabled=false;p.temporal.permission='declined';p.temporal.source='none';p.temporal.lastPromptedAt=Date.now()})}
function enableFromSettings(){grant()}function setReminder(value){updateProfile(p=>{p.temporal.reminderPreference=value?'occasional':'never'})}
function saveLocation(){const city=document.querySelector('#swrlzProfileCity'),state=document.querySelector('#swrlzProfileState'),country=document.querySelector('#swrlzProfileCountry');updateProfile(p=>{p.profileLocation.city=String(city?.value||'').trim().slice(0,96);p.profileLocation.state=String(state?.value||'').trim().slice(0,96);p.profileLocation.country=String(country?.value||'').trim().slice(0,96);p.profileLocation.useForTemporalResolution=false});try{typeof toast==='function'&&toast('Profile location saved; not used for timezone yet')}catch(_){}}
function injectStyles(){if(document.querySelector('#swrlzTemporalStyles'))return;const style=document.createElement('style');style.id='swrlzTemporalStyles';style.textContent=`#swrlzTemporalConsent{max-width:520px;border:1px solid rgba(56,232,255,.22);border-radius:20px;color:#f7fbff;background:#08101f;padding:0;box-shadow:0 28px 90px rgba(0,0,0,.55)}#swrlzTemporalConsent::backdrop{background:rgba(0,0,0,.64);backdrop-filter:blur(5px)}.swrlz-time-wrap{padding:20px}.swrlz-time-wrap h3{margin:0 0 10px;font-size:18px}.swrlz-time-wrap p{color:#b9ccdd;line-height:1.55;font-size:13px}.swrlz-time-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:16px}.swrlz-time-actions button,.swrlz-time-settings button{border:1px solid rgba(145,169,192,.22);border-radius:11px;padding:9px 12px;color:#f7fbff;background:rgba(17,30,52,.86);cursor:pointer}.swrlz-time-actions button[data-primary=true],.swrlz-time-settings button[data-primary=true]{border-color:rgba(56,232,255,.42);background:rgba(56,232,255,.12)}.swrlz-time-settings{margin-top:18px;padding-top:18px;border-top:1px solid rgba(145,169,192,.16)}.swrlz-time-settings strong{display:block;margin-bottom:6px}.swrlz-time-settings small{display:block;color:#91a9c0;line-height:1.45;margin:6px 0 10px}.swrlz-time-settings .row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.swrlz-time-settings input[type=text]{min-width:120px;flex:1;border:1px solid rgba(145,169,192,.18);border-radius:10px;padding:9px 10px;color:#f7fbff;background:rgba(4,8,18,.75)}`;document.head.appendChild(style)}
function ensureConsent(){if(document.querySelector('#swrlzTemporalConsent'))return document.querySelector('#swrlzTemporalConsent');injectStyles();const d=document.createElement('dialog');d.id='swrlzTemporalConsent';d.innerHTML=`<div class="swrlz-time-wrap"><h3>Share your device clock with §wyrlz?</h3><p>Allow Chat to relay this device's local clock and timezone as factual context. §wyrlz decides what that information means and whether it matters. Precise location is not requested or required.</p><p><strong>Transparency:</strong> device-time facts are attached only after you approve them, and you can turn this off at any time.</p><div class="swrlz-time-actions"><button type="button" data-primary="true" id="swrlzTimeAllow">Allow device time</button><button type="button" id="swrlzTimeLater">Not now</button><button type="button" id="swrlzTimeNever">Don't ask again</button></div></div>`;document.body.appendChild(d);d.querySelector('#swrlzTimeAllow').addEventListener('click',grant);d.querySelector('#swrlzTimeLater').addEventListener('click',()=>decline(false));d.querySelector('#swrlzTimeNever').addEventListener('click',()=>decline(true));return d}
function openConsent(force=false){const p=loadProfile();if(!force&&!shouldPrompt(p))return;updateProfile(x=>{x.temporal.lastPromptedAt=Date.now()});const d=ensureConsent();if(!d.open)d.showModal()}function closeConsent(){const d=document.querySelector('#swrlzTemporalConsent');if(d?.open)d.close()}
function injectSettings(){const body=document.querySelector('#settingsDialog .dialog-body');if(!body||document.querySelector('#swrlzTemporalSettings'))return;injectStyles();const box=document.createElement('div');box.className='swrlz-time-settings';box.id='swrlzTemporalSettings';box.innerHTML=`<strong>Time-aware context</strong><small id="swrlzTimeStatus"></small><div class="row"><button type="button" data-primary="true" id="swrlzTimeEnable">Enable device time</button><button type="button" id="swrlzTimeDisable">Turn off</button><label style="font-size:12px;color:#b9ccdd"><input id="swrlzTimeRemind" type="checkbox"> Allow occasional reminders when off</label></div><small style="margin-top:14px">Future profile location context — stored only. City/state/country are not used to resolve timezone yet.</small><div class="row"><input type="text" id="swrlzProfileCity" placeholder="City (future)"><input type="text" id="swrlzProfileState" placeholder="State/region (future)"><input type="text" id="swrlzProfileCountry" placeholder="Country (future)"><button type="button" id="swrlzLocationSave">Save</button></div>`;body.appendChild(box);box.querySelector('#swrlzTimeEnable').addEventListener('click',enableFromSettings);box.querySelector('#swrlzTimeDisable').addEventListener('click',disable);box.querySelector('#swrlzTimeRemind').addEventListener('change',e=>setReminder(Boolean(e.target.checked)));box.querySelector('#swrlzLocationSave').addEventListener('click',saveLocation);renderSettings()}
function renderSettings(){const box=document.querySelector('#swrlzTemporalSettings');if(!box)return;const p=loadProfile(),t=p.temporal,enabled=allowed(p),status=box.querySelector('#swrlzTimeStatus');status.textContent=enabled?`On · factual device clock/timezone are relayed to §wyrlz for its own interpretation.`:`Off · local clock/timezone are not relayed.`;box.querySelector('#swrlzTimeEnable').disabled=enabled;box.querySelector('#swrlzTimeDisable').disabled=!enabled;box.querySelector('#swrlzTimeRemind').checked=t.reminderPreference!=='never';box.querySelector('#swrlzProfileCity').value=p.profileLocation.city||'';box.querySelector('#swrlzProfileState').value=p.profileLocation.state||'';box.querySelector('#swrlzProfileCountry').value=p.profileLocation.country||''}
function bootUi(){injectSettings();const settings=document.querySelector('#settingsButton');if(settings&&!settings.__swrlzTemporalBound){settings.__swrlzTemporalBound=true;settings.addEventListener('click',()=>setTimeout(()=>{injectSettings();renderSettings()},0))}setTimeout(()=>openConsent(false),1200)}
window.fetch=function(input,init={}){if(!isStream(input,init))return priorFetch(input,init);const payload=parseBody(init);if(!payload)return priorFetch(input,init);return priorFetch(input,{...init,body:JSON.stringify(augment(payload))})};window.addEventListener('storage',e=>{if(e.key===PROFILE_KEY)renderSettings()});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootUi,{once:true});else bootUi();window.__swrlzUserTimeContext={version:3,profileKey:PROFILE_KEY,approvedTimeContext,augment,loadProfile,grant,decline,disable,openConsent,pendingReceipts,policy:'permission-first-factual-device-time-relay-lalm-interprets'};
})();