(()=>{"use strict";
if(window.__swrlzContextCameraInstalled)return;
window.__swrlzContextCameraInstalled=true;
const rawByRequest=new Map(),branchByRequest=new Map(),priorConsume=typeof window.consumeEvent==='function'?window.consumeEvent:null;if(!priorConsume)return;
function ridOf(event,context){return String(event?.identity?.requestId||context?.requestId||context?.message?.meta?.requestId||'')}
function ensureMeta(message){message.meta=message.meta||{};message.meta.contextCamera=message.meta.contextCamera||{};return message.meta.contextCamera}
function branchIdOf(context,rid){return String(context?.__swrlzGenerationBranchId||context?.message?.meta?.generationBranchId||`${rid}:branch-1`)}
function attachRelayReceipt(message,rid){try{const attach=window.__swrlzCanonicalContext?.attachReceipt;return typeof attach==='function'?Boolean(attach(rid,message,{consume:false})):false}catch(error){const camera=ensureMeta(message);camera.receiptAttachError=String(error?.message||error);return false}}
function addTrail(message,reason){try{message.meta=message.meta||{};message.meta.trail=Array.isArray(message.meta.trail)?message.meta.trail:[];const last=message.meta.trail.at(-1);message.meta.trail.push({seq:Number(last?.seq||0)+1,phase:'CONTEXT_CAMERA',reason,at:Date.now()});if(message.meta.trail.length>80)message.meta.trail.splice(0,message.meta.trail.length-80)}catch(_){ }}
function beginBranchIfNeeded(rid,context,message){const branchId=branchIdOf(context,rid),previous=branchByRequest.get(rid);if(previous!==branchId){branchByRequest.set(rid,branchId);rawByRequest.set(rid,'');const camera=ensureMeta(message);camera.generationBranchId=branchId;camera.rawBranchResetAt=Date.now();camera.rawBranchResetReason=previous?'recovery-branch-change':'initial-generation-branch'}return branchId}
window.consumeEvent=function(event,context){const message=context?.message,rid=ridOf(event,context);if(message&&rid){attachRelayReceipt(message,rid);const branchId=beginBranchIfNeeded(rid,context,message),camera=ensureMeta(message);if(event?.type==='RESET')rawByRequest.set(rid,'');if(event?.type==='DELTA'&&typeof event.text==='string')rawByRequest.set(rid,(rawByRequest.get(rid)||'')+event.text);camera.lastRawEventSeq=Number(event?.seq||camera.lastRawEventSeq||0);camera.captureMode='raw-winning-generation-branch';camera.activeGenerationBranchId=branchId;camera.interpretationOwner='lalm'}const result=priorConsume(event,context);if(message&&rid&&['COMPLETED','CANCELLED','FAILED'].includes(String(event?.type||''))){attachRelayReceipt(message,rid);const raw=rawByRequest.get(rid),camera=ensureMeta(message),branchId=branchIdOf(context,rid);if(typeof raw==='string'&&raw.length){message.meta.modelText=raw;camera.rawAssistantChars=raw.length}camera.winningGenerationBranchId=branchId;camera.displayAssistantChars=String(message.text||'').length;camera.canonicalDiffersFromDisplay=typeof raw==='string'?raw!==String(message.text||''):false;camera.canonicalModelTextSource='winning-generation-branch';camera.completedAt=Date.now();addTrail(message,`Context camera · relay=${camera.relayId||'unknown'} · history=${camera.historySource||'unknown'} · raw/display differ=${camera.canonicalDiffersFromDisplay?'yes':'no'} · interpretation=LALM.`);rawByRequest.delete(rid);branchByRequest.delete(rid);try{window.__swrlzCanonicalContext?.releaseReceipt?.(rid)}catch(_){ }try{typeof saveState==='function'&&saveState()}catch(_){ }}return result};
window.__swrlzContextCamera={version:2,rawByRequest,branchByRequest,policy:'transport-and-display-diagnostics-only-lalm-interprets'};
})();