(()=>{"use strict";
if(window.__swrlzImmediateActivityInstalled)return;
window.__swrlzImmediateActivityInstalled=true;
const priorFetch=window.fetch.bind(window);
const baseRenderMessage=typeof renderMessage==='function'?renderMessage:null;
function streamUrl(input){try{return typeof input==='string'?input:(input?.url||'')}catch(_){return ''}}
function isStream(input,init){const method=String(init?.method||input?.method||'GET').toUpperCase();return method==='POST'&&/(?:[?&]action=stream(?:&|$)|\/stream(?:[?#]|$))/i.test(streamUrl(input))}
function parseBody(init){if(typeof init?.body!=='string')return null;try{return JSON.parse(init.body)}catch(_){return null}}
function isLive(message){return message?.role==='assistant'&&(message?.state==='streaming'||message?.state==='cancelling')}
function phaseText(message){try{return typeof phaseLabel==='function'?phaseLabel(message?.meta?.phase||'ANALYZING_REQUEST'):'Analyzing request'}catch(_){return 'Analyzing request'}}
function findMessage(id){try{const key=String(id||'');if(!key)return null;for(const thread of state?.threads||[]){const message=thread?.messages?.find?.(m=>String(m?.id||'')===key);if(message)return message}return null}catch(_){return null}}
function ensureModel(message){try{if(!message||message?.role!=='assistant')return false;message.meta=message.meta||{};message.meta.trail=Array.isArray(message.meta.trail)?message.meta.trail:[];if(isLive(message)&&!message.meta.trail.length)message.meta.trail.push({seq:0,phase:message.meta.phase||'ANALYZING_REQUEST',reason:'Preparing the canonical request locally.',at:Date.now()});if(typeof message.meta.activityExpanded!=='boolean')message.meta.activityExpanded=false;return true}catch(_){return false}}
function activitySteps(message){return (message?.meta?.trail||[]).slice(-12)}
function hideLegacyTraces(body){body?.querySelectorAll?.(':scope > details.trace').forEach(node=>{node.hidden=true;node.setAttribute('aria-hidden','true');node.dataset.swrlzActivityLegacy='hidden'})}
function syncPanel(article,message){try{if(!article||!ensureModel(message))return article;const body=article.querySelector('.message-body');if(!body)return article;const hasActivity=isLive(message)||Boolean(message.meta.trail?.length);hideLegacyTraces(body);let panel=body.querySelector(':scope > .swrlz-activity-panel');if(!hasActivity){panel?.remove();return article}if(!panel){panel=document.createElement('section');panel.className='trace swrlz-activity-panel';const button=document.createElement('button');button.type='button';button.className='swrlz-activity-toggle';const list=document.createElement('div');list.className='trace-list swrlz-activity-list';panel.append(button,list);const bubble=body.querySelector(':scope > .bubble'),actions=body.querySelector(':scope > .message-actions');if(bubble)body.insertBefore(panel,bubble);else if(actions)body.insertBefore(panel,actions);else body.append(panel)}const expanded=Boolean(message.meta.activityExpanded),button=panel.querySelector('.swrlz-activity-toggle'),list=panel.querySelector('.swrlz-activity-list');panel.dataset.expanded=expanded?'true':'false';if(button){button.setAttribute('aria-expanded',expanded?'true':'false');button.textContent=`Activity log · ${phaseText(message)}`}if(list){list.hidden=!expanded;const recent=activitySteps(message),sig=recent.map(x=>`${x?.phase||''}\u0000${x?.reason||''}`).join('\u0001');if(list.dataset.activitySignature!==sig){list.dataset.activitySignature=sig;const frag=document.createDocumentFragment();for(const step of recent){const item=document.createElement('div');item.className='trace-item';const label=typeof phaseLabel==='function'?phaseLabel(step?.phase):String(step?.phase||'Activity');item.textContent=step?.reason?`${label} — ${step.reason}`:label;frag.append(item)}list.replaceChildren(frag)}}return article}catch(_){return article}}
function articleMessage(article){return findMessage(article?.dataset?.messageId)}
function syncArticle(article){if(!article?.matches?.('.message.assistant'))return;const message=articleMessage(article);if(message)syncPanel(article,message)}
function syncAll(root=document){try{if(root.matches?.('.message.assistant'))syncArticle(root);root.querySelectorAll?.('.message.assistant').forEach(syncArticle)}catch(_){}}
function setFromUser(panel,next){try{const article=panel?.closest?.('.message.assistant'),message=articleMessage(article);if(!message)return;ensureModel(message);message.meta.activityExpanded=Boolean(next);syncPanel(article,message);saveState()}catch(_){}}
if(baseRenderMessage){renderMessage=function(message){ensureModel(message);return syncPanel(baseRenderMessage(message),message)}}
document.addEventListener('click',event=>{const button=event.target?.closest?.('.swrlz-activity-toggle');if(!button)return;const panel=button.closest('.swrlz-activity-panel');if(!panel)return;const article=panel.closest('.message.assistant'),message=articleMessage(article);if(!message)return;setFromUser(panel,!Boolean(message.meta?.activityExpanded))},true);
const observer=new MutationObserver(records=>{queueMicrotask(()=>{for(const record of records){for(const node of record.addedNodes||[]){if(node.nodeType===1)syncAll(node)}}})});
function bootObserver(){const stack=document.querySelector('#messageStack');if(stack&&!stack.dataset.swrlzActivityOwner){stack.dataset.swrlzActivityOwner='user-owned-v4';observer.observe(stack,{childList:true,subtree:true});syncAll(stack)}}
function seed(message){try{if(!ensureModel(message))return false;if(isLive(message)&&!message.meta.phase)message.meta.phase='ANALYZING_REQUEST';try{saveState()}catch(_){};if(typeof render==='function')render(false);else if(typeof scheduleRender==='function')scheduleRender(false);return true}catch(_){return false}}
function latestStreaming(){try{if(typeof currentThread!=='function')return null;const thread=currentThread();if(!thread?.messages)return null;return[...thread.messages].reverse().find(m=>isLive(m))||null}catch(_){return null}}
function mark(payload){try{const rid=String(payload?.requestId||'');if(!rid||typeof currentThread!=='function')return;const thread=currentThread();if(!thread?.messages)return;const message=[...thread.messages].reverse().find(m=>m?.role==='assistant'&&String(m?.meta?.requestId||'')===rid);seed(message)}catch(_){}}
document.addEventListener('submit',event=>{try{const form=event.target;if(!(form instanceof HTMLFormElement)||form.id!=='composer')return;queueMicrotask(()=>seed(latestStreaming()))}catch(_){}},true);
window.fetch=function(input,init={}){if(isStream(input,init)){const payload=parseBody(init);if(payload)mark(payload);else queueMicrotask(()=>seed(latestStreaming()))}return priorFetch(input,init)};
const style=document.createElement('style');style.textContent=`details.trace[data-swrlz-activity-legacy="hidden"]{display:none!important}.swrlz-activity-panel{overflow:hidden}.swrlz-activity-toggle{display:flex;align-items:center;gap:8px;width:100%;min-height:38px;padding:0 12px;border:0;color:var(--muted);background:transparent;cursor:pointer;text-align:left;font:inherit;font-size:11px}.swrlz-activity-toggle::before{content:"";width:6px;height:6px;flex:0 0 auto;border-radius:50%;color:var(--cyan);background:currentColor;box-shadow:0 0 9px currentColor}.swrlz-activity-panel[data-expanded="true"] .swrlz-activity-toggle{color:var(--secondary)}.swrlz-activity-list[hidden]{display:none!important}`;document.head.append(style);
window.__swrlzActivityController={version:4,policy:'activityExpanded-user-write-only',ensureModel,syncPanel,syncArticle,syncAll,findMessage};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootObserver,{once:true});else bootObserver();
})();
