(()=>{"use strict";
if(window.__swrlzTerminalTranscriptRecoveryInstalled)return;
window.__swrlzTerminalTranscriptRecoveryInstalled=true;
const CONTRACT='terminal-transcript-recovery-v1',inflight=new Map(),cooldown=new Map();
function dbg(message,data={}){try{window.__swrlzClientDebug?.('terminal-recovery',message,{contract:CONTRACT,...data})}catch(_){}}
function auth(){try{return typeof authHeaders==='function'?authHeaders():{'Content-Type':'application/json'}}catch(_){return {'Content-Type':'application/json'}}}
function transcriptUrl(){try{return String(API||'/api/chat').replace(/\/$/,'')+'/transcript'}catch(_){return '/api/chat/transcript'}}
function candidates(){try{return (state?.threads||[]).flatMap(t=>(t?.messages||[]).map(m=>({thread:t,message:m}))).filter(({message:m})=>m?.role==='assistant'&&!String(m?.text||'')&&String(m?.meta?.requestId||'')&&(['failed','complete'].includes(String(m?.state||''))||/ERROR|COMPLETE/i.test(String(m?.meta?.phase||''))||/without a terminal event|No committed assistant text/i.test(String(m?.meta?.error||''))))}catch(_){return[]}}
function saveRender(){try{typeof saveState==='function'&&saveState()}catch(_){ }try{typeof scheduleRender==='function'&&scheduleRender(false)}catch(_){ }}
async function recover(thread,message,reason){const rid=String(message?.meta?.requestId||'');if(!rid||inflight.has(rid))return;const last=Number(cooldown.get(rid)||0);if(Date.now()-last<900)return;cooldown.set(rid,Date.now());const task=(async()=>{dbg('canonical-transcript-requested',{requestId:rid,messageId:String(message.id||''),reason});try{const response=await fetch(transcriptUrl(),{method:'POST',headers:auth(),body:JSON.stringify({requestId:rid,reason:`terminal-recovery:${reason}`})});if(!response.ok)throw new Error(`Transcript HTTP ${response.status}`);const snapshot=await response.json();const text=String(snapshot?.text||'');if(snapshot?.contract!=='generation-transcript-v1'||String(snapshot?.requestId||'')!==rid)throw new Error('Transcript identity/contract mismatch');if(!snapshot?.terminal||String(snapshot?.terminalType||'COMPLETED')!=='COMPLETED'||!text){dbg('canonical-transcript-not-ready',{requestId:rid,terminal:!!snapshot?.terminal,terminalType:String(snapshot?.terminalType||''),chars:text.length});return}const current=String(message.text||'');if(current&&current.length>=text.length)return;message.text=text;message.state='complete';message.meta=message.meta||{};message.meta.phase='COMPLETE';message.meta.rawPhase='COMPLETE';message.meta.error='';message.meta.workLabel='Response complete';message.meta.terminalType='COMPLETED';message.meta.transcriptSync={...(message.meta.transcriptSync||{}),contract:'generation-transcript-v1',state:'terminal-synced',strict:true,verified:true,recovered:true,recoveryContract:CONTRACT,textRevision:Number(snapshot?.textRevision||0),lastSyncAt:Date.now()};message.meta.terminalIntegrity={...(message.meta.terminalIntegrity||{}),contract:'terminal-response-integrity-v2',version:2,terminalConfirmed:true,terminalSnapshot:{text,chars:text.length,requestId:rid,completedAt:Date.now(),source:'canonical-transcript-recovery'},lastReconciliation:'canonical-transcript-recovered',lastReconciliationAt:Date.now()};if(thread)thread.updatedAt=Date.now();try{if(typeof active!=='undefined'&&active?.requestId===rid){const ctl=active.controller;active=null;try{ctl?.abort?.('canonical-transcript-recovered')}catch(_){ }}}catch(_){ }saveRender();dbg('canonical-transcript-recovered',{requestId:rid,messageId:String(message.id||''),chars:text.length})}catch(error){dbg('canonical-transcript-recovery-failed',{requestId:rid,error:String(error?.message||error)})}})().finally(()=>inflight.delete(rid));inflight.set(rid,task);return task}
function scan(reason='scan'){for(const {thread,message} of candidates())recover(thread,message,reason)}
let queued=false;function queue(reason){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;scan(reason)})}
const observer=new MutationObserver(()=>queue('dom-mutation'));
function boot(){observer.observe(document.body,{subtree:true,childList:true,characterData:true});scan('boot');for(const delay of [250,700,1500,3200])setTimeout(()=>scan(`boot-${delay}`),delay)}
window.addEventListener('pageshow',()=>scan('pageshow'));window.addEventListener('online',()=>scan('online'));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')scan('foreground')});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.__swrlzTerminalTranscriptRecovery={version:1,contract:CONTRACT,scan,policy:'canonical-nonempty-terminal-transcript-repairs-empty-failed-or-complete-mask-state-without-changing-lalm-semantics'};
})();
