(()=>{
'use strict';
const STATE_KEY='swrlz.vercel.chat.v1', PROFILE_KEY='swrlz.user.profile.v1', RUN_KEY='swrlz.workflow.run.v1';
let user=null, config=null, lastSync='', syncTimer=0;
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=m=>{const e=$('.toast')||$('#toast');if(e){e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}};
async function json(url,init={}){const r=await fetch(url,{credentials:'include',cache:'no-store',...init});let v={};try{v=await r.json()}catch{}if(!r.ok)throw Error(v.detail||v.code||`HTTP ${r.status}`);return v}
function state(){try{return JSON.parse(localStorage.getItem(STATE_KEY)||'null')}catch{return null}}
function profile(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'{}')}catch{return {}}}
function writeState(v){const s=JSON.stringify(v);localStorage.setItem(STATE_KEY,s);window.dispatchEvent(new StorageEvent('storage',{key:STATE_KEY,newValue:s}))}
function workflowReceipt(){try{return JSON.parse(localStorage.getItem(RUN_KEY)||'null')}catch{return null}}
function inject(body){if(!user)return body;const receipt=workflowReceipt(),sameRun=receipt&&receipt.requestId&&receipt.requestId===body.requestId;return {...body,userId:user.userId,profileId:user.userId,profile:profile(),inputProvenance:body.inputProvenance||{modality:'text'},...(sameRun&&receipt.runId?{workflowRunId:receipt.runId}:{})}}
const realFetch=window.fetch.bind(window);
window.fetch=async(input,init={})=>{let response;try{const u=new URL(typeof input==='string'?input:input?.url||'',location.href);if(u.origin===location.origin&&u.pathname==='/api/chat'&&String(init.method||'GET').toUpperCase()==='POST'&&typeof init.body==='string')init={...init,credentials:'include',body:JSON.stringify(inject(JSON.parse(init.body)))};}catch{}response=await realFetch(input,init);try{const runId=response.headers.get('X-SWRLZ-Workflow-Run-Id');if(runId){const requestId=response.headers.get('X-SWRLZ-Request-Id')||'';localStorage.setItem(RUN_KEY,JSON.stringify({runId,requestId,updatedAt:Date.now()}))}}catch{}return response};
function styles(){if($('#swrlz-account-style'))return;const s=document.createElement('style');s.id='swrlz-account-style';s.textContent=`
.swrlz-account-btn{border:1px solid rgba(56,232,255,.25);background:rgba(8,16,29,.8);color:#dff7ff;border-radius:999px;padding:7px 11px;font:700 11px system-ui;cursor:pointer}.swrlz-account-modal{position:fixed;inset:0;z-index:9999;display:grid;place-items:center;padding:18px;background:rgba(0,0,0,.62);backdrop-filter:blur(12px)}.swrlz-account-panel{width:min(580px,100%);max-height:90dvh;overflow:auto;background:#08111f;border:1px solid rgba(56,232,255,.25);border-radius:22px;padding:20px;box-shadow:0 30px 100px #000}.swrlz-account-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:16px 0}.swrlz-account-grid label{font-size:11px;color:#9eb7cc}.swrlz-account-grid input,.swrlz-account-grid select{width:100%;margin-top:5px;padding:10px;border:1px solid #294767;border-radius:10px;background:#06101d;color:#fff}.swrlz-account-actions{display:flex;gap:8px;flex-wrap:wrap}.swrlz-account-actions button{padding:10px 13px;border:1px solid #315b80;border-radius:10px;background:#10243a;color:#fff;font-weight:800;cursor:pointer}.swrlz-google{min-height:44px;margin:16px 0}.swrlz-code-copy{position:absolute;right:8px;top:8px;padding:5px 8px;border:1px solid rgba(56,232,255,.25);border-radius:8px;background:rgba(3,9,18,.9);color:#dff7ff;font:700 10px system-ui;cursor:pointer}.message-body pre{position:relative}.swrlz-follow{position:fixed;right:18px;bottom:92px;z-index:50;display:none;padding:8px 12px;border:1px solid rgba(56,232,255,.3);border-radius:999px;background:#07101d;color:#dff7ff;font:800 11px system-ui}.swrlz-follow.show{display:block}@media(max-width:700px){.swrlz-account-grid{grid-template-columns:1fr}}
`;document.head.append(s)}
function paint(){styles();let h=$('.topbar-right');if(!h||$('#swrlzAccountButton'))return;const b=document.createElement('button');b.id='swrlzAccountButton';b.className='swrlz-account-btn';b.textContent=user?`◉ ${user.name||user.email}`:'◎ SIGN IN';b.onclick=openAccount;h.prepend(b)}
async function boot(){try{config=await json('/api/chat/auth/config');user=(await json('/api/chat/auth/me')).user||null;paint();if(user)await restore()}catch(e){console.warn('[§wyrlz account]',e)}}
async function restore(){const j=await json('/api/chat/data');const threads=j.data?.threads||[];writeState({version:1,currentId:threads[0]?.id||null,threads});localStorage.setItem(PROFILE_KEY,JSON.stringify(j.data?.profile||{}));lastSync=JSON.stringify({threads,profile:j.data?.profile||{}});toast(`Restored ${threads.length} server conversation${threads.length===1?'':'s'}`)}
async function persist(){if(!user)return;const st=state();if(!st)return;const p=profile();const sig=JSON.stringify({threads:st.threads||[],profile:p});if(sig===lastSync)return;try{await json('/api/chat/data',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({threads:(st.threads||[]).slice(0,80),profile:p,settings:{defaultScale:p.defaultScale||'NORMAL'},organization:{id:'personal',name:p.organizationName||'Personal',role:p.organizationRole||'Owner'}})});lastSync=sig}catch(e){console.warn('[§wyrlz sync]',e)}}
function openAccount(){styles();document.querySelector('.swrlz-account-modal')?.remove();const m=document.createElement('div');m.className='swrlz-account-modal';const p=document.createElement('div');p.className='swrlz-account-panel';if(!user){p.innerHTML='<h3>Sign in to §wyrlz</h3><p>Your Google identity becomes the account boundary for server chat history, profile context, settings, and resumable generation.</p><div class="swrlz-google" id="swrlzGoogle"></div><div class="swrlz-account-actions"><button data-close>CLOSE</button></div>';m.append(p);document.body.append(m);p.querySelector('[data-close]').onclick=()=>m.remove();loadGoogle();return}const pr=profile();p.innerHTML=`<h3>${esc(user.name||'§wyrlz user')}</h3><p>${esc(user.email||'')} · Google verified · ${config?.persistentStore?'persistent server storage':'local fallback storage'}</p><div class="swrlz-account-grid"><label>Display name<input data-k="displayName" value="${esc(pr.displayName||user.name||'')}"></label><label>Timezone<input data-k="timezone" value="${esc(pr.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone)}"></label><label>Response style<select data-k="responseStyle"><option>Adaptive</option><option>Technical</option><option>Conversational</option><option>Concise</option></select></label><label>Default scale<select data-k="defaultScale"><option>SHORT</option><option>NORMAL</option><option>EXPANDED</option><option>EXTENDED</option><option>MASSIVE</option></select></label><label>Organization<input data-k="organizationName" value="${esc(pr.organizationName||'Personal')}"></label><label>Role<input data-k="organizationRole" value="${esc(pr.organizationRole||'Owner')}"></label></div><div class="swrlz-account-actions"><button data-save>SAVE PROFILE</button><button data-sync>SYNC NOW</button><button data-logout>SIGN OUT</button><button data-close>CLOSE</button></div>`;m.append(p);document.body.append(m);p.querySelector('[data-k="responseStyle"]').value=pr.responseStyle||'Adaptive';p.querySelector('[data-k="defaultScale"]').value=pr.defaultScale||'NORMAL';p.querySelector('[data-save]').onclick=async()=>{const n={...pr};p.querySelectorAll('[data-k]').forEach(x=>n[x.dataset.k]=x.value);localStorage.setItem(PROFILE_KEY,JSON.stringify(n));await persist();toast('Profile saved')};p.querySelector('[data-sync]').onclick=restore;p.querySelector('[data-logout]').onclick=logout;p.querySelector('[data-close]').onclick=()=>m.remove()}
async function loadGoogle(){if(window.google?.accounts?.id){renderGoogle();return}if(!config?.googleClientId){$('#swrlzGoogle').textContent='Google client ID is not configured on the server.';return}const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.defer=true;s.onload=renderGoogle;s.onerror=()=>$('#swrlzGoogle').textContent='Google Identity Services failed to load.';document.head.append(s)}
function renderGoogle(){const box=$('#swrlzGoogle');if(!box||!window.google?.accounts?.id)return;box.replaceChildren();google.accounts.id.initialize({client_id:config.googleClientId,callback:async r=>{try{const j=await json('/api/chat/auth/google',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({credential:r.credential})});user=j.user;paint();await restore();document.querySelector('.swrlz-account-modal')?.remove();toast('Signed in — server account restored')}catch(e){toast('Sign-in failed: '+e.message)}}});google.accounts.id.renderButton(box,{theme:'outline',size:'large',shape:'pill',text:'signin_with',width:320})}
async function logout(){try{await json('/api/chat/auth/logout',{method:'POST'})}catch{}user=null;localStorage.removeItem(STATE_KEY);localStorage.removeItem(PROFILE_KEY);localStorage.removeItem(RUN_KEY);location.reload()}
function codeButtons(){document.querySelectorAll('.message-body pre').forEach(pre=>{if(pre.dataset.swrlzCopy)return;pre.dataset.swrlzCopy='1';const b=document.createElement('button');b.className='swrlz-code-copy';b.textContent='COPY';b.onclick=async e=>{e.stopPropagation();try{await navigator.clipboard.writeText(pre.querySelector('code')?.textContent||pre.textContent||'');b.textContent='COPIED';setTimeout(()=>b.textContent='COPY',1200)}catch{toast('Clipboard access unavailable')}};pre.append(b)})}
function scrollControl(){const box=$('.messages');if(!box||box.dataset.swrlzScroll)return;box.dataset.swrlzScroll='1';let paused=false,lastTop=box.scrollTop;const follow=document.createElement('button');follow.className='swrlz-follow';follow.textContent='FOLLOW LIVE';document.body.append(follow);box.addEventListener('scroll',()=>{paused=box.scrollHeight-box.clientHeight-box.scrollTop>96;lastTop=box.scrollTop;if(!paused)follow.classList.remove('show')});follow.onclick=()=>{paused=false;box.scrollTo({top:box.scrollHeight,behavior:'smooth'});follow.classList.remove('show')};new MutationObserver(()=>{codeButtons();if(paused){requestAnimationFrame(()=>{if(Math.abs(box.scrollTop-lastTop)>8)box.scrollTop=lastTop;follow.classList.add('show')})}else if(box.scrollHeight-box.clientHeight-box.scrollTop<180){requestAnimationFrame(()=>box.scrollTop=box.scrollHeight)}}).observe(box,{childList:true,subtree:true,characterData:true});codeButtons()}
function watch(){let previous='';setInterval(()=>{const s=localStorage.getItem(STATE_KEY)||'';if(s&&s!==previous){previous=s;clearTimeout(syncTimer);syncTimer=setTimeout(persist,1200)}},1500)}
styles();paint();scrollControl();watch();boot();
})();
