(()=>{"use strict";
if(window.__swrlzRuntimeLoaderV3)return;
const REV=(()=>{try{return new URL(document.currentScript?.src||'',location.href).searchParams.get('v')||'95'}catch(_){return'95'}})(),ROOT='/live/assets/',LKG_KEY='swrlz.chat.lkg.v1';
const diagnostics={contractId:'swrlz_chat_cooperative_boot_v3',revision:REV,startedAt:performance.now(),critical:[],functional:[],decorative:[],styleErrors:[],scriptErrors:[],timeouts:[],mainReady:false,functionalReady:false,decorativeReady:false,themeSettled:false,stage:'loader-start',mode:'candidate'};window.__swrlzRuntimeLoaderV3=diagnostics;
const pre=(m,d,t='boot')=>{try{window.__swrlzPreboot?.send(m,d,t)}catch(_){ }};const dbg=(t,m,d)=>{try{window.__swrlzDebug?.log(t,m,d)}catch(_){ }pre(m,d,t)};
const stage=(name,data)=>{diagnostics.stage=name;diagnostics.stageAt=performance.now();try{document.documentElement.dataset.swrlzBootStage=name}catch(_){ }dbg('boot','boot-stage',{stage:name,revision:REV,...(data||{})})};
const readLkg=()=>{try{return JSON.parse(localStorage.getItem(LKG_KEY)||'null')}catch(_){return null}};const markMode=(mode,detail={})=>{diagnostics.mode=mode;document.documentElement.dataset.swrlzRuntimeMode=mode;dbg('boot','runtime-mode',{mode,revision:REV,lkg:readLkg(),...detail})};
const failOpen=(reason,data)=>{diagnostics.failOpenReason=reason;diagnostics.failOpenAt=performance.now();document.documentElement.classList.remove('swrlz-visual-booting');document.documentElement.classList.add('swrlz-main-chat-ready','swrlz-visual-ready');markMode('emergency-base',{reason});stage('fail-open',{reason,...(data||{})})};
const promote=()=>{const value={revision:REV,verifiedAt:new Date().toISOString(),contract:diagnostics.contractId};try{localStorage.setItem(LKG_KEY,JSON.stringify(value))}catch(_){ }diagnostics.lastKnownGood=value;markMode('verified',{promoted:value})};
window.addEventListener('error',e=>dbg('error','loader-window-error',{stage:diagnostics.stage,message:e.message,source:e.filename,line:e.lineno,column:e.colno}),true);window.addEventListener('unhandledrejection',e=>dbg('error','loader-unhandled-rejection',{stage:diagnostics.stage,reason:String(e.reason?.message||e.reason||'unknown')}));
const bootWatchdog=setTimeout(()=>{if(!diagnostics.functionalReady)failOpen('boot-watchdog',{stage:diagnostics.stage,critical:[...diagnostics.critical],functional:[...diagnostics.functional],scriptErrors:[...diagnostics.scriptErrors],styleErrors:[...diagnostics.styleErrors],timeouts:[...diagnostics.timeouts]})},15000);markMode('candidate',{previousLkg:readLkg()});stage('loader-start');
const ua=navigator.userAgent||'',isAndroid=/Android/i.test(ua),isEdgeAndroid=isAndroid&&(/\bEdgA\//i.test(ua)||/\bEdg\//i.test(ua));if(isAndroid)document.documentElement.classList.add('swrlz-android-device');if(isEdgeAndroid)document.documentElement.classList.add('swrlz-edge-android');
const yieldBrowser=()=>new Promise(resolve=>{if('requestIdleCallback'in window)requestIdleCallback(()=>resolve(),{timeout:80});else setTimeout(resolve,16)});
const visualViewportWidth=()=>{const vv=window.visualViewport;return Math.max(1,Math.round(vv?.width||document.documentElement.clientWidth||innerWidth||1))};
const syncViewport=()=>{if(!isAndroid)return;const vv=visualViewport,visualH=Math.max(1,Math.round(vv?.height||innerHeight||document.documentElement.clientHeight||1)),layoutH=Math.max(visualH,Math.round(document.documentElement.clientHeight||innerHeight||visualH)),w=visualViewportWidth(),top=Math.max(0,Math.round(vv?.offsetTop||0)),left=Math.max(0,Math.round(vv?.offsetLeft||0)),focused=document.activeElement,editable=!!focused&&(focused.matches?.('textarea,input,[contenteditable="true"]')||focused.isContentEditable),edgeImeCompensated=isEdgeAndroid&&editable&&(layoutH-visualH>64),h=edgeImeCompensated?layoutH:visualH,imeOpen=editable&&(layoutH-visualH>80||Math.round(screen?.height||0)-visualH>220);document.documentElement.classList.toggle('swrlz-ime-open',!!imeOpen);document.documentElement.classList.toggle('swrlz-edge-ime-layout',!!edgeImeCompensated);document.documentElement.style.setProperty('--swrlz-vvh',`${h}px`);document.documentElement.style.setProperty('--swrlz-vvw',`${w}px`);document.documentElement.style.setProperty('--swrlz-vv-top',`${top}px`);document.documentElement.style.setProperty('--swrlz-vv-left',`${left}px`);diagnostics.viewport={height:h,width:w,top,left,imeOpen,layoutHeight:layoutH,widthAuthority:vv?.width?'visualViewport':'layoutViewport'}};syncViewport();visualViewport?.addEventListener('resize',syncViewport,{passive:true});visualViewport?.addEventListener('scroll',syncViewport,{passive:true});addEventListener('resize',syncViewport,{passive:true});
const styles=['chat_boot_guard.css','chat_enhancements.css','chat_user_settings_v2.css','themes/ice-dragon/ice-dragon-theme.css','themes/ice-dragon/ice-dragon-art-v2.css','themes/ice-dragon/ice-dragon-shell-v1.css','themes/ice-dragon/ice-dragon-brand-v1.css','themes/ice-dragon/ice-dragon-polish-v2.css','themes/ice-dragon/ice-dragon-response-layout-v1.css','chat_mobile_viewport_fix.css','chat_code_artifacts.css'];
const critical=['chat_debug_log_v1.js','chat_drawer_layer_v1.js','chat_transport_boundary_v1.js','chat_frontend_boot_v2.js','chat_boot_guard.js','chat_version.js','chat_boot_ready.js'];
const functional=['chat_admin_session.js','chat_enhancements.js','chat_google_server_config.js','themes/ice-dragon/ice-dragon-theme-v3.2.js','chat_account_identity_v1.js','chat_user_settings_v2.js','chat_stream_focus.js','chat_stream_incremental.js','chat_committed_contract_bridge.js','chat_committed_output_v3.js','chat_activity_immediate.js','chat_user_time_context.js','chat_context_canonical.js','chat_background_resume_v2.js','chat_response_presence.js','chat_terminal_integrity.js','chat_context_capacity.js','chat_context_camera.js','chat_response_polish.js','chat_turn_integrity_v1.js','chat_response_layout_v1.js','chat_thread_brand_v1.js','chat_theme_settings_v1.js','chat_scroll_gesture_v1.js','chat_code_artifacts.js'],themeSettlement='themes/ice-dragon/ice-dragon-art-loader-v17.js',wallpaper='themes/ice-dragon/ice-dragon-wallpaper-v22.js',src=p=>`${ROOT}${p}?v=${REV}`;
function establishInitialTheme(){let saved='';try{saved=localStorage.getItem('swrlz.chat.theme')||''}catch(_){ }const initial=saved==='default'?'default':'ice-dragon';if(initial==='ice-dragon')document.body.dataset.swrlzTheme='ice-dragon';else delete document.body.dataset.swrlzTheme;diagnostics.initialTheme=initial;stage('theme-established',{theme:initial})}
function loadStyle(path){return new Promise(resolve=>{const link=document.createElement('link');link.rel='stylesheet';link.href=src(path);link.dataset.swrlzRuntimeStyle=path;link.onload=()=>{dbg('asset','style-load',{path});resolve()};link.onerror=()=>{diagnostics.styleErrors.push(path);dbg('error','style-error',{path});resolve()};document.head.appendChild(link)})}
function loadOne(path,bucket,timeoutMs=5000){return new Promise(resolve=>{let settled=false;stage(`script:${path}:start`);const done=kind=>{if(settled)return;settled=true;clearTimeout(timer);if(kind==='load')bucket?.push(path);else(kind==='error'?diagnostics.scriptErrors:diagnostics.timeouts).push(path);dbg(kind==='load'?'asset':'error',`script-${kind}`,{path,stage:diagnostics.stage});stage(`script:${path}:${kind}`);resolve()};const script=document.createElement('script');script.src=src(path);script.async=false;script.dataset.swrlzRuntimeScript=path;script.onload=()=>done('load');script.onerror=()=>done('error');const timer=setTimeout(()=>done('timeout'),timeoutMs);document.body.appendChild(script)})}
async function loadSerial(paths,bucket,{settle=0,yieldEach=false}={}){if(settle){stage('functional-settle',{ms:settle});await new Promise(r=>setTimeout(r,settle))}for(const path of paths){await loadOne(path,bucket);if(yieldEach)await yieldBrowser()}}
async function boot(){stage('boot-enter');establishInitialTheme();document.documentElement.classList.add('swrlz-visual-booting');const styleReady=Promise.all(styles.map(loadStyle));stage('critical-start',{count:critical.length});await loadSerial(critical,diagnostics.critical,{yieldEach:true});diagnostics.mainReady=true;document.documentElement.classList.add('swrlz-main-chat-ready');stage('critical-complete',{loaded:diagnostics.critical.length});await yieldBrowser();const functionalReady=loadSerial(functional,diagnostics.functional,{settle:1600,yieldEach:true});stage('functional-start',{count:functional.length});await Promise.all([functionalReady,styleReady]);diagnostics.functionalReady=true;diagnostics.functionalReadyAt=performance.now();clearTimeout(bootWatchdog);document.documentElement.classList.add('swrlz-chat-functional-ready');stage('functional-complete',{loaded:diagnostics.functional.length,errors:diagnostics.scriptErrors,timeouts:diagnostics.timeouts});promote();await yieldBrowser();stage('decorative-start');await loadOne(wallpaper,diagnostics.decorative,5000);await yieldBrowser();await loadOne(themeSettlement,diagnostics.decorative,5000);diagnostics.themeSettled=true;document.documentElement.classList.add('swrlz-theme-settled');document.documentElement.classList.remove('swrlz-visual-booting');document.documentElement.classList.add('swrlz-visual-ready','swrlz-chat-decorative-ready');diagnostics.decorativeReady=true;stage('visual-ready',{revision:REV});}
boot().catch(error=>{diagnostics.fatal=String(error?.message||error);failOpen('boot-fatal',{message:diagnostics.fatal,stack:error?.stack});console.error('[§wyrlz cooperative chat boot]',error)});})();