(()=>{"use strict";
if(window.__swrlzCanonicalTerminalReconcileV1)return;
const CONTRACT="canonical-terminal-reconcile-v1",ENDPOINT="/api/chat_turn_status";
const ctl={contract:CONTRACT,checks:0,adopted:0,lastError:"",active:new Set()};
window.__swrlzCanonicalTerminalReconcileV1=ctl;
const terminalState=s=>["complete","failed","cancelled"].includes(String(s||"").toLowerCase());
const requestIdOf=m=>String(m?.meta?.requestId||"");
const dbg=(message,data={})=>{try{window.__swrlzClientDebug?.("canonical-terminal",message,{contract:CONTRACT,...data})}catch(_){}};
function messages(){try{return (state?.threads||[]).flatMap(t=>(t?.messages||[]).map(m=>({thread:t,message:m})))}catch(_){return []}}
function candidate(){for(const item of messages()){const m=item.message;if(m?.role!=="assistant"||terminalState(m.state)||!requestIdOf(m))continue;const continuity=String(m.meta?.networkContinuity?.state||"");const reconnect=(m.meta?.trail||[]).some(x=>String(x?.phase||"").toUpperCase()==="RECONNECTING");if(reconnect||["waiting-network","reconnecting","foreground-resume-requested","shared-transcript-handoff"].includes(continuity))return item}return null}
function traceTerminal(m,value){m.meta=m.meta||{};m.meta.trail=Array.isArray(m.meta.trail)?m.meta.trail:[];const at=Number(value.completedAt||value.updatedAt||Date.now());const phase=value.terminalType==="COMPLETED"?"COMPLETE":value.terminalType==="CANCELLED"?"CANCELLED":"ERROR";const reason=value.terminalType==="COMPLETED"?"Canonical Redis confirms the response is complete.":value.terminalReason||`Canonical Redis confirms ${value.terminalType.toLowerCase()}.`;const last=m.meta.trail.at(-1);if(last?.phase!==phase||last?.reason!==reason)m.meta.trail.push({seq:Number(last?.seq||0)+1,phase,reason,at});if(m.meta.trail.length>30)m.meta.trail=m.meta.trail.slice(-30);m.meta.phase=phase;m.meta.rawPhase=phase;m.meta.workLabel=value.terminalType==="COMPLETED"?"✅ Response complete":value.terminalType==="CANCELLED"?"Request cancelled":"Request failed";m.meta.totalLatencyMs??=Math.max(0,at-Number(m.createdAt||at));m.meta.canonicalTerminal={contract:CONTRACT,authority:"canonical-redis",at,requestId:value.requestId};}
function apply(item,value){const m=item.message,rid=requestIdOf(m);if(!value?.terminal||String(value.requestId||"")!==rid)return false;if(String(value.assistantMessageId||"")&&String(value.assistantMessageId)!==String(m.id||"")){dbg("terminal-id-mismatch",{requestId:rid,localMessageId:String(m.id||""),canonicalMessageId:String(value.assistantMessageId||"")});return false}m.text=String(value.text||m.text||"");m.state=value.terminalType==="COMPLETED"?"complete":value.terminalType==="CANCELLED"?"cancelled":"failed";m.meta=m.meta||{};m.meta.error=value.terminalType==="FAILED"?String(value.terminalReason||m.meta.error||"The request failed."):"";if(m.meta.networkContinuity)m.meta.networkContinuity={...m.meta.networkContinuity,state:"complete",terminalAuthority:"canonical-redis",lastError:""};traceTerminal(m,value);try{if(typeof active!=="undefined"&&active?.requestId===rid){const controller=active.controller;active=null;setTimeout(()=>{try{controller?.abort?.()}catch(_){ }},0)}}catch(_){ }try{saveState()}catch(_){ }try{render(true)}catch(_){ }setTimeout(()=>{if(!terminalState(m.state)){m.state=value.terminalType==="COMPLETED"?"complete":value.terminalType==="CANCELLED"?"cancelled":"failed";traceTerminal(m,value);try{saveState();render(false)}catch(_){ }}},40);ctl.adopted++;dbg("canonical-terminal-adopted",{requestId:rid,terminalType:value.terminalType,chars:m.text.length,adopted:ctl.adopted});window.dispatchEvent(new CustomEvent("swrlz:canonical-turn-terminal",{detail:{requestId:rid,terminalType:value.terminalType}}));return true}
async function check(item){const rid=requestIdOf(item.message);if(!rid||ctl.active.has(rid))return;ctl.active.add(rid);ctl.checks++;try{const r=await fetch(`${ENDPOINT}?requestId=${encodeURIComponent(rid)}`,{credentials:"same-origin",cache:"no-store",headers:{Accept:"application/json"}});if(r.status===404)return;const value=await r.json().catch(()=>({}));if(!r.ok){ctl.lastError=String(value.detail||`HTTP ${r.status}`);return}apply(item,value)}catch(e){ctl.lastError=String(e?.message||e)}finally{ctl.active.delete(rid)}}
function tick(){const item=candidate();if(item)check(item)}
setInterval(tick,900);document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")setTimeout(tick,0)});window.addEventListener("online",()=>setTimeout(tick,0));
window.__swrlzCanonicalTerminalReconcile={version:1,contract:CONTRACT,check:tick};
})();
