(()=>{"use strict";
if(window.__swrlzImmediateActivityInstalled)return;
window.__swrlzImmediateActivityInstalled=true;
const priorFetch=window.fetch.bind(window);
function streamUrl(input){try{return typeof input==='string'?input:(input?.url||'')}catch(_){return ''}}
function isStream(input,init){const method=String(init?.method||input?.method||'GET').toUpperCase();return method==='POST'&&/(?:[?&]action=stream(?:&|$)|\/stream(?:[?#]|$))/i.test(streamUrl(input))}
function parseBody(init){if(typeof init?.body!=='string')return null;try{return JSON.parse(init.body)}catch(_){return null}}
function seed(message){try{if(!message)return false;message.meta=message.meta||{};message.meta.phase='ANALYZING_REQUEST';if(typeof message.meta.activityExpanded!=='boolean')message.meta.activityExpanded=false;message.meta.trail=Array.isArray(message.meta.trail)?message.meta.trail:[];if(!message.meta.trail.some(x=>x?.phase==='ANALYZING_REQUEST'&&x?.reason==='Preparing the canonical request locally.'))message.meta.trail.unshift({seq:0,phase:'ANALYZING_REQUEST',reason:'Preparing the canonical request locally.',at:Date.now()});if(typeof render==='function')render(false);else if(typeof scheduleRender==='function')scheduleRender(false);requestAnimationFrame(()=>{const node=document.querySelector(`[data-message-id="${CSS.escape(String(message.id||''))}"]`);const trace=node?.querySelector('.trace');if(trace){trace.open=Boolean(message.meta.activityExpanded);const summary=trace.querySelector('summary');if(summary&&!String(summary.textContent||'').startsWith('Activity log'))summary.textContent=`Activity log · ${summary.textContent||'Analyzing request'}`}});return true}catch(_){return false}}
function latestStreaming(){try{if(typeof currentThread!=='function')return null;const thread=currentThread();if(!thread?.messages)return null;return[...thread.messages].reverse().find(m=>m?.role==='assistant'&&(m?.state==='streaming'||m?.state==='cancelling'))||null}catch(_){return null}}
function messageForTrace(trace){try{const article=trace?.closest?.('[data-message-id]');const id=String(article?.dataset?.messageId||'');if(!id||typeof currentThread!=='function')return null;return currentThread()?.messages?.find?.(m=>String(m?.id||'')===id)||null}catch(_){return null}}
function persistIntendedTraceState(event){try{const summary=event.target?.closest?.('.trace > summary');if(!summary)return;const trace=summary.parentElement,message=messageForTrace(trace);if(!message)return;message.meta=message.meta||{};message.meta.activityExpanded=!trace.open;if(typeof saveState==='function')saveState()}catch(_){}}
function persistKeyboardTraceState(event){if(event.key!=='Enter'&&event.key!==' ')return;persistIntendedTraceState(event)}
function mark(payload){try{const rid=String(payload?.requestId||'');if(!rid||typeof currentThread!=='function')return;const thread=currentThread();if(!thread?.messages)return;const message=[...thread.messages].reverse().find(m=>m?.role==='assistant'&&String(m?.meta?.requestId||'')===rid);seed(message)}catch(_){}}
/* Persist the user's intended Activity Log state before native <details> toggle dispatch. Stream events can rebuild the response DOM between pointer interaction and the asynchronous toggle event, so this capture-phase write is the canonical anti-collapse guard. */
document.addEventListener('pointerdown',persistIntendedTraceState,true);
document.addEventListener('keydown',persistKeyboardTraceState,true);
/* Spawn the activity surface at the submit boundary instead of waiting for the first network event. Capture runs before Chat's submit listener; the microtask runs after sendMessage has created the assistant turn and before ordinary streamed events paint it. */
document.addEventListener('submit',event=>{try{const form=event.target;if(!(form instanceof HTMLFormElement)||form.id!=='composer')return;queueMicrotask(()=>seed(latestStreaming()))}catch(_){}},true);
window.fetch=function(input,init={}){if(isStream(input,init)){const payload=parseBody(init);if(payload)mark(payload);else queueMicrotask(()=>seed(latestStreaming()))}return priorFetch(input,init)};
})();
