(()=>{'use strict';
if(window.__swrlzUserSettingsV2Installed)return;window.__swrlzUserSettingsV2Installed=true;
const CLAIMS='swrlzGoogleLoginTestClaims',THEME='swrlz.chat.theme',BASE='swrlzUserUiPrefsV2';
const defaults={density:'comfortable',fontScale:'normal',reduceMotion:false,highContrast:false,largeControls:false,sendOnEnter:true,scrollMode:'smooth',showComposerTips:true};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function claims(){try{const v=JSON.parse(sessionStorage.getItem(CLAIMS)||'null');return v&&v.authenticated?v:null}catch{return null}}
function subject(){return String(claims()?.subject||'signed-out').trim()||'signed-out'}
function key(){return `${BASE}.account.${encodeURIComponent(subject())}`}
function read(){try{return {...defaults,...(JSON.parse(localStorage.getItem(key())||'{}')||{})}}catch{return {...defaults}}}
function save(v){try{localStorage.setItem(key(),JSON.stringify(v))}catch(_){}apply(v)}
function theme(){try{return localStorage.getItem(THEME)||'default'}catch{return'default'}}
function setTheme(v){try{localStorage.setItem(THEME,v)}catch(_){};window.IceDragonTheme?.set?.(v,true)}
function apply(p=read()){
 const root=document.documentElement;
 root.dataset.swrlzDensity=p.density;root.dataset.swrlzFontScale=p.fontScale;root.dataset.swrlzScroll=p.scrollMode;
 root.classList.toggle('swrlz-reduce-motion',!!p.reduceMotion);root.classList.toggle('swrlz-high-contrast',!!p.highContrast);root.classList.toggle('swrlz-large-controls',!!p.largeControls);root.classList.toggle('swrlz-hide-composer-tips',!p.showComposerTips);
}
function card(title,copy,control=''){return `<div class="swrlz-settings-card"><div class="swrlz-settings-card-copy"><strong>${title}</strong>${copy?`<span>${copy}</span>`:''}</div>${control}</div>`}
function select(name,value,items){return `<select data-ui-pref="${name}">${items.map(([v,l])=>`<option value="${v}" ${value===v?'selected':''}>${l}</option>`).join('')}</select>`}
function toggle(name,on,label){return `<label class="swrlz-switch"><input type="checkbox" data-ui-check="${name}" ${on?'checked':''}><span class="swrlz-switch-track"><span></span></span><em>${label}</em></label>`}
function notify(text){if(typeof window.toast==='function')window.toast(text);else{const n=document.createElement('div');n.className='swrlz-settings-toast';n.textContent=text;document.body.append(n);setTimeout(()=>n.remove(),1800)}}
function collect(detail){const p=read();detail.querySelectorAll('[data-ui-pref]').forEach(el=>p[el.dataset.uiPref]=el.value);detail.querySelectorAll('[data-ui-check]').forEach(el=>p[el.dataset.uiCheck]=el.checked);return p}
function diagnostics(){const c=claims(),p=read(),m=window.__swrlzContextCapacity?.metrics?.();return {settingsVersion:2,accountScope:c?'signed-in':'signed-out',theme:theme(),density:p.density,fontScale:p.fontScale,reduceMotion:p.reduceMotion,highContrast:p.highContrast,sendOnEnter:p.sendOnEnter,contextEstimate:m?{percent:m.percent,storedMessages:m.storedMessages,historyMessages:m.historyMessages,estimatedTokens:m.estimatedTokens}:null,userAgent:navigator.userAgent};}
function renderExtra(panel,name){
 const detail=panel.querySelector('[data-detail]');if(!detail)return;const p=read(),c=claims(),m=window.__swrlzContextCapacity?.metrics?.();
 if(name==='appearance')detail.innerHTML=`<div class="swrlz-settings-section-head"><div><span class="swrlz-settings-kicker">Interface</span><h3>Appearance</h3><p>Visual choices stay on this device and only change how the mask presents §wyrlz.</p></div></div><div class="swrlz-settings-card-list">${card('Chat theme','Choose the visual skin.',select('theme',theme(),[['default','Default'],['ice-dragon','❄ Ice Dragon']]))}${card('Interface density','Adjust spacing without changing conversation content.',select('density',p.density,[['comfortable','Comfortable'],['compact','Compact'],['roomy','Roomy']]))}${card('Text size','Scale Chat text for readability.',select('fontScale',p.fontScale,[['small','Small'],['normal','Default'],['large','Large'],['xlarge','Extra large']]))}</div><div class="swrlz-settings-actions"><button type="button" data-save-ui>Save appearance</button></div>`;
 if(name==='conversation')detail.innerHTML=`<div class="swrlz-settings-section-head"><div><span class="swrlz-settings-kicker">Chat behavior</span><h3>Conversation</h3><p>Input and scrolling preferences. They do not change model reasoning or server authority.</p></div></div><div class="swrlz-settings-card-list">${card('Enter key','Choose whether Enter sends or inserts a new line.',toggle('sendOnEnter',p.sendOnEnter,'Enter sends message'))}${card('Scrolling','Select the local visual scroll behavior.',select('scrollMode',p.scrollMode,[['smooth','Smooth'],['instant','Instant']]))}${card('Composer helper text','Show or hide small helper captions below the composer.',toggle('showComposerTips',p.showComposerTips,'Show helper text'))}</div><div class="swrlz-settings-actions"><button type="button" data-save-ui>Save conversation settings</button></div>`;
 if(name==='accessibility')detail.innerHTML=`<div class="swrlz-settings-section-head"><div><span class="swrlz-settings-kicker">Comfort & access</span><h3>Accessibility</h3><p>Presentation controls designed to reduce visual strain and make controls easier to use.</p></div></div><div class="swrlz-settings-card-list">${card('Reduced motion','Minimize nonessential transitions and animations.',toggle('reduceMotion',p.reduceMotion,'Reduce motion'))}${card('High contrast','Strengthen borders and text separation.',toggle('highContrast',p.highContrast,'Increase contrast'))}${card('Larger controls','Increase common button and input hit areas.',toggle('largeControls',p.largeControls,'Use larger controls'))}</div><div class="swrlz-settings-actions"><button type="button" data-save-ui>Save accessibility</button></div>`;
 if(name==='advanced'){
  const pct=m?`${m.percent}% estimated active context`:'Context estimate unavailable';
  detail.innerHTML=`<div class="swrlz-settings-section-head"><div><span class="swrlz-settings-kicker">Tools</span><h3>Advanced</h3><p>Utilities and factual diagnostics. No secret tokens are shown or copied.</p></div></div><div class="swrlz-settings-status-grid"><div><span>Account namespace</span><strong>${c?'Signed-in account':'Signed-out device'}</strong></div><div><span>Theme</span><strong>${esc(theme())}</strong></div><div><span>Conversation</span><strong>${esc(pct)}</strong></div><div><span>Settings</span><strong>UI preferences v2</strong></div></div><div class="swrlz-settings-tool-grid"><button type="button" data-open-bridge><strong>Bridge settings</strong><span>Open token and runtime verification controls.</span></button><button type="button" data-export-chat><strong>Export conversation</strong><span>Use the existing Chat export action.</span></button><button type="button" data-copy-diag><strong>Copy diagnostics</strong><span>Copy non-secret local UI and context facts.</span></button><button type="button" class="danger" data-reset-ui><strong>Reset interface preferences</strong><span>Reset only these device-side UI settings.</span></button></div>`;
 }
 detail.querySelector('[data-ui-pref="theme"]')?.addEventListener('change',e=>setTheme(e.target.value));
 detail.querySelector('[data-save-ui]')?.addEventListener('click',()=>{const next=collect(detail);const t=detail.querySelector('[data-ui-pref="theme"]')?.value;if(t)setTheme(t);save(next);notify('Settings saved')});
 detail.querySelector('[data-open-bridge]')?.addEventListener('click',()=>{panel.closest('.swrlz-account-modal')?.remove();setTimeout(()=>document.querySelector('#settingsButton')?.click(),0)});
 detail.querySelector('[data-export-chat]')?.addEventListener('click',()=>document.querySelector('#exportChat')?.click());
 detail.querySelector('[data-copy-diag]')?.addEventListener('click',async()=>{const text=JSON.stringify(diagnostics(),null,2);try{await navigator.clipboard.writeText(text);notify('Diagnostics copied')}catch(_){notify('Copy unavailable')}});
 detail.querySelector('[data-reset-ui]')?.addEventListener('click',()=>{if(!confirm('Reset interface preferences for this account on this device?'))return;localStorage.removeItem(key());apply(defaults);renderExtra(panel,'advanced');notify('Interface preferences reset')});
}
const labels={profile:['👤','Profile','Identity and account details'],data:['🛡️','Data & privacy','Storage and account data controls'],personalization:['✨','Personalization','Names and response depth'],appearance:['🎨','Appearance','Theme, spacing and text size'],conversation:['💬','Conversation','Composer and scrolling behavior'],accessibility:['♿','Accessibility','Motion, contrast and control size'],security:['🔐','Security','Sign-in and session controls'],advanced:['⚙️','Advanced','Bridge, export and diagnostics']};
function enhance(panel){if(!panel||panel.dataset.swrlzSettingsV2)return;panel.dataset.swrlzSettingsV2='true';panel.classList.add('swrlz-settings-v2');
 const head=panel.querySelector('.swrlz-panel-head');if(head){const title=head.querySelector('strong');if(title)title.textContent='Settings';const sub=head.querySelector('.swrlz-account-sub');if(sub&&!sub.querySelector('.swrlz-settings-head-note')){const note=document.createElement('span');note.className='swrlz-settings-head-note';note.textContent='Your account, interface, privacy and device preferences';sub.appendChild(note)}const badge=document.createElement('span');badge.className='swrlz-settings-scope-badge';badge.textContent=claims()?'Account scoped':'Device scoped';head.insertBefore(badge,head.lastElementChild)}
 const nav=panel.querySelector('.swrlz-settings-list');if(!nav)return;nav.setAttribute('aria-label','Settings sections');
 nav.querySelectorAll('[data-setting]').forEach(btn=>{const x=labels[btn.dataset.setting];if(!x)return;btn.innerHTML=`<i aria-hidden="true">${x[0]}</i><span class="swrlz-settings-nav-copy"><strong>${x[1]}</strong><small>${x[2]}</small></span>`});
 const before=nav.querySelector('[data-setting="security"]');for(const name of ['appearance','conversation','accessibility','advanced']){if(nav.querySelector(`[data-setting="${name}"]`))continue;const x=labels[name],b=document.createElement('button');b.type='button';b.dataset.setting=name;b.innerHTML=`<i aria-hidden="true">${x[0]}</i><span class="swrlz-settings-nav-copy"><strong>${x[1]}</strong><small>${x[2]}</small></span>`;if(before)nav.insertBefore(b,before);else nav.appendChild(b);b.addEventListener('click',()=>{nav.querySelectorAll('[data-setting]').forEach(v=>v.classList.toggle('active',v===b));renderExtra(panel,name)})}
 panel.querySelector('[data-detail]')?.setAttribute('aria-live','polite');
}
function scan(){document.querySelectorAll('.swrlz-account-panel').forEach(enhance)}
function installPromptBehavior(){document.addEventListener('keydown',e=>{if(e.target?.id!=='prompt'||e.key!=='Enter'||e.shiftKey||e.isComposing)return;if(read().sendOnEnter===false)e.stopImmediatePropagation()},true)}
const obs=new MutationObserver(scan);function boot(){apply();scan();installPromptBehavior();obs.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('swrlz:account-change',()=>apply(read()));window.addEventListener('storage',e=>{if(e.key===key())apply(read())})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.__swrlzUserSettingsV2={version:2,read,apply,diagnostics};
})();