(()=>{"use strict";const $=s=>document.querySelector(s);const safe=v=>v??"—";const settingsKey="swrlz.chat.generation.v1";let camera=[];let ops=null;
function modal(title,body){let m=document.createElement('div');m.className='swrlz-modal';m.innerHTML=`<div class="swrlz-panel"><div style="display:flex;justify-content:space-between;gap:8px;align-items:center"><h3>${title}</h3><button data-close>CLOSE</button></div><div data-body></div></div>`;m.querySelector('[data-body]').append(body);m.querySelector('[data-close]').onclick=()=>m.remove();document.body.append(m);return m}
async function loadOps(){try{let r=await fetch('/api/chat/ops',{cache:'no-store'});ops=await r.json();paintMode()}catch(_){ops=null;paintMode()}}
function paintMode(){let el=$('#swrlzMode');if(!el)return;let mode=ops?.mode||'UNKNOWN';let inst=ops?.operations?.server?.instanceId||'';el.textContent=mode+(inst?' · '+inst:'')}
function contextInspector(){let t=currentThread();let h=t.messages.filter(m=>m.text&&['user','assistant'].includes(m.role)).slice(-32).map(m=>({role:m.role,text:m.text.slice(0,2000)}));let pre=document.createElement('pre');pre.textContent=JSON.stringify({threadId:t.id,turns:h.length,history:h},null,2);modal('Context inspector',pre)}
function controls(){let cfg={temperature:.7,topP:.95,maxTokens:512,...JSON.parse(localStorage.getItem(settingsKey)||'{}')};let box=document.createElement('div');box.innerHTML=`<label>Temperature <input id="gtemp" type="number" min="0" max="2" step="0.05" value="${cfg.temperature}"></label><br><br><label>Top P <input id="gtop" type="number" min="0" max="1" step="0.01" value="${cfg.topP}"></label><br><br><label>Max tokens <input id="gmax" type="number" min="1" max="512" value="${cfg.maxTokens}"></label><br><br><button id="gsave">SAVE CONTROLS</button>`;box.querySelector('#gsave').onclick=()=>{let v={temperature:+box.querySelector('#gtemp').value,topP:+box.querySelector('#gtop').value,maxTokens:+box.querySelector('#gmax').value};localStorage.setItem(settingsKey,JSON.stringify(v));toast('Generation controls saved')};modal('Generation controls',box)}
function streamCamera(){let pre=document.createElement('pre');pre.className='swrlz-camera';pre.textContent=camera.length?camera.slice(-120).map(x=>`${x.at} #${x.seq} ${x.type} ${x.phase||''} ${x.text||''}`).join('\n'):'No stream events captured yet.';modal('Stream camera',pre)}
function forkAt(message){let t=currentThread(),i=t.messages.findIndex(m=>m.id===message.id);if(i<0)return;let stamp=now();let copy=JSON.parse(JSON.stringify(t.messages.slice(0,i+1)));let nt={id:uid('thread'),title:'Fork · '+t.title,createdAt:stamp,updatedAt:stamp,pinned:false,messages:copy};state.threads.push(nt);state.currentId=nt.id;saveState();render(true);toast('Forked conversation')}
function retryMessage(message){let t=currentThread(),i=t.messages.findIndex(m=>m.id===message.id);for(let n=i-1;n>=0;n--){if(t.messages[n].role==='user'&&t.messages[n].text){refs.prompt.value=t.messages[n].text;resizePrompt();sendMessage();return}}toast('No user prompt found to retry')}
function sendWorkbench(message){let admin=sessionStorage.getItem('swrlzAdminToken')||prompt('Admin token');if(!admin)return;sessionStorage.setItem('swrlzAdminToken',admin);let name=prompt('Save response as','chat-response-'+Date.now()+'.md');if(!name)return;let path='/tmp/swrlz-admin/web/'+name;fetch('/api/admin?'+new URLSearchParams({action:'save-text',path}),{method:'POST',headers:{'x-swrlz-admin-token':admin},body:new Blob([message.text||''],{type:'text/plain'})}).then(async r=>{let j=await r.json();if(!r.ok)throw Error(JSON.stringify(j));toast('Sent to Workbench · /live/'+name)}).catch(e=>toast('Workbench save failed: '+e.message))}
const baseRenderMessage=renderMessage;renderMessage=function(message){let article=baseRenderMessage(message);if(message.role==='assistant'){let d=document.createElement('details');d.className='swrlz-evidence';let m=message.meta||{};d.innerHTML=`<summary>Evidence · ${safe(m.phase)} · ${safe(m.requestId)}</summary><div class="swrlz-evidence-grid"><span>route: ${safe(m.route)}</span><span>engine: ${safe(m.engineId)}</span><span>model: ${safe(m.modelId)}</span><span>TTFT: ${safe(m.firstDeltaLatencyMs)} ms</span><span>total: ${safe(m.totalLatencyMs)} ms</span><span>finish: ${safe(message.state)}</span></div>`;let a=document.createElement('div');a.className='swrlz-evidence-actions';[['RETRY',()=>retryMessage(message)],['FORK HERE',()=>forkAt(message)],['SEND TO WORKBENCH',()=>sendWorkbench(message)],['EXPORT TRACE',()=>{let b=new Blob([JSON.stringify({message,threadId:currentThread().id},null,2)],{type:'application/json'}),u=URL.createObjectURL(b),x=document.createElement('a');x.href=u;x.download=(m.requestId||'trace')+'.json';x.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}]].forEach(([n,f])=>{let b=document.createElement('button');b.textContent=n;b.onclick=f;a.append(b)});d.append(a);article.querySelector('.message-body')?.append(d)}return article};
const baseConsume=consumeEvent;consumeEvent=function(event,context){camera.push({at:new Date().toISOString().slice(11,23),seq:event?.seq,type:event?.type,phase:event?.phase,text:event?.type==='DELTA'?String(event.text||'').slice(0,40):event?.reason||''});if(camera.length>500)camera=camera.slice(-500);return baseConsume(event,context)};
const nativeFetch=window.fetch.bind(window);window.fetch=async function(input,init){try{let url=typeof input==='string'?input:input.url;if(url.includes('?action=stream')&&init?.body){let p=JSON.parse(init.body),g=JSON.parse(localStorage.getItem(settingsKey)||'{}');p.generation=g;init={...init,body:JSON.stringify(p)}}}catch(_){}return nativeFetch(input,init)};
function searchThreads(q){q=q.toLowerCase().trim();document.querySelectorAll('.thread').forEach(el=>{let text=el.textContent.toLowerCase();el.style.display=!q||text.includes(q)?'':'none'})}
let bar=document.createElement('div');bar.className='swrlz-enhance-bar';bar.innerHTML='<span id="swrlzMode" class="swrlz-mode">LOADING</span><input class="swrlz-search" placeholder="Search threads"><button class="swrlz-tools-toggle" type="button" aria-expanded="false">TOOLS</button><button data-context>CONTEXT</button><button data-controls>GENERATION</button><button data-camera>STREAM CAMERA</button><button data-ops>REFRESH STATE</button>';let workspace=$('.workspace');let top=$('.topbar');if(workspace&&top)top.insertAdjacentElement('afterend',bar);bar.querySelector('.swrlz-search').oninput=e=>searchThreads(e.target.value);let toggle=bar.querySelector('.swrlz-tools-toggle');toggle.onclick=()=>{let open=bar.dataset.expanded==='true';bar.dataset.expanded=open?'false':'true';toggle.setAttribute('aria-expanded',String(!open));toggle.textContent=open?'TOOLS':'CLOSE'};bar.querySelector('[data-context]').onclick=contextInspector;bar.querySelector('[data-controls]').onclick=controls;bar.querySelector('[data-camera]').onclick=streamCamera;bar.querySelector('[data-ops]').onclick=loadOps;loadOps();setInterval(loadOps,15000);
})();
