(()=>{"use strict";
const AUTH_ROOT="https://raw.githubusercontent.com/kaministrator999-ui/Swrlzkamico/runtime/";
const INDEX_URL=`${AUTH_ROOT}VERSION.txt`;
const LALM_CACHE_KEY="swrlzLalmReadinessV1",LALM_CACHE_TTL_MS=10*60*1000;
const parseKV=t=>Object.fromEntries(String(t||"").split(/\r?\n/).map(x=>x.trim()).filter(x=>x&&!x.startsWith("#")&&x.includes("=")).map(x=>{const i=x.indexOf("=");return[x.slice(0,i).trim(),x.slice(i+1).trim()]}));
const log=(event,data={})=>{try{window.__swrlzDebug?.log("version-authority",event,data)}catch(_){}};
const fetchText=url=>fetch(`${url}${url.includes("?")?"&":"?"}ts=${Date.now()}`,{cache:"no-store"}).then(r=>r.ok?r.text():Promise.reject(new Error(`HTTP ${r.status} ${url}`)));
const apply=()=>{const foot=document.querySelector(".sidebar-foot");if(!foot)return;let line=document.querySelector("#swrlzChatVersion");if(!line){line=document.createElement("div");line.id="swrlzChatVersion";line.className="swrlz-version-line";line.style.cssText="padding:4px 9px 2px;color:var(--muted);font-size:10px;letter-spacing:.05em;opacity:.9;line-height:1.45;";foot.appendChild(line)}
const renderVersions=(m={})=>{const p=[];if(m.WEB_CHAT?.VERSION)p.push(`Chat v${m.WEB_CHAT.VERSION}`);if(m.STREAM_CONTRACT?.VERSION)p.push(`Stream ${m.STREAM_CONTRACT.VERSION}`);if(m.SERVER_RUNTIME?.VERSION)p.push(`Server runtime v${m.SERVER_RUNTIME.VERSION}`);if(m.LALM_ENGINE?.VERSION)p.push(`LALM engine v${m.LALM_ENGINE.VERSION}`);line.textContent=p.join(" · ")||"Version registry unavailable"};
const loadVersions=async()=>{try{log("index-fetch-start",{index:INDEX_URL});const index=parseKV(await fetchText(INDEX_URL));const keys=["WEB_CHAT","STREAM_CONTRACT","SERVER_RUNTIME","LALM_ENGINE"];const pairs=await Promise.all(keys.map(async key=>{const path=index[key];if(!path)throw new Error(`VERSION.txt missing ${key}`);return[key,parseKV(await fetchText(`${AUTH_ROOT}${path}`))]}));const mods=Object.fromEntries(pairs);renderVersions(mods);window.__swrlzChatVersionAuthority={index:INDEX_URL,keys,source:"runtime-VERSION.txt",loadedAt:Date.now()};log("registry-ready",Object.fromEntries(keys.map(k=>[k,mods[k]?.VERSION||""])))}catch(error){line.textContent="Version registry unavailable";window.__swrlzChatVersionAuthority={index:INDEX_URL,source:"runtime-VERSION.txt",error:String(error?.message||error),loadedAt:Date.now()};log("registry-error",{error:String(error?.message||error)})}};
const els=()=>({title:document.querySelector("#nodeTitle"),detail:document.querySelector("#nodeDetail"),light:document.querySelector("#nodeLight"),pill:document.querySelector("#statusPill"),pillText:document.querySelector("#statusText")});
const paintState=(kind,detailText)=>{const{title,detail,light,pill,pillText}=els();if(!title||!detail||!light)return;light.classList.remove("ready","error");if(pill)pill.classList.remove("ready","error");if(kind==="ready"){light.classList.add("ready");if(pill)pill.classList.add("ready");if(pillText)pillText.textContent="LALM ready";title.textContent="Local LALM ready";detail.textContent="R39 resident · native backend"}else if(kind==="error"){light.classList.add("error");if(pill)pill.classList.add("error");if(pillText)pillText.textContent="LALM unavailable";title.textContent="Local LALM unavailable";detail.textContent=detailText||"Check LALM status"}else{if(pillText)pillText.textContent="LALM warming";title.textContent="Local LALM warming";detail.textContent="R39 is being prepared"}};
const readCached=()=>{try{const c=JSON.parse(sessionStorage.getItem(LALM_CACHE_KEY)||"null");if(c&&c.ready===true&&Date.now()-Number(c.at||0)<=LALM_CACHE_TTL_MS){paintState("ready");return true}}catch(_){}return false};
const paintLalm=async()=>{try{const r=await fetch("/api/lalm/status",{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const s=await r.json(),ready=Boolean(s?.readiness?.interactiveReady),failed=s?.readiness?.ok===false;if(ready){paintState("ready");try{sessionStorage.setItem(LALM_CACHE_KEY,JSON.stringify({ready:true,at:Date.now()}))}catch(_){}}else if(failed){const d=String(s?.readiness?.detail||s?.readiness?.code||"Check LALM status");paintState("error",d);log("lalm-readiness-error",{detail:d});try{sessionStorage.removeItem(LALM_CACHE_KEY)}catch(_){}}else paintState("warming")}catch(e){paintState("error","LALM status unavailable");log("lalm-status-fetch-error",{error:String(e?.message||e)})}};
loadVersions();if(!readCached())paintState("warming");paintLalm();window.setInterval(paintLalm,60000);window.addEventListener("focus",()=>{paintLalm();loadVersions()});document.addEventListener("visibilitychange",()=>{if(!document.hidden)loadVersions()})};
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",apply,{once:true});else apply();})();
