(()=>{"use strict";
if(window.__swrlzDebug)return;
const KEY='swrlz.chat.debug.v1',MAX=240,RUN=(crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`),ENDPOINT='/api/chat/client-debug';
let entries=[];try{const v=JSON.parse(localStorage.getItem(KEY)||'[]');if(Array.isArray(v))entries=v.slice(-MAX)}catch(_){ }
const clean=v=>{try{if(v instanceof Error)return{name:v.name,message:v.message,stack:v.stack};if(typeof v==='string'||typeof v==='number'||typeof v==='boolean'||v==null)return v;return JSON.parse(JSON.stringify(v))}catch(_){return String(v)}};
function persist(){try{localStorage.setItem(KEY,JSON.stringify(entries.slice(-MAX)))}catch(_){ }}
function send(e){const payload=JSON.stringify({runId:RUN,url:location.pathname,ua:navigator.userAgent,event:e});try{fetch(ENDPOINT,{method:'POST',headers:{'content-type':'application/json'},body:payload,keepalive:true,cache:'no-store',credentials:'same-origin'}).catch(()=>{})}catch(_){ }}
function beacon(e){const payload=JSON.stringify({runId:RUN,url:location.pathname,ua:navigator.userAgent,event:e});try{if(navigator.sendBeacon)navigator.sendBeacon(ENDPOINT,new Blob([payload],{type:'application/json'}))}catch(_){ }}
function log(type,message,data){const e={at:new Date().toISOString(),ms:Math.round(performance.now()),type:String(type||'info'),message:String(message||''),data:clean(data)};entries.push(e);if(entries.length>MAX)entries=entries.slice(-MAX);persist();send(e);return e}
function text(){return[`SWRLZ Chat Debug Log`,`Run: ${RUN}`,`URL: ${location.href}`,`UA: ${navigator.userAgent}`,`Generated: ${new Date().toISOString()}`,'',...entries.map(e=>`[${e.at}] +${e.ms}ms ${e.type.toUpperCase()} ${e.message}${e.data===undefined?'':' '+JSON.stringify(e.data)}`)].join('\n')}
async function copy(){const value=text();try{await navigator.clipboard.writeText(value);return true}catch(_){return false}}
function download(){const blob=new Blob([text()],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`swrlz-chat-debug-${RUN}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function clear(){entries=[];persist();log('debug','log-cleared')}
window.__swrlzDebug={version:8,runId:RUN,log,text,copy,download,clear,get entries(){return entries.slice()}};window.__swrlzDebugLog=entries;
/* Diagnostic code is intentionally layout-neutral. chat_mobile_viewport_fix.css is the sole mobile viewport/sidebar authority. */
let lastViewport={h:0,w:0,top:0,left:0,keyboard:false,vvH:0,layoutH:0};
function snapshotElement(selector){const el=document.querySelector(selector);if(!el)return null;const r=el.getBoundingClientRect(),c=getComputedStyle(el);return{selector,left:Math.round(r.left),right:Math.round(r.right),top:Math.round(r.top),bottom:Math.round(r.bottom),width:Math.round(r.width),height:Math.round(r.height),clientWidth:el.clientWidth,scrollWidth:el.scrollWidth,position:c.position,zIndex:c.zIndex,transform:c.transform,opacity:c.opacity,filter:c.filter,backdropFilter:c.backdropFilter||c.webkitBackdropFilter||'none',overflowX:c.overflowX,display:c.display}}
function geometry(reason){const vv=window.visualViewport;const data={reason,sidebarOpen:document.body?.classList.contains('sidebar-open')||false,viewport:{innerWidth:window.innerWidth,innerHeight:window.innerHeight,visualWidth:Math.round(vv?.width||0),visualHeight:Math.round(vv?.height||0),offsetLeft:Math.round(vv?.offsetLeft||0),offsetTop:Math.round(vv?.offsetTop||0),scale:vv?.scale||1,screenWidth:screen?.width||0,screenHeight:screen?.height||0,dpr:devicePixelRatio||1},document:{clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,bodyClientWidth:document.body?.clientWidth||0,bodyScrollWidth:document.body?.scrollWidth||0},elements:['.app','.workspace','.topbar','.messages','.message-stack','.composer-shell','.sidebar','.sidebar-scrim'].map(snapshotElement).filter(Boolean)};log('layout','geometry-v2',data);return data}
function syncVisualViewport(reason){const vv=window.visualViewport;const vvH=Math.max(1,Math.round(vv?.height||window.innerHeight||document.documentElement.clientHeight));const w=Math.max(1,Math.round(vv?.width||window.innerWidth||document.documentElement.clientWidth));const top=Math.max(0,Math.round(vv?.offsetTop||0));const left=Math.max(0,Math.round(vv?.offsetLeft||0));const layoutH=Math.max(vvH,Math.round(window.innerHeight||document.documentElement.clientHeight||vvH));const focused=document.activeElement;const editable=!!focused&&(focused.matches?.('textarea,input,[contenteditable="true"]')||focused.isContentEditable);const keyboard=editable&&(layoutH-vvH>80||Math.round(screen?.height||0)-vvH>220);const changed=vvH!==lastViewport.h||w!==lastViewport.w||top!==lastViewport.top||left!==lastViewport.left||keyboard!==lastViewport.keyboard||layoutH!==lastViewport.layoutH;if(changed){lastViewport={h:vvH,w,top,left,keyboard,vvH,layoutH};log('viewport','visual-viewport-observed',{reason,h:vvH,w,top,left,vvH,layoutH,keyboard,authority:'observer-only'});requestAnimationFrame(()=>geometry(`viewport:${reason}`))}}
if(window.visualViewport){visualViewport.addEventListener('resize',()=>syncVisualViewport('resize'),{passive:true});visualViewport.addEventListener('scroll',()=>syncVisualViewport('scroll'),{passive:true})}window.addEventListener('resize',()=>syncVisualViewport('window-resize'),{passive:true});window.addEventListener('orientationchange',()=>setTimeout(()=>syncVisualViewport('orientation'),80),{passive:true});document.addEventListener('focusin',()=>setTimeout(()=>syncVisualViewport('focusin'),50),true);document.addEventListener('focusout',()=>setTimeout(()=>syncVisualViewport('focusout'),80),true);
const sidebarObserver=new MutationObserver(m=>{if(m.some(x=>x.attributeName==='class'))requestAnimationFrame(()=>geometry('body-class-change'))});const bind=()=>{syncVisualViewport('dom-ready');if(document.body)sidebarObserver.observe(document.body,{attributes:true,attributeFilter:['class']});requestAnimationFrame(()=>geometry('dom-ready'))};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
window.addEventListener('error',e=>log('error','window-error',{message:e.message,source:e.filename,line:e.lineno,column:e.colno,error:clean(e.error)}));window.addEventListener('unhandledrejection',e=>log('error','unhandled-rejection',clean(e.reason)));document.addEventListener('visibilitychange',()=>log('lifecycle','visibility',{state:document.visibilityState}));window.addEventListener('pageshow',e=>{log('lifecycle','pageshow',{persisted:e.persisted});syncVisualViewport('pageshow');requestAnimationFrame(()=>geometry('pageshow'))});window.addEventListener('pagehide',e=>{const event={at:new Date().toISOString(),ms:Math.round(performance.now()),type:'lifecycle',message:'pagehide',data:{persisted:e.persisted}};entries.push(event);if(entries.length>MAX)entries=entries.slice(-MAX);persist();beacon(event)});log('boot','debug-logger-ready',{readyState:document.readyState,runId:RUN,delivery:'fetch-keepalive',layoutAuthority:'observer-only-v8'});
})();