(()=>{'use strict';
if(window.__swrlzChatLanguagePreferencesV1)return;
const KEY='swrlz.chat.language.preferences.v1';
const DEFAULT={profanity:'clean'};
function read(){try{const v=JSON.parse(localStorage.getItem(KEY)||'null');return {profanity:v?.profanity==='allowed'?'allowed':'clean'}}catch(_){return {...DEFAULT}}}
function write(next){const value={profanity:next?.profanity==='allowed'?'allowed':'clean'};try{localStorage.setItem(KEY,JSON.stringify(value))}catch(_){}return value}
const ctl={contract:'swrlz-chat-language-preferences-v1',read,write};window.__swrlzChatLanguagePreferencesV1=ctl;
function installUi(){const dialog=document.querySelector('#settingsDialog .dialog-body');if(!dialog||dialog.querySelector('[data-swrlz-language-preferences]'))return;const field=document.createElement('div');field.className='field';field.dataset.swrlzLanguagePreferences='v1';const label=document.createElement('label');label.textContent='Language style';const select=document.createElement('select');select.className='route-select';select.style.maxWidth='100%';select.style.width='100%';select.setAttribute('aria-label','Profanity preference');select.innerHTML='<option value="clean">Clean language</option><option value="allowed">Profanity allowed</option>';select.value=read().profanity;const small=document.createElement('small');small.textContent='Clean is the default. “Profanity allowed” gives §wyrlz permission to use it when contextually appropriate; it does not force profanity.';select.addEventListener('change',()=>{write({profanity:select.value});try{window.__swrlzDebug?.log('language-preference','profanity-updated',{profanity:read().profanity})}catch(_){}});field.append(label,select,small);const runtime=dialog.querySelector('.runtime-panel');dialog.insertBefore(field,runtime||dialog.firstChild);}
installUi();new MutationObserver(installUi).observe(document.documentElement,{childList:true,subtree:true});
const priorFetch=window.fetch.bind(window);window.fetch=function(input,init){try{if(init&&String(init.method||'GET').toUpperCase()==='POST'&&typeof init.body==='string'){const p=JSON.parse(init.body);if(p?.protocolVersion===2&&p?.requestId&&p?.prompt&&p?.threadId){const prefs=read();return priorFetch(input,{...init,body:JSON.stringify({...p,userPreferences:{...(p.userPreferences||{}),profanity:prefs.profanity}})});}}}catch(_){}return priorFetch(input,init)};
})();