(()=>{"use strict";
const UI_VERSION='1.3.13';
const $=s=>document.querySelector(s),safe=v=>v??'—';
const settingsKey='swrlz.chat.generation.v1';
const ADMIN_KEY='swrlzAdminToken',SESSION_KEY='swrlz.vercel.chat.admin-session.v1',TOKEN_KEY='swrlz.vercel.chat.token.v1',SESSION_MARKER='__ADMIN_SESSION_AUTHORIZED__';
let camera=[],ops=null;
function modal(title,body,actions=[]){let m=document.createElement('div');m.className='swrlz-modal';m.innerHTML=`<div class="swrlz-panel"><div class="swrlz-panel-head"><h3>${title}</h3><div data-actions></div></div><div data-body></div></div>`;m.querySelector('[data-body]').append(body);let a=m.querySelector('[data-actions]');actions.forEach(([n,f])=>{let b=document.createElement('button');b.textContent=n;b.onclick=f;a.append(b)});let close=document.createElement('button');close.textContent='CLOSE';close.onclick=()=>m.remove();a.append(close);document.body.append(m);return m}
async function copyText(text){try{await navigator.clipboard.writeText(text);toast('Copied to clipboard')}catch(_){let ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();toast('Copied to clipboard')}}
async function loadOps(){try{let r=await fetch('/api/chat/ops',{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);ops=await r.json();paintMode()}catch(_){ops=null;paintMode()}}
function paintMode(){let el=$('#swrlzMode'),mode=ops?.mode||'UNKNOWN',inst=ops?.operations?.server?.instanceId||'',server=ops?.operations?.server?.version||'—';if(el)el.textContent=mode+(inst?' · '+inst:'');let local=ops?.localR39||{},localReady=mode==='LOCAL_R39'&&(local.oneTokenReady||local.interactiveReady||ops?.operations?.localEngine?.oneTokenReady||ops?.operations?.localEngine?.interactiveReady),upstreamReady=mode==='UPSTREAM_SERVER'&&ops?.upstream?.configurationReady,ready=localReady||upstreamReady;document.querySelectorAll('.status-pill').forEach(x=>{x.classList.toggle('ready',!!ready);x.classList.toggle('error',mode==='UNKNOWN')});document.querySelectorAll('.node-light').forEach(x=>{x.classList.toggle('ready',!!ready);x.classList.toggle('error',mode==='UNKNOWN')});let strong=$('#nodeTitle'),sub=$('#nodeDetail');if(strong)strong.textContent=mode==='LOCAL_R39'?(localReady?'Local R39 ready':'Local R39 initializing'):mode==='UPSTREAM_SERVER'?(upstreamReady?'Upstream bridge ready':'Upstream setup needed'):'Runtime status unavailable';if(sub)sub.textContent=`Chat v${UI_VERSION} · Server v${server}`;let v=$('#swrlzHotVersionLine');if(v)v.textContent=`CHAT v${UI_VERSION} · SERVER v${server}`;settingsUX();statusPanelUX()}
function contextInspector(){let t=currentThread(),h=t.messages.filter(m=>m.text&&['user','assistant'].includes(m.role)).slice(-32).map(m=>({role:m.role,text:m.text.slice(0,2000)})),pre=document.createElement('pre');pre.textContent=JSON.stringify({threadId:t.id,turns:h.length,history:h},null,2);modal('Context inspector',pre)}
function controls(){let cfg={temperature:.7,topP:.95,maxTokens:512,...JSON.parse(localStorage.getItem(settingsKey)||'{}')},box=document.createElement('div');box.innerHTML=`<label>Temperature <input id="gtemp" type="number" min="0" max="2" step="0.05" value="${cfg.temperature}"></label><br><br><label>Top P <input id="gtop" type="number" min="0" max="1" step="0.01" value="${cfg.topP}"></label><br><br><label>Max tokens <input id="gmax" type="number" min="1" max="512" value="${cfg.maxTokens}"></label><br><br><button id="gsave">SAVE CONTROLS</button>`;box.querySelector('#gsave').onclick=()=>{let v={temperature:+box.querySelector('#gtemp').value,topP:+box.querySelector('#gtop').value,maxTokens:+box.querySelector('#gmax').value};localStorage.setItem(settingsKey,JSON.stringify(v));toast('Generation controls saved')};modal('Generation controls',box)}
function cameraText(){return camera.length?camera.slice(-120).map(x=>`${x.at} #${x.seq} ${x.type} ${x.phase||''} ${x.text||''}`).join('\n'):'No stream events captured yet.'}
function streamCamera(){let pre=document.createElement('pre');pre.className='swrlz-camera';pre.textContent=cameraText();modal('Stream camera',pre,[['COPY TEXT',()=>copyText(cameraText())],['CLEAR CAMERA',()=>{camera=[];pre.textContent=cameraText();toast('Stream camera cleared')}]] )}
function forkAt(message){let t=currentThread(),i=t.messages.findIndex(m=>m.id===message.id);if(i<0)return;let stamp=now(),copy=JSON.parse(JSON.stringify(t.messages.slice(0,i+1))),nt={id:uid('thread'),title:'Fork · '+t.title,createdAt:stamp,updatedAt:stamp,pinned:false,messages:copy};state.threads.push(nt);state.currentId=nt.id;saveState();render(true);toast('Forked conversation')}
function retryMessage(message){let t=currentThread(),i=t.messages.findIndex(m=>m.id===message.id);for(let n=i-1;n>=0;n--)if(t.messages[n].role==='user'&&t.messages[n].text){refs.prompt.value=t.messages[n].text;resizePrompt();sendMessage();return}toast('No user prompt found to retry')}
function sendWorkbench(message){let admin=sessionStorage.getItem(ADMIN_KEY)||prompt('Admin token');if(!admin)return;sessionStorage.setItem(ADMIN_KEY,admin);let name=prompt('Save response as','chat-response-'+Date.now()+'.md');if(!name)return;let path='/tmp/swrlz-admin/web/'+name;fetch('/api/admin?'+new URLSearchParams({action:'save-text',path}),{method:'POST',headers:{'x-swrlz-admin-token':admin},body:new Blob([message.text||''],{type:'text/plain'})}).then(async r=>{let j=await r.json();if(!r.ok)throw Error(JSON.stringify(j));toast('Sent to Workbench · /live/'+name)}).catch(e=>toast('Workbench save failed: '+e.message))}
const baseRenderMessage=renderMessage;renderMessage=function(message){let article=baseRenderMessage(message);if(message.role==='assistant'){let d=document.createElement('details');d.className='swrlz-evidence';let m=message.meta||{};d.innerHTML=`<summary>Evidence · ${safe(m.phase)} · ${safe(m.requestId)}</summary><div class="swrlz-evidence-grid"><span>route: ${safe(m.route)}</span><span>engine: ${safe(m.engineId)}</span><span>model: ${safe(m.modelId)}</span><span>TTFT: ${safe(m.firstDeltaLatencyMs)} ms</span><span>total: ${safe(m.totalLatencyMs)} ms</span><span>finish: ${safe(message.state)}</span></div>`;let a=document.createElement('div');a.className='swrlz-evidence-actions';[['RETRY',()=>retryMessage(message)],['FORK HERE',()=>forkAt(message)],['SEND TO WORKBENCH',()=>sendWorkbench(message)],['EXPORT TRACE',()=>{let b=new Blob([JSON.stringify({message,threadId:currentThread().id},null,2)],{type:'application/json'}),u=URL.createObjectURL(b),x=document.createElement('a');x.href=u;x.download=(m.requestId||'trace')+'.json';x.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}]].forEach(([n,f])=>{let b=document.createElement('button');b.textContent=n;b.onclick=f;a.append(b)});d.append(a);article.querySelector('.message-body')?.append(d)}return article};
const baseConsume=consumeEvent;consumeEvent=function(event,context){camera.push({at:new Date().toISOString().slice(11,23),seq:event?.seq,type:event?.type,phase:event?.phase,text:event?.type==='DELTA'?String(event.text||'').slice(0,120):event?.reason||''});if(camera.length>500)camera=camera.slice(-500);return baseConsume(event,context)};
const nativeFetch=window.fetch.bind(window);window.fetch=async function(input,init={}){try{let url=typeof input==='string'?input:input.url,u=new URL(url,location.href),headers=new Headers(init.headers||{}),session=sessionStorage.getItem(SESSION_KEY)||'';if(session&&u.origin===location.origin&&(u.pathname==='/api/chat'||u.pathname.startsWith('/api/chat/')))headers.set('X-SWRLZ-Chat-Session',session);if(url.includes('?action=stream')&&init?.body){let p=JSON.parse(init.body),g=JSON.parse(localStorage.getItem(settingsKey)||'{}');p.generation=g;init={...init,body:JSON.stringify(p),headers}}else init={...init,headers}}catch(_){}return nativeFetch(input,init)};
const baseToken=token;token=function(){let session=sessionStorage.getItem(SESSION_KEY)||'';return session?SESSION_MARKER:baseToken()};
async function ensureAdminSession(force=false){let current=sessionStorage.getItem(SESSION_KEY)||'';if(current&&!force&&current.includes('.'))return true;let admin=(sessionStorage.getItem(ADMIN_KEY)||'').trim();if(!admin)return false;try{let r=await nativeFetch('/api/chat/admin-session',{method:'POST',headers:{'X-SWRLZ-Admin-Token':admin},cache:'no-store'}),j=await r.json().catch(()=>({}));if(!r.ok||!j.session)throw Error(j.detail||`HTTP ${r.status}`);sessionStorage.setItem(SESSION_KEY,String(j.session));sessionStorage.setItem(TOKEN_KEY,SESSION_MARKER);settingsUX();statusPanelUX();return true}catch(_){sessionStorage.removeItem(SESSION_KEY);return false}}
const baseSendMessage=sendMessage;sendMessage=async function(){if(!token()){let ok=await ensureAdminSession();if(!ok){toast('Chat authorization is not active. Open Admin once in this tab, then send again.');return}}return baseSendMessage()};
function searchThreads(q){q=q.toLowerCase().trim();document.querySelectorAll('.thread').forEach(el=>{let text=el.textContent.toLowerCase();el.style.display=!q||text.includes(q)?'':'none'})}
function repairDrawerStack(){let scrim=$('#sidebarScrim'),app=$('.app'),side=$('.sidebar');if(scrim&&app&&side&&scrim.parentElement!==app)app.insertBefore(scrim,side.nextSibling)}
function settingsUX(){let dialog=$('#settingsDialog');if(!dialog)return;let heading=dialog.querySelector('.dialog-head h2');if(heading)heading.textContent='Chat settings';let field=$('#accessToken')?.closest('.field');if(field)field.style.display='none';let verify=$('#verifyR39');if(verify)verify.textContent='Verify model';}
function statusPanelUX(){let panel=$('#runtimePanel');if(!panel)return;if(!ops){panel.innerHTML='<strong>Chat status</strong><br>Status unavailable. Refresh state to retry.';return}let mode=ops.mode||'UNKNOWN',server=ops?.operations?.server||{},local=ops.localR39||{},session=sessionStorage.getItem(SESSION_KEY)?'ACTIVE':'NOT ACTIVE',modelState=local.interactiveReady?'READY':local.oneTokenReady?'ONE-TOKEN READY':local.readinessChecked?'CHECKED / NOT READY':'NOT PROBED',engine=local.engineId||ops?.operations?.localEngine?.engineId||'—',source=local.engineSource||ops?.operations?.localEngine?.source||'—',sha=local.modelSha256||ops?.operations?.localEngine?.modelSha256||'',blocker=(local.blockers||[])[0]||'none',route=mode==='LOCAL_R39'?'LOCAL R39':mode==='UPSTREAM_SERVER'?'UPSTREAM SERVER':mode;panel.innerHTML=`<strong>Chat status</strong><br>Route: ${route}<br>Server: v${server.version||'—'} · ${server.instanceId||'instance —'}<br>Authorization: ${session}<br><br><strong>Model status</strong><br>State: ${modelState}<br>Engine: ${engine}<br>Source: ${source}${sha?`<br>Model SHA: ${sha.slice(0,12)}…`:''}${modelState==='READY'?'':`<br>Blocker: ${blocker}`}`;panel.dataset.statusView='chat-model'}
function addVersionReceipt(){let foot=$('.sidebar-foot');if(!foot)return;Array.from(foot.children).forEach(el=>{if(el.id==='swrlzHotVersionLine')return;let text=(el.textContent||'').trim();if(el.id==='swrlzVersionLine'||/^CHAT\s+v\d/i.test(text))el.style.display='none'});let line=$('#swrlzHotVersionLine');if(!line){line=document.createElement('div');line.id='swrlzHotVersionLine';line.className='swrlz-version-line';line.dataset.source='hot-runtime';foot.append(line)}line.textContent=`CHAT v${UI_VERSION} · SERVER v…`}
let bar=document.createElement('div');bar.className='swrlz-enhance-bar';bar.innerHTML='<span id="swrlzMode" class="swrlz-mode">LOADING</span><input class="swrlz-search" placeholder="Search threads"><button class="swrlz-tools-toggle" type="button" aria-expanded="false">TOOLS</button><button data-context>CONTEXT</button><button data-controls>GENERATION</button><button data-camera>STREAM CAMERA</button><button data-ops>REFRESH STATE</button>';let workspace=$('.workspace'),top=$('.topbar');if(workspace&&top)top.insertAdjacentElement('afterend',bar);bar.querySelector('.swrlz-search').oninput=e=>searchThreads(e.target.value);let toggle=bar.querySelector('.swrlz-tools-toggle');toggle.onclick=()=>{let open=bar.dataset.expanded==='true';bar.dataset.expanded=open?'false':'true';toggle.setAttribute('aria-expanded',String(!open));toggle.textContent=open?'TOOLS':'CLOSE'};bar.querySelector('[data-context]').onclick=contextInspector;bar.querySelector('[data-controls]').onclick=controls;bar.querySelector('[data-camera]').onclick=streamCamera;bar.querySelector('[data-ops]').onclick=loadOps;repairDrawerStack();addVersionReceipt();settingsUX();statusPanelUX();ensureAdminSession(true).then(()=>{settingsUX();statusPanelUX()});loadOps();setInterval(loadOps,15000);setInterval(()=>{settingsUX();statusPanelUX()},1000);
})();
