(()=>{"use strict";
if(window.__swrlzCommittedOutputV3Installed)return;
window.__swrlzCommittedOutputV3Installed=true;

const baseConsume=typeof consumeEvent==='function'?consumeEvent:null;
if(!baseConsume)return;

const INTERNAL_LABEL_RE=/^(?:Output Budget|Coding Mode|Response Budget|Debugging|Priority|DELTA)\s*:??\s*$/i;
const MAX_RETRIEVED_RE=/\bat\s+most\s+(\d{1,2})\s+(?:retrieved\s+)?(?:older\s+)?messages\b/i;
const RECENT_WINDOW_RE=/\b(?:keep\s+the\s+)?(?:most\s+)?recent\s+(\d{1,3})\s+messages\b/i;
const CODE_REQUEST_RE=/\b(?:complete\s+)?runnable\s+(?:python\s+)?code\b|\bprovide\s+(?:complete\s+)?(?:runnable\s+)?(?:python\s+)?code\b/i;
const EXAMPLE_RE=/\binclude\s+(?:one\s+)?example\b|\bexample\s+conversation\b/i;
const PREFILL_RE=/\bprompt[- ]prefill\b/i;
const LEXICAL_RE=/\blexical\s+relevance\s+score\b/i;
const NO_EXTERNAL_RE=/\bwithout\s+external\s+librar(?:y|ies)\b|\bno\s+external\s+librar(?:y|ies)\b/i;

function priorUserPrompt(context){try{const thread=typeof currentThread==='function'?currentThread():null;if(!thread||!Array.isArray(thread.messages))return '';const index=thread.messages.findIndex(m=>m===context?.message||String(m?.id||'')===String(context?.message?.id||''));for(let i=(index>=0?index-1:thread.messages.length-1);i>=0;i--)if(thread.messages[i]?.role==='user')return String(thread.messages[i].text||'')}catch(_){ }return ''}
function buildLedger(prompt){const text=String(prompt||''),max=MAX_RETRIEVED_RE.exec(text),recent=RECENT_WINDOW_RE.exec(text);return{maxRetrievedOlder:max?Number(max[1]):null,recentWindow:recent?Number(recent[1]):null,requireRunnableCode:CODE_REQUEST_RE.test(text),requirePython:/\bpython\b/i.test(text)&&CODE_REQUEST_RE.test(text),requireExample:EXAMPLE_RE.test(text),requirePrefillExplanation:PREFILL_RE.test(text),userSuppliedPercent:/\b\d+(?:\.\d+)?\s*%/.test(text),asksForLexicalScore:LEXICAL_RE.test(text),noExternalLibraries:NO_EXTERNAL_RE.test(text)}}
function stateFor(context){if(!context.__swrlzCommitStateV3){context.__swrlzCommitStateV3={raw:'',discarded:0,blocked:false,ledger:buildLedger(priorUserPrompt(context)),seenHeadings:new Set(),semanticRejects:[],validCodeCommitted:false,codeRejects:0,committedEvents:0}}return context.__swrlzCommitStateV3}
function addTrace(message,phase,reason){if(!message)return;message.meta=message.meta||{};message.meta.trail=Array.isArray(message.meta.trail)?message.meta.trail:[];const last=message.meta.trail.at(-1);if(last?.reason!==reason)message.meta.trail.push({seq:Number(last?.seq||0)+1,phase,reason,at:Date.now()});if(message.meta.trail.length>100)message.meta.trail.splice(0,message.meta.trail.length-100)}
function reject(st,message,reason,text){st.semanticRejects.push({reason,text:String(text||'').slice(0,220)});if(st.semanticRejects.length>24)st.semanticRejects.shift();st.discarded+=String(text||'').length;addTrace(message,'SEMANTIC_COMMIT_GUARD',reason)}
function cleanControl(text){return String(text||'').split('\n').filter(line=>{const t=line.trim();return !(INTERNAL_LABEL_RE.test(t)||/^Coding Mode:\s*/i.test(t)||/^Debugging:\s*/i.test(t)||/^Response Budget:\s*/i.test(t)||/^Priority:\s*/i.test(t))}).join('\n')}
function degenerate(text){const tail=String(text||'').slice(-900).toLowerCase();if(/(?:\balt\b|alt){8,}/i.test(tail)||/(?:```\s*){4,}/.test(tail))return true;if(/\b(?:delta|deltda|kitt|story|mee)\b(?:[\s.!`]*\b(?:delta|deltda|kitt|story|mee)\b){3,}/i.test(tail))return true;const words=(tail.match(/[a-z]{2,20}/g)||[]).slice(-48);return words.length>=28&&new Set(words).size/words.length<0.24}
function lastSentenceBoundary(text){let best=-1,m;const re=/[.!?](?:["'\)\]]?)(?=\s|$)/g,s=String(text||'');while((m=re.exec(s)))best=re.lastIndex;return best}
function normalizeHeading(line){return String(line||'').trim().replace(/:$/,'').trim().toLowerCase()}
function isHeading(line){return /^(?:Architecture(?: Explanation| Overview)?|Example(?: Conversation)?|Retrieved Older Messages|Retrieved Recent Messages(?: \(most relevant\))?|Output|Explanation|Implementation|Runnable Code|Code|How it works|Prefill(?: Cost)?)(?::)?$/i.test(String(line||'').trim())}
function sanitizeProse(context,text){const st=stateFor(context),message=context?.message,ledger=st.ledger,lines=cleanControl(text).split('\n'),kept=[];for(let line of lines){const t=line.trim();if(!t){kept.push(line);continue}if(isHeading(t)){const key=normalizeHeading(t);if(st.seenHeadings.has(key)){reject(st,message,`Duplicate structural heading “${t}” was rejected before visibility.`,line);continue}st.seenHeadings.add(key);kept.push(line);continue}if(!ledger.userSuppliedPercent&&/\b\d+(?:\.\d+)?\s*%/.test(line)){const original=line;line=line.replace(/\s+by\s+\d+(?:\.\d+)?\s*%/ig,'').replace(/\b\d+(?:\.\d+)?\s*%\b/ig,'an unmeasured amount');reject(st,message,'An unsupported percentage/measurement was removed before visibility.',original)}if(ledger.asksForLexicalScore&&!/\bexample\b/i.test(line)){const original=line;line=line.replace(/\blexical\s+relevance\s+score\s+(?:of|=|:)\s*\d+(?:\.\d+)?\b/ig,'lexical relevance score');if(line!==original)reject(st,message,'A fabricated fixed lexical-score value was removed before visibility.',original)}kept.push(line)}return kept.join('\n')}
function codeBody(block){const first=block.indexOf('\n'),last=block.lastIndexOf('```');return first>=0&&last>first?block.slice(first+1,last):''}
function validateCode(context,block){const st=stateFor(context),l=st.ledger,code=codeBody(block),gaps=[];if(l.requirePython&&!/```\s*(?:python|py)?\s*\n/i.test(block))gaps.push('python-fence');if(l.requirePython&&!/\b(?:def|class|import|from)\b/.test(code))gaps.push('python-structure');if(l.recentWindow!=null){const n=l.recentWindow;const rx=new RegExp(`maxlen\\s*=\\s*${n}\\b|\\[\\s*-${n}\\s*:\\s*\\]|(?:recent|window|limit|max_recent|recent_limit)\\w*\\s*=\\s*${n}\\b`,'i');if(!rx.test(code))gaps.push(`recent-window=${n}-in-code`)}if(l.maxRetrievedOlder!=null){const n=l.maxRetrievedOlder;const rx=new RegExp(`\\[\\s*:\\s*${n}\\s*\\]|(?:max_results|max_retrieved|retrieval_limit|limit|top_k|k)\\w*\\s*=\\s*${n}\\b`,'i');if(!rx.test(code))gaps.push(`retrieved-older<=${n}-in-code`)}if(l.asksForLexicalScore){const score=/def\s+\w*(?:score|relev|rank)\w*\s*\(/i.test(code),tokens=/\b(?:set|split|findall)\s*\(|re\.findall/i.test(code),overlap=/\.intersection\s*\(|\&|\boverlap\b|\bcommon\b/i.test(code);if(!(score&&tokens&&overlap))gaps.push('lexical-score-implementation')}if(l.noExternalLibraries&&/^\s*(?:from|import)\s+(?:numpy|pandas|sklearn|sentence_transformers|torch|tensorflow)\b/im.test(code))gaps.push('no-external-libraries');return gaps}
function commit(context,text){if(!text)return;const st=stateFor(context),message=context?.message,visible=sanitizeProse(context,text);if(!visible)return;baseConsume({type:'DELTA',text:visible},context);st.committedEvents++;annotate(message,st)}
function process(context,terminal=false){const st=stateFor(context),message=context?.message;if(st.blocked)return;while(st.raw){if(degenerate(String(message?.text||'')+st.raw)){reject(st,message,'A malformed/repetitive tail was discarded before visibility.',st.raw);st.raw='';st.blocked=true;break}const open=st.raw.indexOf('```');if(open>=0){const before=st.raw.slice(0,open);if(before)commit(context,before);const close=st.raw.indexOf('```',open+3);if(close<0){if(open>0)st.raw=st.raw.slice(open);break}const block=st.raw.slice(open,close+3);st.raw=st.raw.slice(close+3);const gaps=validateCode(context,block);if(gaps.length){st.codeRejects++;reject(st,message,`Code artifact withheld before visibility because it failed: ${gaps.join(', ')}.`,block);continue}baseConsume({type:'DELTA',text:block},context);st.validCodeCommitted=true;st.committedEvents++;annotate(message,st);continue}if(terminal){const tail=sanitizeProse(context,st.raw);st.raw='';if(tail)baseConsume({type:'DELTA',text:tail},context);break}const para=st.raw.lastIndexOf('\n\n');if(para>=0){const part=st.raw.slice(0,para+2);st.raw=st.raw.slice(para+2);commit(context,part);continue}const sentence=lastSentenceBoundary(st.raw);if(sentence>0){const part=st.raw.slice(0,sentence);st.raw=st.raw.slice(sentence);commit(context,part);continue}break}}
function evaluate(message,st){const l=st.ledger,value=String(message?.text||''),lower=value.toLowerCase(),gaps=[];if(l.requireRunnableCode&&!st.validCodeCommitted)gaps.push('runnable-code');if(l.requireExample&&!lower.includes('example'))gaps.push('example');if(l.requirePrefillExplanation&&!(lower.includes('prefill')&&(lower.includes('prompt')||lower.includes('context'))))gaps.push('prefill-explanation');if(l.recentWindow!=null&&!new RegExp(`(?:recent|window|latest)[^\\n.]{0,100}\\b${l.recentWindow}\\b|\\b${l.recentWindow}\\b[^\\n.]{0,100}(?:recent|window|latest)`,'i').test(value))gaps.push(`recent-window=${l.recentWindow}`);return gaps}
function annotate(message,st){if(!message)return;message.meta=message.meta||{};message.meta.committedOutputV3=true;message.meta.outputVisibilityPolicy='append-only-final-copy-artifact-validated';message.meta.committedChars=String(message.text||'').length;message.meta.stagedChars=st.raw.length;message.meta.discardedStagedChars=st.discarded;message.meta.requirementLedger=st.ledger;message.meta.semanticCommitRejects=st.semanticRejects.slice(-12);message.meta.validatedCodeArtifactCommitted=st.validCodeCommitted;message.meta.codeArtifactRejects=st.codeRejects}

consumeEvent=function(event,context){if(!event||typeof event!=='object')return baseConsume(event,context);const st=stateFor(context),message=context?.message;if(event.type==='DELTA'){if(!st.blocked)st.raw+=String(event.text??'');process(context,false);annotate(message,st);return}if(['COMPLETED','FAILED','CANCELLED'].includes(String(event.type||'')))process(context,true);let next=event;if(event.type==='COMPLETED'){const gaps=evaluate(message,st);message.meta=message.meta||{};message.meta.requirementGaps=gaps;message.meta.requirementLedgerPassed=gaps.length===0;if(gaps.length){next={...event,type:'FAILED',phase:'ERROR',terminal:true,reason:`Final-copy validation found unmet user requirements: ${gaps.join(', ')}. Only semantically accepted committed text was shown.`};addTrace(message,'REQUIREMENT_GUARD',next.reason)}}const result=baseConsume(next,context);annotate(message,st);return result};

window.__swrlzCommittedOutput={version:3,policy:'append-only-final-copy-artifact-validated',description:'Prose commits at coherent boundaries; requested code artifacts remain private until the complete fenced artifact passes requirement-aware validation.'};
})();
