(()=>{"use strict";
const AUTH_ROOT="https://raw.githubusercontent.com/kaministrator999-ui/Swrlzkamico/runtime/",INDEX_URL=`${AUTH_ROOT}VERSION.txt`;
const parseKV=t=>Object.fromEntries(String(t||"").split(/\r?\n/).map(x=>x.trim()).filter(x=>x&&!x.startsWith("#")&&x.includes("=")).map(x=>{const i=x.indexOf("=");return[x.slice(0,i).trim(),x.slice(i+1).trim()]}));
const log=(event,data={})=>{try{window.__swrlzDebug?.log("version-authority",event,data)}catch(_){}};
const fetchText=url=>fetch(`${url}${url.includes("?")?"&":"?"}ts=${Date.now()}`,{cache:"no-store"}).then(r=>r.ok?r.text():Promise.reject(new Error(`HTTP ${r.status} ${url}`)));
const apply=()=>{const foot=document.querySelector(".sidebar-foot");if(!foot)return;let line=document.querySelector("#swrlzChatVersion");if(!line){line=document.createElement("div");line.id="swrlzChatVersion";line.className="swrlz-version-line";line.style.cssText="padding:4px 9px 2px;color:var(--muted);font-size:10px;letter-spacing:.05em;opacity:.9;line-height:1.45;";foot.appendChild(line)}
let modules={},declaredLalmStatus="unknown";
const renderVersions=(m={})=>{const p=Object.entries(m).filter(([,v])=>v?.VERSION).map(([key,v])=>`${v.DISPLAY_NAME||key.replaceAll("_"," ")} v${v.VERSION}`);line.textContent=p.join(" · ")||"Version registry unavailable"};
const loadVersions=async()=>{try{const index=parseKV(await fetchText(INDEX_URL)),keys=Object.keys(index).filter(key=>key!=="REGISTRY_FORMAT"&&String(index[key]||"").startsWith("versions/")),pairs=await Promise.all(keys.map(async key=>{const path=index[key];return[key,parseKV(await fetchText(`${AUTH_ROOT}${path}`))]}));modules=Object.fromEntries(pairs);declaredLalmStatus=String(modules.LALM_ENGINE?.STATUS||"unknown").toLowerCase();renderVersions(modules);window.__swrlzModuleStatusAuthority={index:INDEX_URL,modules,loadedAt:Date.now()};window.dispatchEvent(new CustomEvent("swrlz:module-status",{detail:{module:"lalm-engine",declaredStatus:declaredLalmStatus,version:modules.LALM_ENGINE?.VERSION||""}}));log("registry-ready",{lalmStatus:declaredLalmStatus})}catch(error){line.textContent="Version registry unavailable";log("registry-error",{error:String(error?.message||error)})}};
const els=()=>({title:document.querySelector("#nodeTitle"),detail:document.querySelector("#nodeDetail"),light:document.querySelector("#nodeLight"),pill:document.querySelector("#statusPill"),pillText:document.querySelector("#statusText")});
const paint=(state,detailText="")=>{const{title,detail,light,pill,pillText}=els();if(!title||!detail||!light)return;light.classList.remove("ready","error");pill?.classList.remove("ready","error");const ready=state==="active",error=state==="error";if(ready){light.classList.add("ready");pill?.classList.add("ready")}if(error){light.classList.add("error");pill?.classList.add("error")}const map={active:["LALM active","Local LALM active","R39 ready · native backend"],preparing:["LALM preparing","Local LALM preparing","R39 is initializing"],maintenance:["LALM maintenance","Local LALM maintenance","Temporarily unavailable for maintenance"],disabled:["LALM disabled","Local LALM disabled","Disabled by module authority"],error:["LALM unavailable","Local LALM unavailable",detailText||"Check LALM status"],unknown:["LALM status unknown","Local LALM status unknown",detailText||"Status authority unavailable"]},v=map[state]||map.unknown;if(pillText)pillText.textContent=v[0];title.textContent=v[1];detail.textContent=v[2];document.documentElement.dataset.swrlzLalmState=state;window.__swrlzLalmState={state,declaredStatus:declaredLalmStatus,detail:detailText,at:Date.now()};window.dispatchEvent(new CustomEvent("swrlz:lalm-state",{detail:window.__swrlzLalmState}))};
const normalize=(declared,s)=>{declared=String(declared||"unknown").toLowerCase();if(["disabled","maintenance"].includes(declared))return declared;if(declared!=="active")return declared==="preparing"?"preparing":"unknown";const r=s?.readiness||{},engine=s?.engine||{};if(r.ok===false||engine.available===false)return"error";if(r.interactiveReady===true)return"active";/* Successful hot hydration is active even when legacy readiness fields lag. */if(engine.available===true||String(engine.hotServerVersion||engine.version||"").trim())return"active";return"preparing"};
const paintLalm=async()=>{try{if(!modules.LALM_ENGINE)await loadVersions();if(["disabled","maintenance"].includes(declaredLalmStatus)){paint(declaredLalmStatus);return}const r=await fetch(`/api/lalm/status?ts=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const s=await r.json(),state=normalize(declaredLalmStatus,s),d=String(s?.readiness?.detail||s?.readiness?.code||s?.engine?.error||"");paint(state,d);log("lalm-state",{declared:declaredLalmStatus,observed:state,interactiveReady:Boolean(s?.readiness?.interactiveReady),engineAvailable:s?.engine?.available})}catch(e){paint(declaredLalmStatus==="active"?"error":"unknown","LALM status unavailable");log("lalm-status-fetch-error",{error:String(e?.message||e)})}};
const reconcileLegacyBridgePainter=()=>{const legacy=window.paintStatus;if(typeof legacy!=="function"||legacy.__swrlzLalmStatusReconciled)return;const reconciled=function(...args){const result=legacy.apply(this,args),snapshot=window.__swrlzLalmState;if(snapshot?.state)paint(snapshot.state,snapshot.detail||"");else queueMicrotask(()=>paintLalm());return result};reconciled.__swrlzLalmStatusReconciled=true;reconciled.__swrlzLegacyBridgePainter=legacy;window.paintStatus=reconciled;window.__swrlzLalmStatusPaintOwner={owner:"chat_version.js",legacyBridgePainter:"compatibility-only",installedAt:Date.now()};log("legacy-status-writer-reconciled",{canonicalOwner:"chat_version.js",legacyRole:"bridge-settings-compatibility"})};
(async()=>{reconcileLegacyBridgePainter();paint("unknown","Loading module authority");await loadVersions();await paintLalm()})();window.setInterval(paintLalm,60000);window.addEventListener("focus",async()=>{await loadVersions();paintLalm()});document.addEventListener("visibilitychange",()=>{if(!document.hidden){loadVersions().then(paintLalm)}})};
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",apply,{once:true});else apply();})();
