(()=>{"use strict";
if(window.__swrlzImmediateActivityInstalled)return;
window.__swrlzImmediateActivityInstalled=true;
const priorFetch=window.fetch.bind(window);
const baseRenderMessage=typeof renderMessage==='function'?renderMessage:null;
function streamUrl(input){try{return typeof input==='string'?input:(input?.url||'')}catch(_){return ''}}
function isStream(input,init){const method=String(init?.method||input?.method||'GET').toUpperCase();return method==='POST'&&/(?:[?&]action=stream(?:&|$)|\/stream(?:[?#]|$))/i.test(streamUrl(input))}
function parseBody(init){if(typeof init?.body!=='string')return null;try{return JSON.parse(init.body)}catch(_){return null}}
function isLive(message){return message?.role==='assistant'&&(message?.state==='streaming'||message?.state==='cancelling')}
function phaseText(message){try{return typeof phaseLabel==='function'?phaseLabel(message?.meta?.phase||'ANALYZING_REQUEST'):'Analyzing request'}catch(_){return 'Analyzing request'}}
function findMessage(id){try{const key=String(id||'');if(!key)return null;for(const thread of state?.threads||[]){const message=thread?.messages?.find?.(m=>String(m?.id||'')===key);if(message)return message}return null}catch(_){return null}}
function ensureModel(message){try{if(!message||message?.role!=='assistant')return false;message.meta=message.meta||{};message.meta.trail=Array.isArray(message.meta.trail)?message.meta.trail:[];if(isLive(message)&&!message.meta.trail.length)message.meta.trail.push({seq:0,phase:message.meta.phase||'ANALYZING_REQUEST',reason:'Preparing the canonical request locally.',at:Date.now()});if(typeof message.meta.activityExpanded!=='boolean')message.meta.activityExpanded=isLive(message);return true}catch(_){return false}}
function syncTrace(article,message){try{if(!article||!ensureModel(message))return article;const body=article.querySelector('.message-body');if(!body)return article;let trace=body.querySelector(':scope > details.trace');if(!trace&&isLive(message)){trace=document.createElement('details');trace.className='trace swrlz-live-trace';trace.append(document.createElement('summary'),Object.assign(document.createElement('div'),{className:'trace-list'}));const bubble=body.querySelector(':scope > .bubble'),actions=body.querySelector(':scope > .message-actions');if(bubble)body.insertBefore(trace,bubble);else if(actions)body.insertBefore(trace,actions);else body.append(trace)}if(!trace)return article;trace.open=Boolean(message.meta.activityExpanded);const summary=trace.querySelector('summary');if(summary)summary.textContent=`Activity log · ${phaseText(message)}`;const list=trace.querySelector('.trace-list');if(list){const recent=(message.meta.trail||[]).slice(-12),sig=recent.map(x=>`${x?.phase||''}\u0000${x?.reason||''}`).join('\u0001');if(list.dataset.activitySignature!==sig){list.dataset.activitySignature=sig;const frag=document.createDocumentFragment();for(const step of recent){const item=document.createElement('div');item.className='trace-item';const label=typeof phaseLabel==='function'?phaseLabel(step?.phase):String(step?.phase||'Activity');item.textContent=step?.reason?`${label} — ${step.reason}`:label;frag.append(item)}list.replaceChildren(frag)}}return article}catch(_){return article}}
function articleMessage(article){return findMessage(article?.dataset?.messageId)}
function syncArticle(article){if(!article?.matches?.('.message.assistant'))return;const message=articleMessage(article);if(message)syncTrace(article,message)}
function syncAll(root=document){try{if(root.matches?.('.message.assistant'))syncArticle(root);root.querySelectorAll?.('.message.assistant').forEach(syncArticle)}catch(_){}}
function commit(trace,next){try{const article=trace?.closest?.('.message.assistant'),message=articleMessage(article);if(!message)return;ensureModel(message);message.meta.activityExpanded=Boolean(next);trace.open=Boolean(next);saveState()}catch(_){}}
if(baseRenderMessage){renderMessage=function(message){ensureModel(message);return syncTrace(baseRenderMessage(message),message)}}
function onActivate(event){const summary=event.target?.closest?.('details.trace > summary');if(!summary)return;const trace=summary.parentElement;if(!trace?.matches?.('details.trace'))return;event.preventDefault();event.stopPropagation();commit(trace,!trace.open)}
document.addEventListener('click',onActivate,true);
document.addEventListener('keydown',event=>{if(event.key!=='Enter'&&event.key!==' ')return;const summary=event.target?.closest?.('details.trace > summary');if(!summary)return;event.preventDefault();event.stopPropagation();commit(summary.parentElement,!summary.parentElement.open)},true);
document.addEventListener('toggle',event=>{const trace=event.target;if(!trace?.matches?.('details.trace'))return;const article=trace.closest('.message.assistant'),message=articleMessage(article);if(!message)return;ensureModel(message);if(trace.open!==Boolean(message.meta.activityExpanded))trace.open=Boolean(message.meta.activityExpanded)},true);
const observer=new MutationObserver(records=>{for(const record of records){for(const node of record.addedNodes||[]){if(node.nodeType===1)syncAll(node)}}});
function bootObserver(){const stack=document.querySelector('#messageStack');if(stack&&!stack.dataset.swrlzActivityOwner){stack.dataset.swrlzActivityOwner='delegated-v2';observer.observe(stack,{childList:true,subtree:true});syncAll(stack)}}
function seed(message){try{if(!ensureModel(message))return false;if(isLive(message)&&!message.meta.phase)message.meta.phase='ANALYZING_REQUEST';try{saveState()}catch(_){};if(typeof render==='function')render(false);else if(typeof scheduleRender==='function')scheduleRender(false);return true}catch(_){return false}}
function latestStreaming(){try{if(typeof currentThread!=='function')return null;const thread=currentThread();if(!thread?.messages)return null;return[...thread.messages].reverse().find(m=>isLive(m))||null}catch(_){return null}}
function mark(payload){try{const rid=String(payload?.requestId||'');if(!rid||typeof currentThread!=='function')return;const thread=currentThread();if(!thread?.messages)return;const message=[...thread.messages].reverse().find(m=>m?.role==='assistant'&&String(m?.meta?.requestId||'')===rid);seed(message)}catch(_){}}
document.addEventListener('submit',event=>{try{const form=event.target;if(!(form instanceof HTMLFormElement)||form.id!=='composer')return;queueMicrotask(()=>seed(latestStreaming()))}catch(_){}},true);
window.fetch=function(input,init={}){if(isStream(input,init)){const payload=parseBody(init);if(payload)mark(payload);else queueMicrotask(()=>seed(latestStreaming()))}return priorFetch(input,init)};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootObserver,{once:true});else bootObserver();
})();
