(()=>{"use strict";
if(window.__swrlzRuntimeLoaderV3)return;
const REV=(()=>{try{return new URL(document.currentScript?.src||'',location.href).searchParams.get('v')||'95'}catch(_){return '95'}})(),ROOT='/live/assets/';
const diagnostics={contractId:'swrlz_chat_cooperative_boot_v3',revision:REV,startedAt:performance.now(),critical:[],functional:[],decorative:[],styleErrors:[],scriptErrors:[],timeouts:[],mainReady:false,functionalReady:false,decorativeReady:false,themeSettled:false,stage:'loader-start'};window.__swrlzRuntimeLoaderV3=diagnostics;
const dbg=(t,m,d)=>{try{window.__swrlzDebug?.log(t,m,d)}catch(_){ }};
const stage=(name,data)=>{diagnostics.stage=name;diagnostics.stageAt=performance.now();try{document.documentElement.dataset.swrlzBootStage=name}catch(_){ }dbg('boot','boot-stage',{stage:name,revision:REV,...(data||{})})};
const failOpen=(reason,data)=>{diagnostics.failOpenReason=reason;diagnostics.failOpenAt=performance.now();document.documentElement.classList.remove('swrlz-visual-booting');document.documentElement.classList.add('swrlz-main-chat-ready','swrlz-visual-ready');stage('fail-open',{reason,...(data||{})})};
window.addEventListener('error',e=>dbg('error','loader-window-error',{stage:diagnostics.stage,message:e.message,source:e.filename,line:e.lineno,column:e.colno}),true);window.addEventListener('unhandledrejection',e=>dbg('error','loader-unhandled-rejection',{stage:diagnostics.stage,reason:String(e.reason?.message||e.reason||'unknown')}));
const bootWatchdog=setTimeout(()=>{if(!diagnostics.functionalReady)failOpen('boot-watchdog',{stage:diagnostics.stage,critical:[...diagnostics.critical],functional:[...diagnostics.functional],scriptErrors:[...diagnostics.scriptErrors],styleErrors:[...diagnostics.styleErrors],timeouts:[...diagnostics.timeouts]})},12000);
stage('loader-start');
const ua=navigator.userAgent||'',isAndroid=/Android/i.test(ua),isEdgeAndroid=isAndroid&&(/\bEdgA\//i.test(ua)||/\bEdg\//i.test(ua));if(isAndroid)document.documentElement.classList.add('swrlz-android-device');if(isEdgeAndroid)document.documentElement.classList.add('swrlz-edge-android');
const physicalViewportWidth=()=>{const vv=window.visualViewport;const layoutW=Math.max(1,Math.round(document.documentElement.clientWidth||window.innerWidth||1));const visualCssW=Math.max(1,Math.round(vv?.width||window.innerWidth||layoutW));const screenCssW=Math.max(1,Math.round(screen?.availWidth||screen?.width||visualCssW));return Math.min(layoutW,visualCssW,screenCssW)};
const syncViewport=()=>{if(!isAndroid)return;const vv=window.visualViewport;const visualH=Math.max(1,Math.round(vv?.height||window.innerHeight||document.documentElement.clientHeight||1));const layoutH=Math.max(visualH,Math.round(document.documentElement.clientHeight||window.innerHeight||visualH));const w=physicalViewportWidth();const top=Math.max(0,Math.round(vv?.offsetTop||0));const left=Math.max(0,Math.round(vv?.offsetLeft||0));const focused=document.activeElement;const editable=!!focused&&(focused.matches?.('textarea,input,[contenteditable="true"]')||focused.isContentEditable);const edgeImeCompensated=isEdgeAndroid&&editable&&(layoutH-visualH>64);const h=edgeImeCompensated?layoutH:visualH;const imeOpen=editable&&(layoutH-visualH>80||Math.round(screen?.height||0)-visualH>220);document.documentElement.classList.toggle('swrlz-ime-open',!!imeOpen);document.documentElement.classList.toggle('swrlz-edge-ime-layout',!!edgeImeCompensated);document.documentElement.style.setProperty('--swrlz-vvh',`${h}px`);document.documentElement.style.setProperty('--swrlz-vvw',`${w}px`);document.documentElement.style.setProperty('--swrlz-vv-top',`${top}px`);document.documentElement.style.setProperty('--swrlz-vv-left',`${left}px`);diagnostics.viewport={height:h,rawVisualHeight:visualH,width:w,top,left,imeOpen,edgeImeCompensated,layoutHeight:layoutH,innerHeight:window.innerHeight,innerWidth:window.innerWidth,visualWidth:Math.round(vv?.width||0),visualHeight:Math.round(vv?.height||0),visualOffsetLeft:Math.round(vv?.offsetLeft||0),visualOffsetTop:Math.round(vv?.offsetTop||0),visualPageLeft:Math.round(vv?.pageLeft||0),visualPageTop:Math.round(vv?.pageTop||0),screenWidth:Math.round(screen?.width||0),screenHeight:Math.round(screen?.height||0)}};syncViewport();window.visualViewport?.addEventListener('resize',syncViewport,{passive:true});window.visualViewport?.addEventListener('scroll',syncViewport,{passive:true});window.addEventListener('resize',syncViewport,{passive:true});window.addEventListener('orientationchange',()=>setTimeout(syncViewport,60),{passive:true});document.addEventListener('focusin',()=>setTimeout(syncViewport,40),true);document.addEventListener('focusout',()=>setTimeout(syncViewport,80),true);
const styles=['chat_boot_guard.css','chat_enhancements.css','chat_user_settings_v2.css','themes/ice-dragon/ice-dragon-theme.css','themes/ice-dragon/ice-dragon-art-v2.css','themes/ice-dragon/ice-dragon-shell-v1.css','themes/ice-dragon/ice-dragon-brand-v1.css','themes/ice-dragon/ice-dragon-polish-v2.css','themes/ice-dragon/ice-dragon-response-layout-v1.css','chat_mobile_viewport_fix.css','chat_code_artifacts.css'];
const critical=['chat_debug_log_v1.js','chat_drawer_layer_v1.js','chat_transport_boundary_v1.js','chat_frontend_boot_v2.js','chat_boot_guard.js','chat_version.js','chat_boot_ready.js'];
const functional=['chat_admin_session.js','chat_enhancements.js','chat_google_server_config.js','themes/ice-dragon/ice-dragon-theme-v3.2.js','chat_account_identity_v1.js','chat_user_settings_v2.js','chat_stream_focus.js','chat_stream_incremental.js','chat_committed_contract_bridge.js','chat_committed_output_v3.js','chat_activity_immediate.js','chat_user_time_context.js','chat_context_canonical.js','chat_background_resume_v2.js','chat_response_presence.js','chat_terminal_integrity.js','chat_context_capacity.js','chat_context_camera.js','chat_response_polish.js','chat_turn_integrity_v1.js','chat_response_layout_v1.js','chat_thread_brand_v1.js','chat_theme_settings_v1.js','chat_scroll_gesture_v1.js','chat_code_artifacts.js'];const themeSettlement='themes/ice-dragon/ice-dragon-art-loader-v17.js',wallpaper='themes/ice-dragon/ice-dragon-wallpaper-v22.js';
const src=p=>`${ROOT}${p}?v=${REV}`;
function establishInitialTheme(){let saved='';try{saved=localStorage.getItem('swrlz.chat.theme')||''}catch(_){ }const initial=saved==='default'?'default':'ice-dragon';if(initial==='ice-dragon')document.body.dataset.swrlzTheme='ice-dragon';else delete document.body.dataset.swrlzTheme;diagnostics.initialTheme=initial;stage('theme-established',{theme:initial})}
function loadStyle(path){return new Promise(resolve=>{if(document.querySelector(`link[data-swrlz-runtime-style="${CSS.escape(path)}"]`))return resolve(path);const link=document.createElement('link');link.rel='stylesheet';link.href=src(path);link.dataset.swrlzRuntimeStyle=path;const done=kind=>{if(kind==='error')diagnostics.styleErrors.push(path);dbg(kind==='load'?'asset':'error',`style-${kind}`,{path,stage:diagnostics.stage});resolve(path)};link.addEventListener('load',()=>done('load'),{once:true});link.addEventListener('error',()=>done('error'),{once:true});document.head.appendChild(link)})}
function startStyles(){stage('styles-start',{count:styles.length});return Promise.all(styles.map(loadStyle))}
function loadOne(path,bucket,timeoutMs=5000){return new Promise(resolve=>{if(document.querySelector(`script[data-swrlz-runtime-script="${CSS.escape(path)}"]`))return resolve();let settled=false;stage(`script:${path}:start`);dbg('asset','script-start',{path,stage:diagnostics.stage});const done=kind=>{if(settled)return;settled=true;clearTimeout(timer);if(kind==='load')bucket?.push(path);if(kind==='error')diagnostics.scriptErrors.push(path);if(kind==='timeout')diagnostics.timeouts.push(path);dbg(kind==='load'?'asset':'error',`script-${kind}`,{path,stage:diagnostics.stage});stage(`script:${path}:${kind}`);resolve()};const script=document.createElement('script');script.src=src(path);script.async=false;script.dataset.swrlzRuntimeScript=path;script.addEventListener('load',()=>done('load'),{once:true});script.addEventListener('error',()=>done('error'),{once:true});const timer=setTimeout(()=>done('timeout'),timeoutMs);document.body.appendChild(script)})}
async function loadSerial(paths,bucket){for(const path of paths)await loadOne(path,bucket)}
async function settleTheme(){stage('theme-settlement-start');await loadOne(themeSettlement,diagnostics.decorative,5000);try{await Promise.resolve(window.__swrlzIceDragonArtReady)}catch(error){diagnostics.scriptErrors.push(`${themeSettlement}:settle`);dbg('error','theme-settle-error',{message:String(error?.message||error)})}try{await Promise.resolve(window.IceDragonAssets?.ensure?.())}catch(error){dbg('error','theme-ensure-error',{message:String(error?.message||error)})}try{window.IceDragonWallpaperV22?.paint?.()}catch(error){dbg('error','wallpaper-paint-error',{message:String(error?.message||error)})}diagnostics.themeSettled=true;diagnostics.themeSettledAt=performance.now();document.documentElement.classList.add('swrlz-theme-settled');stage('theme-settled')}
function geometrySnapshot(reason){const pick=(selector)=>{const el=document.querySelector(selector);if(!el)return null;const r=el.getBoundingClientRect();const c=getComputedStyle(el);return{selector,left:Math.round(r.left),right:Math.round(r.right),top:Math.round(r.top),bottom:Math.round(r.bottom),width:Math.round(r.width),height:Math.round(r.height),display:c.display,visibility:c.visibility,opacity:c.opacity,zIndex:c.zIndex,position:c.position,pointerEvents:c.pointerEvents}};const data={reason,stage:diagnostics.stage,htmlClass:document.documentElement.className,bodyClass:document.body?.className||'',theme:document.body?.dataset?.swrlzTheme||'',viewport:diagnostics.viewport||null,document:{clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,bodyClientWidth:document.body?.clientWidth,bodyScrollWidth:document.body?.scrollWidth},elements:['.app','.workspace','.topbar','.messages','.message-stack','.composer-shell','.sidebar','.sidebar-scrim'].map(pick).filter(Boolean)};diagnostics.lastGeometry=data;dbg('layout','geometry-snapshot',data);return data}
async function boot(){stage('boot-enter');establishInitialTheme();document.documentElement.classList.add('swrlz-visual-booting');geometrySnapshot('boot-enter');const styleReady=startStyles();const wallpaperReady=loadOne(wallpaper,diagnostics.decorative,4000);stage('critical-start',{count:critical.length});await loadSerial(critical,diagnostics.critical);diagnostics.mainReady=true;diagnostics.mainReadyAt=performance.now();document.documentElement.classList.add('swrlz-main-chat-ready');stage('critical-complete',{loaded:[...diagnostics.critical],errors:[...diagnostics.scriptErrors],timeouts:[...diagnostics.timeouts]});window.dispatchEvent(new CustomEvent('swrlz:main-chat-ready',{detail:{revision:REV,at:diagnostics.mainReadyAt}}));const functionalReady=loadSerial(functional,diagnostics.functional);stage('functional-start',{count:functional.length});await Promise.all([functionalReady,styleReady,wallpaperReady]);stage('functional-assets-complete',{loaded:diagnostics.functional.length});await settleTheme();syncViewport();diagnostics.functionalReady=true;diagnostics.functionalReadyAt=performance.now();clearTimeout(bootWatchdog);document.documentElement.classList.add('swrlz-chat-functional-ready');window.dispatchEvent(new CustomEvent('swrlz:chat-functional-ready',{detail:{revision:REV,errors:[...diagnostics.scriptErrors],timeouts:[...diagnostics.timeouts],at:diagnostics.functionalReadyAt}}));requestAnimationFrame(()=>requestAnimationFrame(()=>{syncViewport();geometrySnapshot('before-visual-ready');document.documentElement.classList.remove('swrlz-visual-booting');document.documentElement.classList.add('swrlz-visual-ready');diagnostics.decorativeReady=true;diagnostics.decorativeReadyAt=performance.now();document.documentElement.classList.add('swrlz-chat-decorative-ready');stage('visual-ready',{critical:diagnostics.critical.length,functional:diagnostics.functional.length,styles:styles.length,themeSettled:diagnostics.themeSettled});geometrySnapshot('visual-ready');window.dispatchEvent(new CustomEvent('swrlz:chat-decorative-ready',{detail:{revision:REV,errors:[...diagnostics.scriptErrors],timeouts:[...diagnostics.timeouts],at:diagnostics.decorativeReadyAt}}))}))}
boot().catch(error=>{diagnostics.fatal=String(error?.message||error);failOpen('boot-fatal',{message:diagnostics.fatal,stack:error?.stack});geometrySnapshot('boot-fatal');console.error('[§wyrlz cooperative chat boot]',error)});})();