(()=>{"use strict";
if(window.__swrlzCommittedOutputV3Installed)return;
window.__swrlzCommittedOutputV3Installed=true;
const baseConsume=typeof consumeEvent==='function'?consumeEvent:null;if(!baseConsume)return;
function stateFor(context){if(!context.__swrlzCommitStateV4)context.__swrlzCommitStateV4={raw:'',committedEvents:0};return context.__swrlzCommitStateV4}
function lastSentenceBoundary(text){let best=-1,m;const re=/[.!?](?:["'\)\]]?)(?=\s|$)/g,s=String(text||'');while((m=re.exec(s)))best=re.lastIndex;return best}
function annotate(message,st){if(!message)return;message.meta=message.meta||{};message.meta.committedOutputV4=true;message.meta.outputVisibilityPolicy='append-only-coherent-boundaries-presentation-only';message.meta.committedChars=String(message.text||'').length;message.meta.stagedChars=st.raw.length;message.meta.semanticValidationOwner='lalm'}
function commit(context,text){if(!text)return;const st=stateFor(context);baseConsume({type:'DELTA',text:String(text)},context);st.committedEvents++;annotate(context?.message,st)}
function process(context,terminal=false){const st=stateFor(context);while(st.raw){const open=st.raw.indexOf('```');if(open>=0){if(open>0){commit(context,st.raw.slice(0,open));st.raw=st.raw.slice(open);continue}const close=st.raw.indexOf('```',3);if(close<0){if(terminal){commit(context,st.raw);st.raw=''}break}const block=st.raw.slice(0,close+3);st.raw=st.raw.slice(close+3);commit(context,block);continue}if(terminal){commit(context,st.raw);st.raw='';break}const para=st.raw.lastIndexOf('\n\n');if(para>=0){const part=st.raw.slice(0,para+2);st.raw=st.raw.slice(para+2);commit(context,part);continue}const sentence=lastSentenceBoundary(st.raw);if(sentence>0){const part=st.raw.slice(0,sentence);st.raw=st.raw.slice(sentence);commit(context,part);continue}break}}
consumeEvent=function(event,context){if(!event||typeof event!=='object')return baseConsume(event,context);const st=stateFor(context);if(event.type==='DELTA'){st.raw+=String(event.text??'');process(context,false);annotate(context?.message,st);return}if(['COMPLETED','FAILED','CANCELLED'].includes(String(event.type||'')))process(context,true);const result=baseConsume(event,context);annotate(context?.message,st);return result};
window.__swrlzCommittedOutput={version:4,policy:'append-only-coherent-boundaries-presentation-only',description:'Chat only stages coherent presentation boundaries and complete fenced artifacts when possible. It does not interpret user requirements, judge semantics, rewrite model claims, validate code meaning, or change terminal success/failure. Those responsibilities belong to the LALM/server.'};
})();