(()=>{"use strict";
const STREAM_UI_VERSION='1.3.32';
const DRAFT_IDLE_MS=450,DRAFT_MIN_CHARS=4;
let viewportEventType='',draftTimer=0,draftSeq=0,lastDraftText='';
const draftDiag=[];
function diag(type,text){const row={at:new Date().toISOString().slice(11,23),type,text};draftDiag.push(row);if(draftDiag.length>80)draftDiag.shift();window.__SWRLZ_DRAFT_DIAG__=draftDiag.slice();try{console.debug('[§wyrlz]',type,text)}catch(_){};if(refs?.composerHint&&!active)refs.composerHint.textContent=`${type.replaceAll('_',' ')} · ${text}`;}
function activeArticle(){const m=typeof activeMessage==='function'?activeMessage():null;if(!m)return null;return refs?.stack?.querySelector?.(`[data-message-id="${CSS.escape(m.id)}"]`)||null;}
function focusGeneratedTail(force=false){const article=activeArticle();if(!article||!refs?.messages)return;const trace=article.querySelector('.trace');if(trace?.open){refs.messages.scrollTop=refs.messages.scrollHeight;return;}if(!force&&viewportEventType!=='DELTA'&&viewportEventType!=='RESET')return;const bubble=article.querySelector('.bubble');if(!bubble)return;const viewport=refs.messages.getBoundingClientRect(),rect=bubble.getBoundingClientRect(),delta=rect.bottom-(viewport.bottom-12);if(Math.abs(delta)>1)refs.messages.scrollTop+=delta;}
scheduleRender=function(scroll=false){if(renderQueued)return;renderQueued=true;requestAnimationFrame(()=>{renderQueued=false;render(false);if(scroll)requestAnimationFrame(()=>focusGeneratedTail(false));});};
const focusBaseRenderMessage=renderMessage;
renderMessage=function(message){const article=focusBaseRenderMessage(message);if(message?.role!=='assistant')return article;message.meta=message.meta||{};const body=article.querySelector('.message-body'),bubble=article.querySelector('.bubble'),trace=article.querySelector('.trace');if(trace&&body&&bubble){trace.open=Boolean(message.meta.activityExpanded);const summary=trace.querySelector('summary');if(summary&&!String(summary.textContent||'').startsWith('Activity log'))summary.textContent=`Activity log · ${summary.textContent||'runtime'}`;trace.addEventListener('toggle',()=>{message.meta.activityExpanded=trace.open;saveState();if(trace.open)requestAnimationFrame(()=>{refs.messages.scrollTop=refs.messages.scrollHeight;});else requestAnimationFrame(()=>focusGeneratedTail(true));});body.insertBefore(trace,bubble);}if(body&&bubble){const actions=body.querySelector('.message-actions'),evidence=body.querySelector('.swrlz-evidence');if(actions)body.insertBefore(actions,bubble);if(evidence)body.insertBefore(evidence,bubble);}return article;};
const focusBaseConsume=consumeEvent;
consumeEvent=function(event,context){viewportEventType=String(event?.type||'');return focusBaseConsume(event,context);};
function draftHistory(){const t=currentThread();return (t?.messages||[]).filter(m=>m?.text&&['user','assistant'].includes(m.role)).slice(-32).map(m=>({role:m.role,text:String(m.text).slice(0,2000)}));}
function explicitSessionHeader(){const value=(sessionStorage.getItem('swrlz.vercel.chat.admin-session.v1')||'').trim();return value?{'X-SWRLZ-Chat-Session':value}:{};}
async function prefillDraft(text,seq){const t=currentThread();if(!t?.id||seq!==draftSeq||active)return;const started=performance.now();diag('DRAFT_PREFILL_START',`chars=${text.length} · idle=${DRAFT_IDLE_MS}ms`);try{const r=await window.fetch('/api/chat/draft-prefill',{method:'POST',headers:{'Content-Type':'application/json',...explicitSessionHeader()},credentials:'same-origin',cache:'no-store',body:JSON.stringify({threadId:t.id,draft:text,history:draftHistory(),profileId:refs?.route?.value||''})});let j={};try{j=await r.json()}catch(_){}if(seq!==draftSeq)return;if(r.ok&&j.ok){lastDraftText=text;diag('DRAFT_PREFILL_READY',`chars=${text.length} · tokens=${j.draftTokens??'—'} · reused=${j.reusedTokens??'—'} · computed=${j.prefilledTokens??'—'} · shared=${j.sharedDraftCommitted===true?'yes':'no'} · ${j.elapsedMs??Math.round(performance.now()-started)}ms`);}else diag('DRAFT_PREFILL_SKIPPED',`${j.code||'HTTP_'+r.status} · ${j.detail||'not ready'}`);}catch(error){if(seq===draftSeq)diag('DRAFT_PREFILL_FAILED',String(error?.message||error));}}
function scheduleDraftPrefill(){clearTimeout(draftTimer);const text=String(refs?.prompt?.value||'').trim();draftSeq++;const seq=draftSeq;if(active||text.length<DRAFT_MIN_CHARS||text===lastDraftText)return;draftTimer=setTimeout(()=>prefillDraft(text,seq),DRAFT_IDLE_MS);}
if(refs?.prompt){refs.prompt.addEventListener('input',scheduleDraftPrefill,{passive:true});refs.prompt.addEventListener('blur',scheduleDraftPrefill,{passive:true});}
function stampVersion(){for(const el of [document.querySelector('#swrlzHotVersionLine'),document.querySelector('#nodeDetail')])if(el)el.textContent=String(el.textContent||'').replace(/CHAT v\d+\.\d+\.\d+/i,`CHAT v${STREAM_UI_VERSION}`).replace(/Chat v\d+\.\d+\.\d+/i,`Chat v${STREAM_UI_VERSION}`);}
new MutationObserver(stampVersion).observe(document.body,{subtree:true,childList:true,characterData:true});
const style=document.createElement('style');style.textContent=`.message.assistant .trace summary{user-select:none}.message.assistant .trace:not([open]) .trace-list{display:none}.message.assistant[data-stream-tail="true"] .bubble{scroll-margin-bottom:12px}`;document.head.append(style);
render(false);stampVersion();diag('DRAFT_PREFILL_ARMED',`Chat ${STREAM_UI_VERSION} · idle ${DRAFT_IDLE_MS}ms · same-origin authenticated endpoint`);
})();
