(()=>{"use strict";
if(window.__swrlzIncrementalStreamRenderInstalled)return;
window.__swrlzIncrementalStreamRenderInstalled=true;

const baseRenderMessage=renderMessage;
const baseSaveState=saveState;
let pendingSave=false,saveTimer=0,lastRenderedHeight=null,pendingScroll=false;
const LIVE_NAMES={cpp:'main.cpp',cxx:'main.cpp','c++':'main.cpp',c:'main.c',h:'main.h',hpp:'main.hpp',html:'index.html',css:'styles.css',javascript:'script.js',js:'script.js',typescript:'app.ts',ts:'app.ts',jsx:'App.jsx',tsx:'App.tsx',python:'main.py',py:'main.py',java:'Main.java',kotlin:'Main.kt',kt:'Main.kt',json:'data.json',yaml:'config.yaml',yml:'config.yml',markdown:'README.md',md:'README.md',bash:'script.sh',shell:'script.sh',sh:'script.sh',sql:'query.sql',go:'main.go',rust:'main.rs',rs:'main.rs'};

function activeStreamMessage(){try{return typeof activeMessage==='function'?activeMessage():null}catch(_){return null}}
function activeArticle(message){if(!message||!refs?.stack)return null;try{return refs.stack.querySelector(`[data-message-id="${CSS.escape(String(message.id||''))}"]`)}catch(_){return null}}
function flushSave(){if(saveTimer){clearTimeout(saveTimer);saveTimer=0}if(!pendingSave)return;pendingSave=false;try{baseSaveState()}catch(_){}}
saveState=function(){const message=activeStreamMessage();if(!message){flushSave();return baseSaveState()}pendingSave=true;if(!saveTimer)saveTimer=setTimeout(flushSave,700)};
renderMessage=function(message){const article=baseRenderMessage(message);if(article)article.dataset.messageState=String(message?.state||'');return article};
function followEnabled(){return refs?.messages?.dataset?.streamFollow==='true'}
function centerTailLine(article){if(!followEnabled()||!refs?.messages||!article)return;const bubble=article.querySelector('.bubble');if(!bubble)return;const viewport=refs.messages.getBoundingClientRect(),rect=bubble.getBoundingClientRect(),height=Math.ceil(rect.height),style=getComputedStyle(bubble),line=parseFloat(style.lineHeight),font=parseFloat(style.fontSize)||16,lineHeight=Number.isFinite(line)?line:font*1.5;const lineAdvanced=lastRenderedHeight==null||Math.abs(height-lastRenderedHeight)>=Math.max(4,lineHeight*.45);if(!lineAdvanced)return;lastRenderedHeight=height;const target=viewport.top+viewport.height*.52,delta=rect.bottom-target;if(Math.abs(delta)>1)refs.messages.scrollTop+=delta}
function phaseText(message){try{return typeof phaseLabel==='function'?phaseLabel(message?.meta?.phase||'CONNECTING'):'Preparing response'}catch(_){return 'Preparing response'}}
function updateLiveActivity(article,message){const body=article?.querySelector('.message-body');if(!body)return;const trail=Array.isArray(message?.meta?.trail)?message.meta.trail:[];if(!trail.length)return;let details=body.querySelector(':scope > details.trace');if(!details){details=document.createElement('details');details.className='trace swrlz-live-trace';details.open=true;details.append(document.createElement('summary'),Object.assign(document.createElement('div'),{className:'trace-list'}));const actions=body.querySelector(':scope > .message-actions');if(actions)body.insertBefore(details,actions);else body.append(details)}details.open=true;const summary=details.querySelector('summary');if(summary)summary.textContent=`Activity log · ${phaseText(message)}`;const list=details.querySelector('.trace-list');if(list){const recent=trail.slice(-12),signature=recent.map(x=>`${x.phase||''}\u0000${x.reason||''}`).join('\u0001');if(list.dataset.signature!==signature){list.dataset.signature=signature;const frag=document.createDocumentFragment();for(const step of recent){const item=document.createElement('div');item.className='trace-item';const label=typeof phaseLabel==='function'?phaseLabel(step.phase):String(step.phase||'Activity');item.textContent=step.reason?`${label} — ${step.reason}`:label;frag.append(item)}list.replaceChildren(frag)}}}

function appendInline(parent,text){const source=String(text||'');let i=0;while(i<source.length){const codeStart=source.indexOf('`',i),boldStart=source.indexOf('**',i);let next=-1,type='';if(codeStart>=0&&(boldStart<0||codeStart<boldStart)){next=codeStart;type='code'}else if(boldStart>=0){next=boldStart;type='bold'}if(next<0){parent.append(document.createTextNode(source.slice(i)));break}if(next>i)parent.append(document.createTextNode(source.slice(i,next)));if(type==='code'){const end=source.indexOf('`',next+1);if(end<0){parent.append(document.createTextNode(source.slice(next)));break}const el=document.createElement('code');el.textContent=source.slice(next+1,end);parent.append(el);i=end+1}else{const end=source.indexOf('**',next+2);if(end<0){parent.append(document.createTextNode(source.slice(next)));break}const el=document.createElement('strong');appendInline(el,source.slice(next+2,end));parent.append(el);i=end+2}}}
function renderLiveMarkdown(container,markdown){const src=String(markdown||'').replace(/\r/g,'');const lines=src.split('\n');const frag=document.createDocumentFragment();let list=null,listType='';const closeList=()=>{list=null;listType=''};for(const raw of lines){const line=raw.trimEnd();if(!line.trim()){closeList();continue}let m=line.match(/^\s*[-*+]\s+(.+)$/);if(m){if(!list||listType!=='ul'){list=document.createElement('ul');listType='ul';frag.append(list)}const li=document.createElement('li');appendInline(li,m[1]);list.append(li);continue}m=line.match(/^\s*\d+[.)]\s+(.+)$/);if(m){if(!list||listType!=='ol'){list=document.createElement('ol');listType='ol';frag.append(list)}const li=document.createElement('li');appendInline(li,m[1]);list.append(li);continue}closeList();m=line.match(/^\s*(#{1,4})\s+(.+)$/);if(m){const h=document.createElement(`h${Math.min(4,m[1].length+2)}`);appendInline(h,m[2]);frag.append(h);continue}const p=document.createElement('p');appendInline(p,line.trim());frag.append(p)}container.replaceChildren(frag)}

function copyLive(text,button){const done=()=>{const old=button.textContent;button.textContent='Copied';setTimeout(()=>button.textContent=old,800)};if(navigator.clipboard?.writeText)navigator.clipboard.writeText(text).then(done).catch(()=>{})}
function downloadLive(name,text,type='text/plain;charset=utf-8'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportLive(files){const payload={format:'swrlz-code-artifact-v1',capturedAt:new Date().toISOString(),files:(files||[]).map(f=>({name:f.name,language:f.lang,content:f.text}))};downloadLive(`swrlz-code-${new Date().toISOString().replace(/[:.]/g,'-')}.json`,JSON.stringify(payload,null,2),'application/json;charset=utf-8')}
function liveName(lang,index){const base=LIVE_NAMES[lang]||`code-${index+1}.txt`;if(index===0)return base;const dot=base.lastIndexOf('.');return dot<0?`${base}-${index+1}`:`${base.slice(0,dot)}-${index+1}${base.slice(dot)}`}
function parseLiveCode(text){const source=String(text||''),first=source.indexOf('```');if(first<0)return null;const files=[],detailsParts=[];const lead=source.slice(0,first).trim();let cursor=first;while(cursor<source.length){const open=source.indexOf('```',cursor);if(open<0)break;const headerStart=open+3,lineEnd=source.indexOf('\n',headerStart);if(lineEnd<0){files.push({lang:(source.slice(headerStart).trim().split(/\s+/)[0]||'text').toLowerCase(),text:'',open:true});break}const header=source.slice(headerStart,lineEnd).trim(),lang=(header.split(/\s+/)[0]||'text').toLowerCase(),codeStart=lineEnd+1,close=source.indexOf('```',codeStart);if(close<0){files.push({lang,text:source.slice(codeStart),open:true});break}files.push({lang,text:source.slice(codeStart,close),open:false});const after=close+3,nextOpen=source.indexOf('```',after);const prose=source.slice(after,nextOpen<0?source.length:nextOpen).trim();if(prose)detailsParts.push(prose);if(nextOpen<0)break;cursor=nextOpen}if(!files.length)return null;return {lead,files:files.map((f,i)=>({...f,name:liveName(f.lang,i)})),details:detailsParts.join('\n\n').trim()}}
function ensureLiveArtifact(bubble){let outer=bubble.querySelector(':scope > .swrlz-live-code-artifact');if(outer)return outer;outer=document.createElement('section');outer.className='swrlz-code-artifact swrlz-live-code-artifact';outer.innerHTML=`<div class="swrlz-code-artifact-head"><div class="swrlz-code-artifact-title"><strong>Code artifact</strong><span class="swrlz-live-code-meta">Preparing code…</span></div><div class="swrlz-code-artifact-actions"><button type="button" class="swrlz-live-copy-all">Copy all</button><button type="button" class="swrlz-live-export-all">Export all</button></div></div><div class="swrlz-code-artifact-lead swrlz-live-code-lead"></div><div class="swrlz-code-workspace"><div class="swrlz-code-tabs" role="tablist"></div><div class="swrlz-code-stage"></div></div><div class="swrlz-code-artifact-notes swrlz-live-code-notes" hidden><div class="swrlz-code-notes-title">Details</div><div class="swrlz-live-code-details"></div></div>`;outer.__files=[];outer.__active=0;outer.__source='';outer.querySelector('.swrlz-live-copy-all').addEventListener('click',e=>copyLive((outer.__files||[]).map(f=>`// ${f.name}\n${f.text}`).join('\n\n'),e.currentTarget));outer.querySelector('.swrlz-live-export-all').addEventListener('click',()=>exportLive(outer.__files||[]));bubble.replaceChildren(outer);return outer}
function renderLiveArtifact(bubble,text){const parsed=parseLiveCode(text);if(!parsed)return false;const outer=ensureLiveArtifact(bubble);outer.__source=String(text||'');outer.__files=parsed.files;const title=outer.querySelector('.swrlz-code-artifact-title strong'),meta=outer.querySelector('.swrlz-live-code-meta');if(title)title.textContent=parsed.files.length>1?'Code project':'Code artifact';if(meta){const active=parsed.files[Math.min(outer.__active||0,parsed.files.length-1)]||parsed.files[0];meta.textContent=parsed.files.length>1?`${parsed.files.length} files · ${active.name}`:`${active.name} · ${active.lang}`}
  const lead=outer.querySelector('.swrlz-live-code-lead');if(lead){const leadText=parsed.lead||'Here’s the requested code example:';if(lead.dataset.source!==leadText){lead.dataset.source=leadText;renderLiveMarkdown(lead,leadText)}}
  const tabs=outer.querySelector('.swrlz-code-tabs'),stage=outer.querySelector('.swrlz-code-stage');while(tabs.children.length<parsed.files.length){const index=tabs.children.length,tab=document.createElement('button');tab.type='button';tab.className='swrlz-code-tab';tab.setAttribute('role','tab');tab.addEventListener('click',()=>{outer.__active=index;renderLiveArtifact(bubble,outer.__source)});tabs.append(tab);const pane=document.createElement('section');pane.className='swrlz-code-pane';pane.innerHTML=`<div class="swrlz-code-pane-tools"><span></span><button type="button" class="swrlz-live-copy-one">Copy</button><button type="button" class="swrlz-live-download-one">Download</button></div><div class="swrlz-code-inner"><pre><code></code></pre></div>`;pane.querySelector('.swrlz-live-copy-one').addEventListener('click',e=>{const f=(outer.__files||[])[index];if(f)copyLive(f.text,e.currentTarget)});pane.querySelector('.swrlz-live-download-one').addEventListener('click',()=>{const f=(outer.__files||[])[index];if(f)downloadLive(f.name,f.text)});stage.append(pane)}while(tabs.children.length>parsed.files.length){tabs.lastElementChild.remove();stage.lastElementChild.remove()}
  if(parsed.files.length===1)tabs.classList.add('single');else tabs.classList.remove('single');const active=Math.min(outer.__active||0,parsed.files.length-1);outer.__active=active;parsed.files.forEach((file,index)=>{const tab=tabs.children[index],pane=stage.children[index];tab.textContent=file.name;tab.setAttribute('aria-selected',index===active?'true':'false');pane.hidden=index!==active;const label=pane.querySelector('.swrlz-code-pane-tools span');if(label)label.textContent=`${file.lang} · ${file.name}${file.open?' · writing…':''}`;const code=pane.querySelector('code');if(code&&code.textContent!==file.text)code.textContent=file.text});
  const notes=outer.querySelector('.swrlz-live-code-notes'),details=outer.querySelector('.swrlz-live-code-details');if(notes&&details){notes.hidden=!parsed.details;if(parsed.details&&details.dataset.source!==parsed.details){details.dataset.source=parsed.details;renderLiveMarkdown(details,parsed.details)}}return true}

function stableStreamText(article,message){if(!article||!message)return false;article.dataset.messageState=String(message.state||'streaming');const bubble=article.querySelector('.bubble');if(!bubble)return false;const next=String(message.text||'');if(next){if(!renderLiveArtifact(bubble,next)){let live=bubble.querySelector(':scope > .swrlz-live-stream-text');if(!live){live=document.createElement('div');live.className='swrlz-live-stream-text';bubble.replaceChildren(live)}if(live.textContent!==next)live.textContent=next}}else{let waiting=bubble.querySelector(':scope > .swrlz-live-status');if(!waiting){waiting=document.createElement('div');waiting.className='empty-response swrlz-live-status';const mark=document.createElement('span');mark.className='thinking-mark',txt=document.createElement('span');txt.className='swrlz-live-status-text';waiting.append(mark,txt);bubble.replaceChildren(waiting)}const txt=waiting.querySelector('.swrlz-live-status-text');if(txt)txt.textContent=phaseText(message)}updateLiveActivity(article,message);return true}
function finalizeArticle(article,message){if(!article||!message)return false;const replacement=renderMessage(message);if(!replacement)return false;try{const bubble=replacement.querySelector('.bubble');if(bubble&&typeof window.__swrlzDecorateCodeArtifact==='function')window.__swrlzDecorateCodeArtifact(bubble)}catch(_){}article.replaceWith(replacement);lastRenderedHeight=null;flushSave();return true}
function patchActiveArticle(scroll){const message=activeStreamMessage(),article=activeArticle(message);if(!message||!article)return false;const streaming=message.state==='streaming'||message.state==='cancelling',patched=streaming?stableStreamText(article,message):finalizeArticle(article,message);if(patched&&scroll&&streaming)requestAnimationFrame(()=>centerTailLine(article));return patched}
scheduleRender=function(scroll=false){pendingScroll=pendingScroll||Boolean(scroll);if(renderQueued)return;renderQueued=true;requestAnimationFrame(()=>{renderQueued=false;const shouldScroll=pendingScroll;pendingScroll=false;const message=activeStreamMessage(),patched=message?patchActiveArticle(shouldScroll):false;if(!patched){lastRenderedHeight=null;render(false)}})};
const style=document.createElement('style');style.textContent=`
.swrlz-live-stream-text{white-space:pre-wrap;overflow-wrap:anywhere;word-break:break-word;min-height:1.4em;contain:content}
.swrlz-live-status{min-height:1.4em;color:var(--muted);display:flex;align-items:center;gap:9px}
.swrlz-live-trace{margin-top:8px}
.swrlz-live-code-lead p,.swrlz-live-code-details p{margin:.6em 0;line-height:1.65}
.swrlz-live-code-lead p:first-child,.swrlz-live-code-details p:first-child{margin-top:0}
.swrlz-live-code-details ul,.swrlz-live-code-details ol{margin:.6em 0;padding-left:1.45em}
.swrlz-live-code-details li{margin:.4em 0;line-height:1.6}
.swrlz-live-code-lead code,.swrlz-live-code-details code{padding:.08em .32em;border:1px solid rgba(145,169,192,.12);border-radius:6px;background:rgba(3,9,18,.72);font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;color:var(--secondary)}
.swrlz-live-code-lead strong,.swrlz-live-code-details strong{color:var(--text);font-weight:750}
.swrlz-live-code-artifact .swrlz-code-inner pre{margin:0}
.message[data-message-state="streaming"] .bubble{will-change:auto;backface-visibility:hidden;transform:translateZ(0)}
`;document.head.append(style);
window.addEventListener('pagehide',flushSave);window.addEventListener('beforeunload',flushSave);
})();
