(()=>{"use strict";
if(window.__swrlzRuntimeLoaderV3)return;
const REV='61',ROOT='/live/assets/';
const diagnostics={contractId:'swrlz_chat_cooperative_boot_v3',revision:REV,startedAt:performance.now(),critical:[],functional:[],decorative:[],styleErrors:[],scriptErrors:[],timeouts:[],mainReady:false,functionalReady:false,decorativeReady:false};window.__swrlzRuntimeLoaderV3=diagnostics;
const styles=['chat_boot_guard.css','chat_enhancements.css','chat_user_settings_v2.css','themes/ice-dragon/ice-dragon-theme.css','themes/ice-dragon/ice-dragon-art-v2.css','themes/ice-dragon/ice-dragon-shell-v1.css','themes/ice-dragon/ice-dragon-brand-v1.css','themes/ice-dragon/ice-dragon-polish-v2.css','themes/ice-dragon/ice-dragon-response-layout-v1.css','chat_mobile_viewport_fix.css','chat_code_artifacts.css'];
const critical=['chat_debug_log_v1.js','chat_debug_ui_v1.js','chat_transport_boundary_v1.js','chat_frontend_boot_v2.js','chat_boot_guard.js','chat_version.js','chat_boot_ready.js'];
const functional=['chat_admin_session.js','chat_enhancements.js','chat_google_server_config.js','themes/ice-dragon/ice-dragon-theme-v3.2.js','chat_account_identity_v1.js','chat_user_settings_v2.js','chat_stream_focus.js','chat_stream_incremental.js','chat_committed_contract_bridge.js','chat_committed_output_v3.js','chat_activity_immediate.js','chat_user_time_context.js','chat_context_canonical.js','chat_background_resume_v2.js','chat_response_presence.js','chat_transcript_sync.js','chat_terminal_integrity.js','chat_context_capacity.js','chat_context_camera.js','chat_response_polish.js','chat_turn_integrity_v1.js','chat_response_layout_v1.js','chat_theme_settings_v1.js','chat_scroll_gesture_v1.js','chat_code_artifacts.js'];const decorativeCore=['themes/ice-dragon/ice-dragon-art-loader-v17.js'],wallpaper='themes/ice-dragon/ice-dragon-wallpaper-v22.js';
const src=p=>`${ROOT}${p}?v=${REV}`,sleep=ms=>new Promise(r=>setTimeout(r,ms)),dbg=(t,m,d)=>{try{window.__swrlzDebug?.log(t,m,d)}catch(_){ }};
function establishInitialTheme(){let saved='';try{saved=localStorage.getItem('swrlz.chat.theme')||''}catch(_){ }const initial=saved==='default'?'default':'ice-dragon';if(initial==='ice-dragon')document.body.dataset.swrlzTheme='ice-dragon';else delete document.body.dataset.swrlzTheme;diagnostics.initialTheme=initial}
function startStyles(){for(const path of styles){if(document.querySelector(`link[data-swrlz-runtime-style="${CSS.escape(path)}"]`))continue;const link=document.createElement('link');link.rel='stylesheet';link.href=src(path);link.dataset.swrlzRuntimeStyle=path;link.addEventListener('load',()=>dbg('asset','style-loaded',{path}),{once:true});link.addEventListener('error',()=>{diagnostics.styleErrors.push(path);dbg('error','style-error',{path})},{once:true});document.head.appendChild(link)}}
function loadOne(path,bucket,timeoutMs=5000){return new Promise(resolve=>{if(document.querySelector(`script[data-swrlz-runtime-script="${CSS.escape(path)}"]`))return resolve();let settled=false;dbg('asset','script-start',{path});const done=kind=>{if(settled)return;settled=true;clearTimeout(timer);if(kind==='load')bucket?.push(path);if(kind==='error')diagnostics.scriptErrors.push(path);if(kind==='timeout')diagnostics.timeouts.push(path);dbg(kind==='load'?'asset':'error',`script-${kind}`,{path});resolve()};const script=document.createElement('script');script.src=src(path);script.async=false;script.dataset.swrlzRuntimeScript=path;script.addEventListener('load',()=>done('load'),{once:true});script.addEventListener('error',()=>done('error'),{once:true});const timer=setTimeout(()=>done('timeout'),timeoutMs);document.body.appendChild(script)})}
async function loadSerial(paths,bucket,yieldMs=0){for(const path of paths){await loadOne(path,bucket);if(yieldMs)await sleep(yieldMs)}}function whenIdle(fn,timeout=1600){if('requestIdleCallback'in window)requestIdleCallback(fn,{timeout});else setTimeout(fn,180)}
async function boot(){establishInitialTheme();startStyles();loadOne(wallpaper,diagnostics.decorative,4000);await loadSerial(critical,diagnostics.critical,6);dbg('boot','critical-ready',{revision:REV,loaded:diagnostics.critical});diagnostics.mainReady=true;diagnostics.mainReadyAt=performance.now();document.documentElement.classList.add('swrlz-main-chat-ready');window.dispatchEvent(new CustomEvent('swrlz:main-chat-ready',{detail:{revision:REV,at:diagnostics.mainReadyAt}}));setTimeout(async()=>{await loadSerial(functional,diagnostics.functional,8);diagnostics.functionalReady=true;diagnostics.functionalReadyAt=performance.now();dbg('boot','functional-ready',{loaded:diagnostics.functional,errors:diagnostics.scriptErrors,timeouts:diagnostics.timeouts});document.documentElement.classList.add('swrlz-chat-functional-ready');window.dispatchEvent(new CustomEvent('swrlz:chat-functional-ready',{detail:{revision:REV,errors:[...diagnostics.scriptErrors],timeouts:[...diagnostics.timeouts],at:diagnostics.functionalReadyAt}}));whenIdle(async()=>{await loadSerial(decorativeCore,diagnostics.decorative);diagnostics.decorativeReady=true;diagnostics.decorativeReadyAt=performance.now();dbg('boot','decorative-ready',{loaded:diagnostics.decorative});document.documentElement.classList.add('swrlz-chat-decorative-ready');window.dispatchEvent(new CustomEvent('swrlz:chat-decorative-ready',{detail:{revision:REV,errors:[...diagnostics.scriptErrors],timeouts:[...diagnostics.timeouts],at:diagnostics.decorativeReadyAt}}))},900)},40)}
boot().catch(error=>{diagnostics.fatal=String(error?.message||error);dbg('error','boot-fatal',{message:diagnostics.fatal,stack:error?.stack});console.error('[§wyrlz cooperative chat boot]',error)});})();