(()=>{"use strict";
if(window.__swrlzBackgroundResumeV3)return;
// Claim the legacy install guard before the cooperative loader reaches v2. The
// old implementation deliberately cancelled a healthy reader on foreground /
// pageshow / online events; that could reopen a turn after visible output and
// create duplicate canonical POSTs. v3 reconnects only after an actual stream
// interruption and treats terminal state as irreversible.
window.__swrlzBackgroundResumeInstalled=true;
const CONTRACT="same-generation-resume-v3",SESSION="resumable-v1";
const nativeFetch=window.fetch.bind(window),encoder=new TextEncoder();
const ctl={version:3,contract:CONTRACT,reconnects:0,terminalStops:0,lastError:""};
window.__swrlzBackgroundResumeV3=ctl;
function isStream(input,init){try{const method=String(init?.method||input?.method||"GET").toUpperCase(),url=typeof input==="string"?input:String(input?.url||"");return method==="POST"&&/(?:[?&]action=stream(?:&|$)|\/stream(?:[?#]|$))/i.test(url)}catch(_){return false}}
function body(init){if(typeof init?.body!=="string")return null;try{const value=JSON.parse(init.body);return value&&typeof value==="object"?value:null}catch(_){return null}}
function canonical(payload){let value={...payload};try{const prepare=window.__swrlzCanonicalContext?.preparePayload;if(typeof prepare==="function")value=prepare(value)||value}catch(_){ }return value}
function messageFor(rid){try{for(const thread of state?.threads||[])for(const message of thread?.messages||[])if(message?.role==="assistant"&&String(message?.meta?.requestId||"")===rid)return message}catch(_){ }return null}
function terminal(message){const stateName=String(message?.state||"").toLowerCase();return ["complete","failed","cancelled"].includes(stateName)||["COMPLETE","ERROR","CANCELLED"].includes(String(message?.meta?.phase||"").toUpperCase())}
function trace(message,reason){if(!message||terminal(message))return;message.meta=message.meta||{};message.meta.phase="RECONNECTING";message.meta.trail=Array.isArray(message.meta.trail)?message.meta.trail:[];const last=message.meta.trail.at(-1);if(last?.phase!=="RECONNECTING"||last?.reason!==reason)message.meta.trail.push({seq:Number(last?.seq||0)+1,phase:"RECONNECTING",reason,at:Date.now()});if(message.meta.trail.length>30)message.meta.trail=message.meta.trail.slice(-30);try{saveState();scheduleRender(false)}catch(_){ }}
function abortError(){try{return new DOMException("Aborted","AbortError")}catch(_){const e=new Error("Aborted");e.name="AbortError";return e}}
function sleep(ms,signal){return new Promise((resolve,reject)=>{if(signal?.aborted)return reject(abortError());const timer=setTimeout(done,ms);function done(){signal?.removeEventListener?.("abort",stop);resolve()}function stop(){clearTimeout(timer);reject(abortError())}signal?.addEventListener?.("abort",stop,{once:true})})}
async function online(signal){while(!navigator.onLine){await new Promise((resolve,reject)=>{if(signal?.aborted)return reject(abortError());const yes=()=>{cleanup();resolve()},no=()=>{cleanup();reject(abortError())};function cleanup(){window.removeEventListener("online",yes);signal?.removeEventListener?.("abort",no)}window.addEventListener("online",yes,{once:true});signal?.addEventListener?.("abort",no,{once:true})})}}
async function reopen(input,init,payload,lastSeq,signal){await online(signal);return nativeFetch(input,{...init,signal,body:JSON.stringify({...payload,resumeAfterSeq:Math.max(0,Number(lastSeq||0))})})}
function resilient(input,init,payload,first){const rid=String(payload.requestId||""),message=messageFor(rid),signal=init.signal;let response=first,lastSeq=0,done=false,reconnects=0;return new ReadableStream({async start(controller){try{while(!done){if(signal?.aborted)throw abortError();if(terminal(message)){done=true;ctl.terminalStops++;break}if(!response){reconnects++;ctl.reconnects++;trace(message,"The response stream was interrupted. Reconnecting to the same server generation session.");let delay=250;while(!response&&!done){if(signal?.aborted)throw abortError();if(terminal(message)){done=true;ctl.terminalStops++;break}try{const candidate=await reopen(input,init,payload,lastSeq,signal);if(candidate.status===401||candidate.status===403)throw new Error(`Resume authorization failed (HTTP ${candidate.status}).`);if(candidate.status===404||candidate.status===410)throw new Error(`Generation session unavailable (HTTP ${candidate.status}).`);if(candidate.status===409){await sleep(delay,signal);delay=Math.min(2500,Math.round(delay*1.5));continue}if(!candidate.ok)throw new Error(`Resume HTTP ${candidate.status}`);response=candidate}catch(error){ctl.lastError=String(error?.message||error);await sleep(delay,signal);delay=Math.min(3000,Math.round(delay*1.6))}}}if(done)break;const reader=response.body?.getReader?.();if(!reader)throw new Error("Streaming response body is unavailable.");const decoder=new TextDecoder();let buffer="",interrupted=false;try{while(!done){const part=await reader.read();if(part.done){interrupted=true;break}buffer+=decoder.decode(part.value,{stream:true});let nl;while((nl=buffer.indexOf("\n"))>=0){const line=buffer.slice(0,nl).trim();buffer=buffer.slice(nl+1);if(!line)continue;let event;try{event=JSON.parse(line)}catch(_){controller.enqueue(encoder.encode(line+"\n"));continue}const seq=Number(event?.seq||0);if(Number.isInteger(seq)&&seq>lastSeq){lastSeq=seq;controller.enqueue(encoder.encode(JSON.stringify(event)+"\n"));if(["COMPLETED","FAILED","CANCELLED"].includes(String(event?.type||""))){done=true;break}}}if(terminal(message)){done=true;ctl.terminalStops++;break}}}catch(error){if(signal?.aborted)throw error;ctl.lastError=String(error?.message||error);interrupted=true}finally{try{reader.releaseLock()}catch(_){ }}if(done)break;response=null;if(!interrupted)await sleep(120,signal)}controller.close()}catch(error){ctl.lastError=String(error?.message||error);controller.error(error)}}})}
window.fetch=async function(input,init={}){if(!isStream(input,init))return nativeFetch(input,init);const parsed=body(init);if(!parsed)return nativeFetch(input,init);const payload=canonical(parsed),next={...init,body:JSON.stringify(payload)};const response=await nativeFetch(input,next);if(response.headers.get("x-swrlz-generation-session")!==SESSION||!response.body)return response;const headers=new Headers(response.headers);headers.set("x-swrlz-browser-continuity",CONTRACT);return new Response(resilient(input,next,payload,response),{status:response.status,statusText:response.statusText,headers})};
window.__swrlzBackgroundResume={version:7,contract:CONTRACT,continuityPolicy:"actual-stream-interruption-only; terminal-is-irreversible",nudgeActive:()=>false};
})();
